// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: tsn_service/pkg/structures/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// A new TSN stream/reservation was requested.
	EventType_STREAM_ADDED EventType = 1
	// An existing TSN stream/reservation was removed.
	EventType_STREAM_REMOVED EventType = 2
	// A network/topology event was detected.
	EventType_NETWORK_EVENT EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "STREAM_ADDED",
		2: "STREAM_REMOVED",
		3: "NETWORK_EVENT",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"STREAM_ADDED":           1,
		"STREAM_REMOVED":         2,
		"NETWORK_EVENT":          3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_tsn_service_pkg_structures_notification_notification_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_tsn_service_pkg_structures_notification_notification_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{0}
}

type NetworkTrigger int32

const (
	NetworkTrigger_NETWORK_TRIGGER_UNSPECIFIED NetworkTrigger = 0
	NetworkTrigger_LINK_DOWN                   NetworkTrigger = 1
	NetworkTrigger_LINK_UP                     NetworkTrigger = 2
	NetworkTrigger_NODE_DOWN                   NetworkTrigger = 3
	NetworkTrigger_NODE_UP                     NetworkTrigger = 4
	NetworkTrigger_TOPOLOGY_CHANGED            NetworkTrigger = 5
	NetworkTrigger_RESOURCE_THRESHOLD          NetworkTrigger = 6
	NetworkTrigger_MANUAL_RECALCULATION        NetworkTrigger = 7
)

// Enum value maps for NetworkTrigger.
var (
	NetworkTrigger_name = map[int32]string{
		0: "NETWORK_TRIGGER_UNSPECIFIED",
		1: "LINK_DOWN",
		2: "LINK_UP",
		3: "NODE_DOWN",
		4: "NODE_UP",
		5: "TOPOLOGY_CHANGED",
		6: "RESOURCE_THRESHOLD",
		7: "MANUAL_RECALCULATION",
	}
	NetworkTrigger_value = map[string]int32{
		"NETWORK_TRIGGER_UNSPECIFIED": 0,
		"LINK_DOWN":                   1,
		"LINK_UP":                     2,
		"NODE_DOWN":                   3,
		"NODE_UP":                     4,
		"TOPOLOGY_CHANGED":            5,
		"RESOURCE_THRESHOLD":          6,
		"MANUAL_RECALCULATION":        7,
	}
)

func (x NetworkTrigger) Enum() *NetworkTrigger {
	p := new(NetworkTrigger)
	*p = x
	return p
}

func (x NetworkTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_tsn_service_pkg_structures_notification_notification_proto_enumTypes[1].Descriptor()
}

func (NetworkTrigger) Type() protoreflect.EnumType {
	return &file_tsn_service_pkg_structures_notification_notification_proto_enumTypes[1]
}

func (x NetworkTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkTrigger.Descriptor instead.
func (NetworkTrigger) EnumDescriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type       EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=notification.EventType" json:"type,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Service that generated the event.
	//
	// Examples:
	//
	//	"monitor-service"
	//	"main-service"
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_StreamAdded
	//	*Event_StreamRemoved
	//	*Event_NetworkEvent
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetStreamAdded() *StreamAdded {
	if x != nil {
		if x, ok := x.Payload.(*Event_StreamAdded); ok {
			return x.StreamAdded
		}
	}
	return nil
}

func (x *Event) GetStreamRemoved() *StreamRemoved {
	if x != nil {
		if x, ok := x.Payload.(*Event_StreamRemoved); ok {
			return x.StreamRemoved
		}
	}
	return nil
}

func (x *Event) GetNetworkEvent() *NetworkEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_NetworkEvent); ok {
			return x.NetworkEvent
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_StreamAdded struct {
	StreamAdded *StreamAdded `protobuf:"bytes,10,opt,name=stream_added,json=streamAdded,proto3,oneof"`
}

type Event_StreamRemoved struct {
	StreamRemoved *StreamRemoved `protobuf:"bytes,11,opt,name=stream_removed,json=streamRemoved,proto3,oneof"`
}

type Event_NetworkEvent struct {
	NetworkEvent *NetworkEvent `protobuf:"bytes,12,opt,name=network_event,json=networkEvent,proto3,oneof"`
}

func (*Event_StreamAdded) isEvent_Payload() {}

func (*Event_StreamRemoved) isEvent_Payload() {}

func (*Event_NetworkEvent) isEvent_Payload() {}

type StreamAdded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier(s) associated with the stream request.
	RequestIds []string `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	// Optional stream identifier.
	StreamId      string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAdded) Reset() {
	*x = StreamAdded{}
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAdded) ProtoMessage() {}

func (x *StreamAdded) ProtoReflect() protoreflect.Message {
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAdded.ProtoReflect.Descriptor instead.
func (*StreamAdded) Descriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAdded) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

func (x *StreamAdded) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamRemoved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier(s) associated with the stream request.
	RequestIds []string `protobuf:"bytes,1,rep,name=request_ids,json=requestIds,proto3" json:"request_ids,omitempty"`
	// Optional stream identifier.
	StreamId      string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRemoved) Reset() {
	*x = StreamRemoved{}
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRemoved) ProtoMessage() {}

func (x *StreamRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRemoved.ProtoReflect.Descriptor instead.
func (*StreamRemoved) Descriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRemoved) GetRequestIds() []string {
	if x != nil {
		return x.RequestIds
	}
	return nil
}

func (x *StreamRemoved) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamRemoved) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NetworkEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Trigger NetworkTrigger         `protobuf:"varint,1,opt,name=trigger,proto3,enum=notification.NetworkTrigger" json:"trigger,omitempty"`
	// Objects known to be affected by the event.
	AffectedNodeIds []string `protobuf:"bytes,2,rep,name=affected_node_ids,json=affectedNodeIds,proto3" json:"affected_node_ids,omitempty"`
	AffectedLinkIds []string `protobuf:"bytes,3,rep,name=affected_link_ids,json=affectedLinkIds,proto3" json:"affected_link_ids,omitempty"`
	Reason          string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkEvent) GetTrigger() NetworkTrigger {
	if x != nil {
		return x.Trigger
	}
	return NetworkTrigger_NETWORK_TRIGGER_UNSPECIFIED
}

func (x *NetworkEvent) GetAffectedNodeIds() []string {
	if x != nil {
		return x.AffectedNodeIds
	}
	return nil
}

func (x *NetworkEvent) GetAffectedLinkIds() []string {
	if x != nil {
		return x.AffectedLinkIds
	}
	return nil
}

func (x *NetworkEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NotifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notification was accepted by the TSN service.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Optional identifier for the internal configuration/reconfiguration
	// workflow started by the event.
	WorkflowId    string `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *NotifyResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *NotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tsn_service_pkg_structures_notification_notification_proto protoreflect.FileDescriptor

const file_tsn_service_pkg_structures_notification_notification_proto_rawDesc = "" +
	"\n" +
	":tsn_service/pkg/structures/notification/notification.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.notification.EventTypeR\x04type\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12>\n" +
	"\fstream_added\x18\n" +
	" \x01(\v2\x19.notification.StreamAddedH\x00R\vstreamAdded\x12D\n" +
	"\x0estream_removed\x18\v \x01(\v2\x1b.notification.StreamRemovedH\x00R\rstreamRemoved\x12A\n" +
	"\rnetwork_event\x18\f \x01(\v2\x1a.notification.NetworkEventH\x00R\fnetworkEventB\t\n" +
	"\apayload\"K\n" +
	"\vStreamAdded\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"e\n" +
	"\rStreamRemoved\x12\x1f\n" +
	"\vrequest_ids\x18\x01 \x03(\tR\n" +
	"requestIds\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb6\x01\n" +
	"\fNetworkEvent\x126\n" +
	"\atrigger\x18\x01 \x01(\x0e2\x1c.notification.NetworkTriggerR\atrigger\x12*\n" +
	"\x11affected_node_ids\x18\x02 \x03(\tR\x0faffectedNodeIds\x12*\n" +
	"\x11affected_link_ids\x18\x03 \x03(\tR\x0faffectedLinkIds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"g\n" +
	"\x0eNotifyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*`\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTREAM_ADDED\x10\x01\x12\x12\n" +
	"\x0eSTREAM_REMOVED\x10\x02\x12\x11\n" +
	"\rNETWORK_EVENT\x10\x03*\xb1\x01\n" +
	"\x0eNetworkTrigger\x12\x1f\n" +
	"\x1bNETWORK_TRIGGER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tLINK_DOWN\x10\x01\x12\v\n" +
	"\aLINK_UP\x10\x02\x12\r\n" +
	"\tNODE_DOWN\x10\x03\x12\v\n" +
	"\aNODE_UP\x10\x04\x12\x14\n" +
	"\x10TOPOLOGY_CHANGED\x10\x05\x12\x16\n" +
	"\x12RESOURCE_THRESHOLD\x10\x06\x12\x18\n" +
	"\x14MANUAL_RECALCULATION\x10\a2M\n" +
	"\fNotification\x12=\n" +
	"\x06Notify\x12\x13.notification.Event\x1a\x1c.notification.NotifyResponse\"\x00B>Z<OpenCNC/tsn_service/pkg/structures/notification;notificationb\x06proto3"

var (
	file_tsn_service_pkg_structures_notification_notification_proto_rawDescOnce sync.Once
	file_tsn_service_pkg_structures_notification_notification_proto_rawDescData []byte
)

func file_tsn_service_pkg_structures_notification_notification_proto_rawDescGZIP() []byte {
	file_tsn_service_pkg_structures_notification_notification_proto_rawDescOnce.Do(func() {
		file_tsn_service_pkg_structures_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsn_service_pkg_structures_notification_notification_proto_rawDesc), len(file_tsn_service_pkg_structures_notification_notification_proto_rawDesc)))
	})
	return file_tsn_service_pkg_structures_notification_notification_proto_rawDescData
}

var file_tsn_service_pkg_structures_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tsn_service_pkg_structures_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tsn_service_pkg_structures_notification_notification_proto_goTypes = []any{
	(EventType)(0),                // 0: notification.EventType
	(NetworkTrigger)(0),           // 1: notification.NetworkTrigger
	(*Event)(nil),                 // 2: notification.Event
	(*StreamAdded)(nil),           // 3: notification.StreamAdded
	(*StreamRemoved)(nil),         // 4: notification.StreamRemoved
	(*NetworkEvent)(nil),          // 5: notification.NetworkEvent
	(*NotifyResponse)(nil),        // 6: notification.NotifyResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_tsn_service_pkg_structures_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.Event.type:type_name -> notification.EventType
	7, // 1: notification.Event.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 2: notification.Event.stream_added:type_name -> notification.StreamAdded
	4, // 3: notification.Event.stream_removed:type_name -> notification.StreamRemoved
	5, // 4: notification.Event.network_event:type_name -> notification.NetworkEvent
	1, // 5: notification.NetworkEvent.trigger:type_name -> notification.NetworkTrigger
	2, // 6: notification.Notification.Notify:input_type -> notification.Event
	6, // 7: notification.Notification.Notify:output_type -> notification.NotifyResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tsn_service_pkg_structures_notification_notification_proto_init() }
func file_tsn_service_pkg_structures_notification_notification_proto_init() {
	if File_tsn_service_pkg_structures_notification_notification_proto != nil {
		return
	}
	file_tsn_service_pkg_structures_notification_notification_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_StreamAdded)(nil),
		(*Event_StreamRemoved)(nil),
		(*Event_NetworkEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsn_service_pkg_structures_notification_notification_proto_rawDesc), len(file_tsn_service_pkg_structures_notification_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsn_service_pkg_structures_notification_notification_proto_goTypes,
		DependencyIndexes: file_tsn_service_pkg_structures_notification_notification_proto_depIdxs,
		EnumInfos:         file_tsn_service_pkg_structures_notification_notification_proto_enumTypes,
		MessageInfos:      file_tsn_service_pkg_structures_notification_notification_proto_msgTypes,
	}.Build()
	File_tsn_service_pkg_structures_notification_notification_proto = out.File
	file_tsn_service_pkg_structures_notification_notification_proto_goTypes = nil
	file_tsn_service_pkg_structures_notification_notification_proto_depIdxs = nil
}
