// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/structures/sync/syncdiag.proto

package syncdiag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Current state of gate cycle relative to expected schedule (e.g., "ON_TIME", "LATE", "EARLY")
type GateSyncDiagnostics_SyncState int32

const (
	GateSyncDiagnostics_SYNC_STATE_UNSPECIFIED GateSyncDiagnostics_SyncState = 0
	GateSyncDiagnostics_ON_TIME                GateSyncDiagnostics_SyncState = 1
	GateSyncDiagnostics_LATE                   GateSyncDiagnostics_SyncState = 2
	GateSyncDiagnostics_EARLY                  GateSyncDiagnostics_SyncState = 3
)

// Enum value maps for GateSyncDiagnostics_SyncState.
var (
	GateSyncDiagnostics_SyncState_name = map[int32]string{
		0: "SYNC_STATE_UNSPECIFIED",
		1: "ON_TIME",
		2: "LATE",
		3: "EARLY",
	}
	GateSyncDiagnostics_SyncState_value = map[string]int32{
		"SYNC_STATE_UNSPECIFIED": 0,
		"ON_TIME":                1,
		"LATE":                   2,
		"EARLY":                  3,
	}
)

func (x GateSyncDiagnostics_SyncState) Enum() *GateSyncDiagnostics_SyncState {
	p := new(GateSyncDiagnostics_SyncState)
	*p = x
	return p
}

func (x GateSyncDiagnostics_SyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateSyncDiagnostics_SyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_structures_sync_syncdiag_proto_enumTypes[0].Descriptor()
}

func (GateSyncDiagnostics_SyncState) Type() protoreflect.EnumType {
	return &file_common_structures_sync_syncdiag_proto_enumTypes[0]
}

func (x GateSyncDiagnostics_SyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateSyncDiagnostics_SyncState.Descriptor instead.
func (GateSyncDiagnostics_SyncState) EnumDescriptor() ([]byte, []int) {
	return file_common_structures_sync_syncdiag_proto_rawDescGZIP(), []int{0, 0}
}

// Represents the synchronization state of a gate control mechanism
type GateSyncDiagnostics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GateInstanceName string                 `protobuf:"bytes,1,opt,name=gate_instance_name,json=gateInstanceName,proto3" json:"gate_instance_name,omitempty"` // Name of the gate instance being monitored
	// Timestamp of the last successful sync event (nanoseconds since epoch or device uptime)
	LastSyncTimeNs uint64 `protobuf:"varint,2,opt,name=last_sync_time_ns,json=lastSyncTimeNs,proto3" json:"last_sync_time_ns,omitempty"`
	// Number of sync failures since last reset
	SyncFailureCount uint32 `protobuf:"varint,3,opt,name=sync_failure_count,json=syncFailureCount,proto3" json:"sync_failure_count,omitempty"`
	// Is the gate currently considered synchronized and healthy?
	IsSynchronized bool `protobuf:"varint,4,opt,name=is_synchronized,json=isSynchronized,proto3" json:"is_synchronized,omitempty"`
	// Offset between local clock and grandmaster clock (nanoseconds)
	ClockOffsetNs int64 `protobuf:"varint,5,opt,name=clock_offset_ns,json=clockOffsetNs,proto3" json:"clock_offset_ns,omitempty"`
	// Root mean square (RMS) error of the synchronization offset (nanoseconds)
	SyncRmsErrorNs uint64 `protobuf:"varint,6,opt,name=sync_rms_error_ns,json=syncRmsErrorNs,proto3" json:"sync_rms_error_ns,omitempty"`
	// Last detected gate schedule mismatch count (e.g., unexpected gate state changes)
	GateMismatchCount uint32                        `protobuf:"varint,7,opt,name=gate_mismatch_count,json=gateMismatchCount,proto3" json:"gate_mismatch_count,omitempty"`
	SyncState         GateSyncDiagnostics_SyncState `protobuf:"varint,8,opt,name=sync_state,json=syncState,proto3,enum=syncdiag.GateSyncDiagnostics_SyncState" json:"sync_state,omitempty"`
	// Optional human-readable status message or comment
	StatusMessage string `protobuf:"bytes,9,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateSyncDiagnostics) Reset() {
	*x = GateSyncDiagnostics{}
	mi := &file_common_structures_sync_syncdiag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateSyncDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateSyncDiagnostics) ProtoMessage() {}

func (x *GateSyncDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_sync_syncdiag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateSyncDiagnostics.ProtoReflect.Descriptor instead.
func (*GateSyncDiagnostics) Descriptor() ([]byte, []int) {
	return file_common_structures_sync_syncdiag_proto_rawDescGZIP(), []int{0}
}

func (x *GateSyncDiagnostics) GetGateInstanceName() string {
	if x != nil {
		return x.GateInstanceName
	}
	return ""
}

func (x *GateSyncDiagnostics) GetLastSyncTimeNs() uint64 {
	if x != nil {
		return x.LastSyncTimeNs
	}
	return 0
}

func (x *GateSyncDiagnostics) GetSyncFailureCount() uint32 {
	if x != nil {
		return x.SyncFailureCount
	}
	return 0
}

func (x *GateSyncDiagnostics) GetIsSynchronized() bool {
	if x != nil {
		return x.IsSynchronized
	}
	return false
}

func (x *GateSyncDiagnostics) GetClockOffsetNs() int64 {
	if x != nil {
		return x.ClockOffsetNs
	}
	return 0
}

func (x *GateSyncDiagnostics) GetSyncRmsErrorNs() uint64 {
	if x != nil {
		return x.SyncRmsErrorNs
	}
	return 0
}

func (x *GateSyncDiagnostics) GetGateMismatchCount() uint32 {
	if x != nil {
		return x.GateMismatchCount
	}
	return 0
}

func (x *GateSyncDiagnostics) GetSyncState() GateSyncDiagnostics_SyncState {
	if x != nil {
		return x.SyncState
	}
	return GateSyncDiagnostics_SYNC_STATE_UNSPECIFIED
}

func (x *GateSyncDiagnostics) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_common_structures_sync_syncdiag_proto protoreflect.FileDescriptor

const file_common_structures_sync_syncdiag_proto_rawDesc = "" +
	"\n" +
	"%common/structures/sync/syncdiag.proto\x12\bsyncdiag\"\x82\x04\n" +
	"\x13GateSyncDiagnostics\x12,\n" +
	"\x12gate_instance_name\x18\x01 \x01(\tR\x10gateInstanceName\x12)\n" +
	"\x11last_sync_time_ns\x18\x02 \x01(\x04R\x0elastSyncTimeNs\x12,\n" +
	"\x12sync_failure_count\x18\x03 \x01(\rR\x10syncFailureCount\x12'\n" +
	"\x0fis_synchronized\x18\x04 \x01(\bR\x0eisSynchronized\x12&\n" +
	"\x0fclock_offset_ns\x18\x05 \x01(\x03R\rclockOffsetNs\x12)\n" +
	"\x11sync_rms_error_ns\x18\x06 \x01(\x04R\x0esyncRmsErrorNs\x12.\n" +
	"\x13gate_mismatch_count\x18\a \x01(\rR\x11gateMismatchCount\x12F\n" +
	"\n" +
	"sync_state\x18\b \x01(\x0e2'.syncdiag.GateSyncDiagnostics.SyncStateR\tsyncState\x12%\n" +
	"\x0estatus_message\x18\t \x01(\tR\rstatusMessage\"I\n" +
	"\tSyncState\x12\x1a\n" +
	"\x16SYNC_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aON_TIME\x10\x01\x12\b\n" +
	"\x04LATE\x10\x02\x12\t\n" +
	"\x05EARLY\x10\x03B8Z6OpenCNC_config_service/common/structures/sync;syncdiagb\x06proto3"

var (
	file_common_structures_sync_syncdiag_proto_rawDescOnce sync.Once
	file_common_structures_sync_syncdiag_proto_rawDescData []byte
)

func file_common_structures_sync_syncdiag_proto_rawDescGZIP() []byte {
	file_common_structures_sync_syncdiag_proto_rawDescOnce.Do(func() {
		file_common_structures_sync_syncdiag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_sync_syncdiag_proto_rawDesc), len(file_common_structures_sync_syncdiag_proto_rawDesc)))
	})
	return file_common_structures_sync_syncdiag_proto_rawDescData
}

var file_common_structures_sync_syncdiag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_structures_sync_syncdiag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_structures_sync_syncdiag_proto_goTypes = []any{
	(GateSyncDiagnostics_SyncState)(0), // 0: syncdiag.GateSyncDiagnostics.SyncState
	(*GateSyncDiagnostics)(nil),        // 1: syncdiag.GateSyncDiagnostics
}
var file_common_structures_sync_syncdiag_proto_depIdxs = []int32{
	0, // 0: syncdiag.GateSyncDiagnostics.sync_state:type_name -> syncdiag.GateSyncDiagnostics.SyncState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_structures_sync_syncdiag_proto_init() }
func file_common_structures_sync_syncdiag_proto_init() {
	if File_common_structures_sync_syncdiag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_sync_syncdiag_proto_rawDesc), len(file_common_structures_sync_syncdiag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_sync_syncdiag_proto_goTypes,
		DependencyIndexes: file_common_structures_sync_syncdiag_proto_depIdxs,
		EnumInfos:         file_common_structures_sync_syncdiag_proto_enumTypes,
		MessageInfos:      file_common_structures_sync_syncdiag_proto_msgTypes,
	}.Build()
	File_common_structures_sync_syncdiag_proto = out.File
	file_common_structures_sync_syncdiag_proto_goTypes = nil
	file_common_structures_sync_syncdiag_proto_depIdxs = nil
}
