// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: monitor_service/structures/grpc_server/service.proto

package service

import (
	monitoring "OpenCNC/monitor_service/structures/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilitiesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Resource      *monitoring.ResourceKey `protobuf:"bytes,1,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilitiesRequest) GetResource() *monitoring.ResourceKey {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Capabilities  []*monitoring.Capability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetCapabilities() []*monitoring.Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type StartMonitoringRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      *monitoring.ResourceKey `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Settings      []*MonitoringSetting    `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMonitoringRequest) Reset() {
	*x = StartMonitoringRequest{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMonitoringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMonitoringRequest) ProtoMessage() {}

func (x *StartMonitoringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMonitoringRequest.ProtoReflect.Descriptor instead.
func (*StartMonitoringRequest) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartMonitoringRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartMonitoringRequest) GetResource() *monitoring.ResourceKey {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *StartMonitoringRequest) GetSettings() []*MonitoringSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type MonitoringSetting struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId   string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	PollIntervalMs uint32                 `protobuf:"varint,2,opt,name=poll_interval_ms,json=pollIntervalMs,proto3" json:"poll_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonitoringSetting) Reset() {
	*x = MonitoringSetting{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringSetting) ProtoMessage() {}

func (x *MonitoringSetting) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringSetting.ProtoReflect.Descriptor instead.
func (*MonitoringSetting) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{3}
}

func (x *MonitoringSetting) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *MonitoringSetting) GetPollIntervalMs() uint32 {
	if x != nil {
		return x.PollIntervalMs
	}
	return 0
}

type MonitoringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringResponse) Reset() {
	*x = MonitoringResponse{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringResponse) ProtoMessage() {}

func (x *MonitoringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringResponse.ProtoReflect.Descriptor instead.
func (*MonitoringResponse) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{4}
}

func (x *MonitoringResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MonitoringResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopMonitoringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMonitoringRequest) Reset() {
	*x = StopMonitoringRequest{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMonitoringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMonitoringRequest) ProtoMessage() {}

func (x *StopMonitoringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMonitoringRequest.ProtoReflect.Descriptor instead.
func (*StopMonitoringRequest) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{5}
}

func (x *StopMonitoringRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// //// TO REMOVE ////////
type TestRollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PortName      string                 `protobuf:"bytes,3,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRollbackRequest) Reset() {
	*x = TestRollbackRequest{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRollbackRequest) ProtoMessage() {}

func (x *TestRollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRollbackRequest.ProtoReflect.Descriptor instead.
func (*TestRollbackRequest) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{6}
}

func (x *TestRollbackRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestRollbackRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TestRollbackRequest) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

type TestRollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRollbackResponse) Reset() {
	*x = TestRollbackResponse{}
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRollbackResponse) ProtoMessage() {}

func (x *TestRollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_grpc_server_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRollbackResponse.ProtoReflect.Descriptor instead.
func (*TestRollbackResponse) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP(), []int{7}
}

func (x *TestRollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestRollbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_monitor_service_structures_grpc_server_service_proto protoreflect.FileDescriptor

const file_monitor_service_structures_grpc_server_service_proto_rawDesc = "" +
	"\n" +
	"4monitor_service/structures/grpc_server/service.proto\x12\aservice\x1a6monitor_service/structures/monitoring/monitoring.proto\"\\\n" +
	"\x13CapabilitiesRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x17.monitoring.ResourceKeyH\x00R\bresource\x88\x01\x01B\v\n" +
	"\t_resource\"R\n" +
	"\x14CapabilitiesResponse\x12:\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x16.monitoring.CapabilityR\fcapabilities\"\x95\x01\n" +
	"\x16StartMonitoringRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\bresource\x18\x02 \x01(\v2\x17.monitoring.ResourceKeyR\bresource\x126\n" +
	"\bsettings\x18\x03 \x03(\v2\x1a.service.MonitoringSettingR\bsettings\"b\n" +
	"\x11MonitoringSetting\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12(\n" +
	"\x10poll_interval_ms\x18\x02 \x01(\rR\x0epollIntervalMs\"H\n" +
	"\x12MonitoringResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15StopMonitoringRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x13TestRollbackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1b\n" +
	"\tport_name\x18\x03 \x01(\tR\bportName\"J\n" +
	"\x14TestRollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcd\x02\n" +
	"\x0eMonitorService\x12N\n" +
	"\x0fGetCapabilities\x12\x1c.service.CapabilitiesRequest\x1a\x1d.service.CapabilitiesResponse\x12O\n" +
	"\x0fStartMonitoring\x12\x1f.service.StartMonitoringRequest\x1a\x1b.service.MonitoringResponse\x12M\n" +
	"\x0eStopMonitoring\x12\x1e.service.StopMonitoringRequest\x1a\x1b.service.MonitoringResponse\x12K\n" +
	"\fTestRollback\x12\x1c.service.TestRollbackRequest\x1a\x1d.service.TestRollbackResponseBHZFOpenCNC/monitor_service/structures/grpc_service;serviceb\x06proto3"

var (
	file_monitor_service_structures_grpc_server_service_proto_rawDescOnce sync.Once
	file_monitor_service_structures_grpc_server_service_proto_rawDescData []byte
)

func file_monitor_service_structures_grpc_server_service_proto_rawDescGZIP() []byte {
	file_monitor_service_structures_grpc_server_service_proto_rawDescOnce.Do(func() {
		file_monitor_service_structures_grpc_server_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_service_structures_grpc_server_service_proto_rawDesc), len(file_monitor_service_structures_grpc_server_service_proto_rawDesc)))
	})
	return file_monitor_service_structures_grpc_server_service_proto_rawDescData
}

var file_monitor_service_structures_grpc_server_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_monitor_service_structures_grpc_server_service_proto_goTypes = []any{
	(*CapabilitiesRequest)(nil),    // 0: service.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),   // 1: service.CapabilitiesResponse
	(*StartMonitoringRequest)(nil), // 2: service.StartMonitoringRequest
	(*MonitoringSetting)(nil),      // 3: service.MonitoringSetting
	(*MonitoringResponse)(nil),     // 4: service.MonitoringResponse
	(*StopMonitoringRequest)(nil),  // 5: service.StopMonitoringRequest
	(*TestRollbackRequest)(nil),    // 6: service.TestRollbackRequest
	(*TestRollbackResponse)(nil),   // 7: service.TestRollbackResponse
	(*monitoring.ResourceKey)(nil), // 8: monitoring.ResourceKey
	(*monitoring.Capability)(nil),  // 9: monitoring.Capability
}
var file_monitor_service_structures_grpc_server_service_proto_depIdxs = []int32{
	8, // 0: service.CapabilitiesRequest.resource:type_name -> monitoring.ResourceKey
	9, // 1: service.CapabilitiesResponse.capabilities:type_name -> monitoring.Capability
	8, // 2: service.StartMonitoringRequest.resource:type_name -> monitoring.ResourceKey
	3, // 3: service.StartMonitoringRequest.settings:type_name -> service.MonitoringSetting
	0, // 4: service.MonitorService.GetCapabilities:input_type -> service.CapabilitiesRequest
	2, // 5: service.MonitorService.StartMonitoring:input_type -> service.StartMonitoringRequest
	5, // 6: service.MonitorService.StopMonitoring:input_type -> service.StopMonitoringRequest
	6, // 7: service.MonitorService.TestRollback:input_type -> service.TestRollbackRequest
	1, // 8: service.MonitorService.GetCapabilities:output_type -> service.CapabilitiesResponse
	4, // 9: service.MonitorService.StartMonitoring:output_type -> service.MonitoringResponse
	4, // 10: service.MonitorService.StopMonitoring:output_type -> service.MonitoringResponse
	7, // 11: service.MonitorService.TestRollback:output_type -> service.TestRollbackResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_monitor_service_structures_grpc_server_service_proto_init() }
func file_monitor_service_structures_grpc_server_service_proto_init() {
	if File_monitor_service_structures_grpc_server_service_proto != nil {
		return
	}
	file_monitor_service_structures_grpc_server_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_service_structures_grpc_server_service_proto_rawDesc), len(file_monitor_service_structures_grpc_server_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_service_structures_grpc_server_service_proto_goTypes,
		DependencyIndexes: file_monitor_service_structures_grpc_server_service_proto_depIdxs,
		MessageInfos:      file_monitor_service_structures_grpc_server_service_proto_msgTypes,
	}.Build()
	File_monitor_service_structures_grpc_server_service_proto = out.File
	file_monitor_service_structures_grpc_server_service_proto_goTypes = nil
	file_monitor_service_structures_grpc_server_service_proto_depIdxs = nil
}
