syntax = "proto3";

package service;

option go_package = "OpenCNC/monitor_service/structures/grpc_service;service";

import "monitor_service/structures/monitoring/monitoring.proto";

message CapabilitiesRequest {
  optional monitoring.ResourceKey resource = 1;
}

message CapabilitiesResponse {
  repeated monitoring.Capability capabilities = 1;
}
///////////////

message StartMonitoringRequest {
  string id = 1;
  monitoring.ResourceKey resource = 2;
  repeated MonitoringSetting settings = 3;
}

message MonitoringSetting {
  string capability_id = 1;
  uint32 poll_interval_ms = 2;
}

message MonitoringResponse {
  bool success = 1;
  string message = 2;
}

message StopMonitoringRequest {
  string id = 1;
}

//////////////
service MonitorService {
  rpc GetCapabilities(CapabilitiesRequest)
      returns (CapabilitiesResponse);
  
  rpc StartMonitoring(StartMonitoringRequest)
      returns (MonitoringResponse);

  rpc StopMonitoring(StopMonitoringRequest)
      returns (MonitoringResponse);

  rpc TestRollback(TestRollbackRequest)
  returns (TestRollbackResponse);
}

////// TO REMOVE ////////
message TestRollbackRequest {
  string id = 1;
  string node_name = 2;
  string port_name = 3;
}

message TestRollbackResponse {
  bool success = 1;
  string message = 2;
}