// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/structures/module-registry/moduleregistry.proto

package moduleregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YangModules   []*YangModule          `protobuf:"bytes,1,rep,name=YangModules,proto3" json:"YangModules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRegistry) Reset() {
	*x = ModuleRegistry{}
	mi := &file_common_structures_module_registry_moduleregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRegistry) ProtoMessage() {}

func (x *ModuleRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_module_registry_moduleregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRegistry.ProtoReflect.Descriptor instead.
func (*ModuleRegistry) Descriptor() ([]byte, []int) {
	return file_common_structures_module_registry_moduleregistry_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRegistry) GetYangModules() []*YangModule {
	if x != nil {
		return x.YangModules
	}
	return nil
}

type YangModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Structure     string                 `protobuf:"bytes,2,opt,name=Structure,json=structure,proto3" json:"Structure,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=Revision,json=revision,proto3" json:"Revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YangModule) Reset() {
	*x = YangModule{}
	mi := &file_common_structures_module_registry_moduleregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YangModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YangModule) ProtoMessage() {}

func (x *YangModule) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_module_registry_moduleregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YangModule.ProtoReflect.Descriptor instead.
func (*YangModule) Descriptor() ([]byte, []int) {
	return file_common_structures_module_registry_moduleregistry_proto_rawDescGZIP(), []int{1}
}

func (x *YangModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YangModule) GetStructure() string {
	if x != nil {
		return x.Structure
	}
	return ""
}

func (x *YangModule) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

var File_common_structures_module_registry_moduleregistry_proto protoreflect.FileDescriptor

const file_common_structures_module_registry_moduleregistry_proto_rawDesc = "" +
	"\n" +
	"6common/structures/module-registry/moduleregistry.proto\x12\x0emoduleregistry\"N\n" +
	"\x0eModuleRegistry\x12<\n" +
	"\vYangModules\x18\x01 \x03(\v2\x1a.moduleregistry.YangModuleR\vYangModules\"Z\n" +
	"\n" +
	"YangModule\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tStructure\x18\x02 \x01(\tR\tstructure\x12\x1a\n" +
	"\bRevision\x18\x03 \x01(\tR\brevisionB\x12Z\x10./moduleregistryb\x06proto3"

var (
	file_common_structures_module_registry_moduleregistry_proto_rawDescOnce sync.Once
	file_common_structures_module_registry_moduleregistry_proto_rawDescData []byte
)

func file_common_structures_module_registry_moduleregistry_proto_rawDescGZIP() []byte {
	file_common_structures_module_registry_moduleregistry_proto_rawDescOnce.Do(func() {
		file_common_structures_module_registry_moduleregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_module_registry_moduleregistry_proto_rawDesc), len(file_common_structures_module_registry_moduleregistry_proto_rawDesc)))
	})
	return file_common_structures_module_registry_moduleregistry_proto_rawDescData
}

var file_common_structures_module_registry_moduleregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_structures_module_registry_moduleregistry_proto_goTypes = []any{
	(*ModuleRegistry)(nil), // 0: moduleregistry.ModuleRegistry
	(*YangModule)(nil),     // 1: moduleregistry.YangModule
}
var file_common_structures_module_registry_moduleregistry_proto_depIdxs = []int32{
	1, // 0: moduleregistry.ModuleRegistry.YangModules:type_name -> moduleregistry.YangModule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_structures_module_registry_moduleregistry_proto_init() }
func file_common_structures_module_registry_moduleregistry_proto_init() {
	if File_common_structures_module_registry_moduleregistry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_module_registry_moduleregistry_proto_rawDesc), len(file_common_structures_module_registry_moduleregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_module_registry_moduleregistry_proto_goTypes,
		DependencyIndexes: file_common_structures_module_registry_moduleregistry_proto_depIdxs,
		MessageInfos:      file_common_structures_module_registry_moduleregistry_proto_msgTypes,
	}.Build()
	File_common_structures_module_registry_moduleregistry_proto = out.File
	file_common_structures_module_registry_moduleregistry_proto_goTypes = nil
	file_common_structures_module_registry_moduleregistry_proto_depIdxs = nil
}
