syntax = "proto3";

package monitoring;

option go_package = "OpenCNC/monitor_service/structures/monitoring;monitoring";

import "google/protobuf/timestamp.proto";

enum DataType{
  RAW = 0;
  METRIC = 1;
}

// a capability is a counter or a metric
message Capability {
  string name = 1; //the id of counter or metric
  string description = 2;
  DataType kind = 3;
}

// Runtime settings for the monitoring service.
message MonitoringSettings {
  repeated Counter counters = 1; // Counters or operational values to collect from devices.
  repeated Metric metrics = 2;   // Metrics derived from sampled counters.
}

// A raw value periodically read from a device.
message Counter {
  string name = 1;             // Human-readable name/ that is the identifier as well
  string path = 3;             // NETCONF XPath, gNMI path, SNMP OID, ...
  uint32 poll_interval_ms = 4; // Sampling period.
  string description = 5;      // Optional description.
}

// A metric computed from one or more counters.
message Metric {
  string name = 1;                   // Human-readable name.
  MetricType type = 2;
  uint32 evaluation_interval_ms = 3; // Evaluation interval (can differ from polling interval)
  repeated string input_ids = 4;   // Counters/metrics used to compute this metric.
  uint32 window_size = 5;            // Number of samples used in the calculation. 
  repeated Threshold thresholds = 6; // Alarm policy. e.g. 70% warning, 90% critical (those are 2 thresholds)
  string description = 7;            // Optional description.
}

enum MetricType {

  METRIC_TYPE_UNSPECIFIED = 0;


  // Performance
  UTILIZATION = 1;
  THROUGHPUT = 2;
  LOSS_RATE = 3;
  ERROR_RATE = 4;
  DISCARD_RATE = 5;
  DELAY = 6;
  JITTER = 7;


  // TSN specific
  QUEUE_OCCUPANCY = 8;
  QUEUE_DROP_RATE = 9;
  CLOCK_SYNC_ERROR = 10;
  GATE_ERROR_RATE = 11;
  CONFIGURATION_MISMATCH = 12;
  RESOURCE_EXHAUSTION = 13;
  DEVICE_UNREACHABLE = 14;
  CONGESTION_LEVEL = 15;
  PACKET_RATE = 16;
}

// Thresholds for triggering alarms.
message Threshold {
  double value = 1;
  Comparison comparison = 2; // how to read the threshold
  MonitoringEvent event = 3; // every threshod signals an event
}

enum Comparison {
  COMPARISON_UNSPECIFIED = 0;

  GREATER_THAN = 1;
  GREATER_OR_EQUAL = 2;
  LESS_THAN = 3;
  LESS_OR_EQUAL = 4;
  EQUAL = 5;
  NOT_EQUAL = 6;
}

////////////////////////////
// Data Readings 
////////////////////////////

// Raw data collected by plugins or Output of the meter
message DataSample {
  string id = 1;
  ResourceKey source = 2;
  google.protobuf.Timestamp timestamp = 3;
  double value = 4;
  DataType kind = 5;
}

// Key to match DataSample and event source
message ResourceKey {
  string node_id = 1;
  optional string port_id = 2;
}

////////////////////////////
// Events 
////////////////////////////

message MonitoringEvent {
    optional ResourceKey source = 1; // populated at runtime
    EventType type = 2;
    Severity severity = 3; //  description
    repeated EventAction actions = 4; //every event triggers some actions
}
enum EventAction {
    ACTION_UNSPECIFIED = 0;
    NOTIFY = 1;
    ALERT = 2;
    CHANGE_MONITORING_LEVEL = 3;
    REQUEST_RECONFIGURATION = 4;
    REQUEST_ROLLBACK = 5;
}

enum EventType {
    TYPE_UNSPECIFIED = 0;
    DEVICE_LOST = 1;
    LINK_DOWN = 2;
    CONGESTION = 3;
    BUFFER_OVERFLOW = 4;
    SYNCHRONIZATION_ERROR = 5;
    CONFIGURATION_FAILURE = 6;
    PERFORMANCE_DEGRADATION = 7;
}

enum Severity {
  SEVERITY_UNSPECIFIED = 0;
  INFO     = 1;
  WARNING  = 2;
  CRITICAL = 3;
}