// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: monitor_service/structures/monitoring/monitoring_events.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED        EventType = 0
	EventType_EVENT_DEVICE_LOST             EventType = 1
	EventType_EVENT_LINK_DOWN               EventType = 2
	EventType_EVENT_CONGESTION              EventType = 3
	EventType_EVENT_BUFFER_OVERFLOW         EventType = 4
	EventType_EVENT_SYNCHRONIZATION_ERROR   EventType = 5
	EventType_EVENT_CONFIGURATION_FAILURE   EventType = 6
	EventType_EVENT_PERFORMANCE_DEGRADATION EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_DEVICE_LOST",
		2: "EVENT_LINK_DOWN",
		3: "EVENT_CONGESTION",
		4: "EVENT_BUFFER_OVERFLOW",
		5: "EVENT_SYNCHRONIZATION_ERROR",
		6: "EVENT_CONFIGURATION_FAILURE",
		7: "EVENT_PERFORMANCE_DEGRADATION",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":        0,
		"EVENT_DEVICE_LOST":             1,
		"EVENT_LINK_DOWN":               2,
		"EVENT_CONGESTION":              3,
		"EVENT_BUFFER_OVERFLOW":         4,
		"EVENT_SYNCHRONIZATION_ERROR":   5,
		"EVENT_CONFIGURATION_FAILURE":   6,
		"EVENT_PERFORMANCE_DEGRADATION": 7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescGZIP(), []int{0}
}

type EventAction int32

const (
	EventAction_EVENT_ACTION_UNSPECIFIED             EventAction = 0
	EventAction_EVENT_ACTION_NOTIFY                  EventAction = 1
	EventAction_EVENT_ACTION_CHANGE_MONITORING_LEVEL EventAction = 2
	EventAction_EVENT_ACTION_REQUEST_RECONFIGURATION EventAction = 3
	EventAction_EVENT_ACTION_REQUEST_ROLLBACK        EventAction = 4
)

// Enum value maps for EventAction.
var (
	EventAction_name = map[int32]string{
		0: "EVENT_ACTION_UNSPECIFIED",
		1: "EVENT_ACTION_NOTIFY",
		2: "EVENT_ACTION_CHANGE_MONITORING_LEVEL",
		3: "EVENT_ACTION_REQUEST_RECONFIGURATION",
		4: "EVENT_ACTION_REQUEST_ROLLBACK",
	}
	EventAction_value = map[string]int32{
		"EVENT_ACTION_UNSPECIFIED":             0,
		"EVENT_ACTION_NOTIFY":                  1,
		"EVENT_ACTION_CHANGE_MONITORING_LEVEL": 2,
		"EVENT_ACTION_REQUEST_RECONFIGURATION": 3,
		"EVENT_ACTION_REQUEST_ROLLBACK":        4,
	}
)

func (x EventAction) Enum() *EventAction {
	p := new(EventAction)
	*p = x
	return p
}

func (x EventAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventAction) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes[1].Descriptor()
}

func (EventAction) Type() protoreflect.EnumType {
	return &file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes[1]
}

func (x EventAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventAction.Descriptor instead.
func (EventAction) EnumDescriptor() ([]byte, []int) {
	return file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescGZIP(), []int{1}
}

type MonitoringEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SourceMetric  string                 `protobuf:"bytes,3,opt,name=source_metric,json=sourceMetric,proto3" json:"source_metric,omitempty"`
	Type          EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=monitoring.EventType" json:"type,omitempty"`
	Action        EventAction            `protobuf:"varint,5,opt,name=action,proto3,enum=monitoring.EventAction" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringEvent) Reset() {
	*x = MonitoringEvent{}
	mi := &file_monitor_service_structures_monitoring_monitoring_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringEvent) ProtoMessage() {}

func (x *MonitoringEvent) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_service_structures_monitoring_monitoring_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringEvent.ProtoReflect.Descriptor instead.
func (*MonitoringEvent) Descriptor() ([]byte, []int) {
	return file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescGZIP(), []int{0}
}

func (x *MonitoringEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonitoringEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MonitoringEvent) GetSourceMetric() string {
	if x != nil {
		return x.SourceMetric
	}
	return ""
}

func (x *MonitoringEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *MonitoringEvent) GetAction() EventAction {
	if x != nil {
		return x.Action
	}
	return EventAction_EVENT_ACTION_UNSPECIFIED
}

func (x *MonitoringEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_monitor_service_structures_monitoring_monitoring_events_proto protoreflect.FileDescriptor

const file_monitor_service_structures_monitoring_monitoring_events_proto_rawDesc = "" +
	"\n" +
	"=monitor_service/structures/monitoring/monitoring_events.proto\x12\n" +
	"monitoring\"\xdd\x01\n" +
	"\x0fMonitoringEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\rsource_metric\x18\x03 \x01(\tR\fsourceMetric\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.monitoring.EventTypeR\x04type\x12/\n" +
	"\x06action\x18\x05 \x01(\x0e2\x17.monitoring.EventActionR\x06action\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription*\xe9\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_DEVICE_LOST\x10\x01\x12\x13\n" +
	"\x0fEVENT_LINK_DOWN\x10\x02\x12\x14\n" +
	"\x10EVENT_CONGESTION\x10\x03\x12\x19\n" +
	"\x15EVENT_BUFFER_OVERFLOW\x10\x04\x12\x1f\n" +
	"\x1bEVENT_SYNCHRONIZATION_ERROR\x10\x05\x12\x1f\n" +
	"\x1bEVENT_CONFIGURATION_FAILURE\x10\x06\x12!\n" +
	"\x1dEVENT_PERFORMANCE_DEGRADATION\x10\a*\xbb\x01\n" +
	"\vEventAction\x12\x1c\n" +
	"\x18EVENT_ACTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EVENT_ACTION_NOTIFY\x10\x01\x12(\n" +
	"$EVENT_ACTION_CHANGE_MONITORING_LEVEL\x10\x02\x12(\n" +
	"$EVENT_ACTION_REQUEST_RECONFIGURATION\x10\x03\x12!\n" +
	"\x1dEVENT_ACTION_REQUEST_ROLLBACK\x10\x04B)Z'common/structures/monitoring;monitoringb\x06proto3"

var (
	file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescOnce sync.Once
	file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescData []byte
)

func file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescGZIP() []byte {
	file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescOnce.Do(func() {
		file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_service_structures_monitoring_monitoring_events_proto_rawDesc), len(file_monitor_service_structures_monitoring_monitoring_events_proto_rawDesc)))
	})
	return file_monitor_service_structures_monitoring_monitoring_events_proto_rawDescData
}

var file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_monitor_service_structures_monitoring_monitoring_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_monitor_service_structures_monitoring_monitoring_events_proto_goTypes = []any{
	(EventType)(0),          // 0: monitoring.EventType
	(EventAction)(0),        // 1: monitoring.EventAction
	(*MonitoringEvent)(nil), // 2: monitoring.MonitoringEvent
}
var file_monitor_service_structures_monitoring_monitoring_events_proto_depIdxs = []int32{
	0, // 0: monitoring.MonitoringEvent.type:type_name -> monitoring.EventType
	1, // 1: monitoring.MonitoringEvent.action:type_name -> monitoring.EventAction
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_monitor_service_structures_monitoring_monitoring_events_proto_init() }
func file_monitor_service_structures_monitoring_monitoring_events_proto_init() {
	if File_monitor_service_structures_monitoring_monitoring_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_service_structures_monitoring_monitoring_events_proto_rawDesc), len(file_monitor_service_structures_monitoring_monitoring_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_monitor_service_structures_monitoring_monitoring_events_proto_goTypes,
		DependencyIndexes: file_monitor_service_structures_monitoring_monitoring_events_proto_depIdxs,
		EnumInfos:         file_monitor_service_structures_monitoring_monitoring_events_proto_enumTypes,
		MessageInfos:      file_monitor_service_structures_monitoring_monitoring_events_proto_msgTypes,
	}.Build()
	File_monitor_service_structures_monitoring_monitoring_events_proto = out.File
	file_monitor_service_structures_monitoring_monitoring_events_proto_goTypes = nil
	file_monitor_service_structures_monitoring_monitoring_events_proto_depIdxs = nil
}
