syntax = "proto3";

package monitoring;

option go_package = "common/structures/monitoring;monitoring";


message MonitoringEvent {

    string id = 1;

    string node_id = 2;

    string source_metric = 3;

    EventType type = 4;

    EventAction action = 5;

    string description = 6;
}


enum EventType {

    EVENT_TYPE_UNSPECIFIED = 0;

    EVENT_DEVICE_LOST = 1;

    EVENT_LINK_DOWN = 2;

    EVENT_CONGESTION = 3;

    EVENT_BUFFER_OVERFLOW = 4;

    EVENT_SYNCHRONIZATION_ERROR = 5;

    EVENT_CONFIGURATION_FAILURE = 6;

    EVENT_PERFORMANCE_DEGRADATION = 7;
}

enum EventAction {

    EVENT_ACTION_UNSPECIFIED = 0;

    EVENT_ACTION_NOTIFY = 1;

    EVENT_ACTION_CHANGE_MONITORING_LEVEL = 2;

    EVENT_ACTION_REQUEST_RECONFIGURATION = 3;

    EVENT_ACTION_REQUEST_ROLLBACK = 4;
}