// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/structures/stp/stp.proto

package stp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Port roles according to Clause 13.25.5
type PortRole int32

const (
	PortRole_PORT_ROLE_UNSPECIFIED       PortRole = 0 // Unknown or not assigned
	PortRole_PORT_ROLE_ROOT              PortRole = 1 // Root port
	PortRole_PORT_ROLE_DESIGNATED        PortRole = 2 // Designated port
	PortRole_PORT_ROLE_ALTERNATE         PortRole = 3 // Alternate port
	PortRole_PORT_ROLE_BACKUP            PortRole = 4 // Backup port
	PortRole_PORT_ROLE_MASTER            PortRole = 5 // MSTI master port (Clause 13.27.2)
	PortRole_PORT_ROLE_NON_PARTICIPATING PortRole = 6 // Disabled or not participating in STP
)

// Enum value maps for PortRole.
var (
	PortRole_name = map[int32]string{
		0: "PORT_ROLE_UNSPECIFIED",
		1: "PORT_ROLE_ROOT",
		2: "PORT_ROLE_DESIGNATED",
		3: "PORT_ROLE_ALTERNATE",
		4: "PORT_ROLE_BACKUP",
		5: "PORT_ROLE_MASTER",
		6: "PORT_ROLE_NON_PARTICIPATING",
	}
	PortRole_value = map[string]int32{
		"PORT_ROLE_UNSPECIFIED":       0,
		"PORT_ROLE_ROOT":              1,
		"PORT_ROLE_DESIGNATED":        2,
		"PORT_ROLE_ALTERNATE":         3,
		"PORT_ROLE_BACKUP":            4,
		"PORT_ROLE_MASTER":            5,
		"PORT_ROLE_NON_PARTICIPATING": 6,
	}
)

func (x PortRole) Enum() *PortRole {
	p := new(PortRole)
	*p = x
	return p
}

func (x PortRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_stp_stp_proto_enumTypes[0].Descriptor()
}

func (PortRole) Type() protoreflect.EnumType {
	return &file_pkg_structures_stp_stp_proto_enumTypes[0]
}

func (x PortRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortRole.Descriptor instead.
func (PortRole) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_proto_rawDescGZIP(), []int{0}
}

// Port states according to Clause 13.25.6
type PortState int32

const (
	PortState_PORT_STATE_UNSPECIFIED PortState = 0 // Unknown or not assigned
	PortState_PORT_STATE_DISCARDING  PortState = 1 // Not forwarding or learning
	PortState_PORT_STATE_LEARNING    PortState = 2 // Learning MAC addresses but not forwarding
	PortState_PORT_STATE_FORWARDING  PortState = 3 // Forwarding frames
)

// Enum value maps for PortState.
var (
	PortState_name = map[int32]string{
		0: "PORT_STATE_UNSPECIFIED",
		1: "PORT_STATE_DISCARDING",
		2: "PORT_STATE_LEARNING",
		3: "PORT_STATE_FORWARDING",
	}
	PortState_value = map[string]int32{
		"PORT_STATE_UNSPECIFIED": 0,
		"PORT_STATE_DISCARDING":  1,
		"PORT_STATE_LEARNING":    2,
		"PORT_STATE_FORWARDING":  3,
	}
)

func (x PortState) Enum() *PortState {
	p := new(PortState)
	*p = x
	return p
}

func (x PortState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_stp_stp_proto_enumTypes[1].Descriptor()
}

func (PortState) Type() protoreflect.EnumType {
	return &file_pkg_structures_stp_stp_proto_enumTypes[1]
}

func (x PortState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortState.Descriptor instead.
func (PortState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_proto_rawDescGZIP(), []int{1}
}

type StpConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clause 13.5.1 — Global Bridge Control
	// Enable or disable STP on the bridge
	StpEnabled *bool `protobuf:"varint,1,opt,name=stp_enabled,json=stpEnabled,proto3,oneof" json:"stp_enabled,omitempty"`
	// Clause 13.25 — Multiple Spanning Tree Instances (MSTIs)
	SpanningTreeInstances []*SpanningTreeInstance `protobuf:"bytes,2,rep,name=spanning_tree_instances,json=spanningTreeInstances,proto3" json:"spanning_tree_instances,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StpConfiguration) Reset() {
	*x = StpConfiguration{}
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpConfiguration) ProtoMessage() {}

func (x *StpConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpConfiguration.ProtoReflect.Descriptor instead.
func (*StpConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_proto_rawDescGZIP(), []int{0}
}

func (x *StpConfiguration) GetStpEnabled() bool {
	if x != nil && x.StpEnabled != nil {
		return *x.StpEnabled
	}
	return false
}

func (x *StpConfiguration) GetSpanningTreeInstances() []*SpanningTreeInstance {
	if x != nil {
		return x.SpanningTreeInstances
	}
	return nil
}

type SpanningTreeInstance struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceId   string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`         // e.g., "cist", "mst0", "mst1"
	RootBridgeId string                 `protobuf:"bytes,2,opt,name=root_bridge_id,json=rootBridgeId,proto3" json:"root_bridge_id,omitempty"` // Bridge ID for this MSTI root
	// Per-port state/configuration within this instance
	PortStates    []*StpPortState `protobuf:"bytes,3,rep,name=port_states,json=portStates,proto3" json:"port_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanningTreeInstance) Reset() {
	*x = SpanningTreeInstance{}
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanningTreeInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanningTreeInstance) ProtoMessage() {}

func (x *SpanningTreeInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanningTreeInstance.ProtoReflect.Descriptor instead.
func (*SpanningTreeInstance) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_proto_rawDescGZIP(), []int{1}
}

func (x *SpanningTreeInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SpanningTreeInstance) GetRootBridgeId() string {
	if x != nil {
		return x.RootBridgeId
	}
	return ""
}

func (x *SpanningTreeInstance) GetPortStates() []*StpPortState {
	if x != nil {
		return x.PortStates
	}
	return nil
}

type StpPortState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PortId string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// Port role within the STP instance (Clause 13.25.5)
	Role PortRole `protobuf:"varint,2,opt,name=role,proto3,enum=stp.PortRole" json:"role,omitempty"`
	// Port state within the STP instance (Clause 13.25.6)
	State PortState `protobuf:"varint,3,opt,name=state,proto3,enum=stp.PortState" json:"state,omitempty"`
	// Indicates if this port is currently forwarding frames.
	// This is often derived from state but provided explicitly for convenience.
	Forwarding    bool `protobuf:"varint,4,opt,name=forwarding,proto3" json:"forwarding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StpPortState) Reset() {
	*x = StpPortState{}
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpPortState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpPortState) ProtoMessage() {}

func (x *StpPortState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpPortState.ProtoReflect.Descriptor instead.
func (*StpPortState) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_proto_rawDescGZIP(), []int{2}
}

func (x *StpPortState) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *StpPortState) GetRole() PortRole {
	if x != nil {
		return x.Role
	}
	return PortRole_PORT_ROLE_UNSPECIFIED
}

func (x *StpPortState) GetState() PortState {
	if x != nil {
		return x.State
	}
	return PortState_PORT_STATE_UNSPECIFIED
}

func (x *StpPortState) GetForwarding() bool {
	if x != nil {
		return x.Forwarding
	}
	return false
}

var File_pkg_structures_stp_stp_proto protoreflect.FileDescriptor

const file_pkg_structures_stp_stp_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/structures/stp/stp.proto\x12\x03stp\"\x9b\x01\n" +
	"\x10StpConfiguration\x12$\n" +
	"\vstp_enabled\x18\x01 \x01(\bH\x00R\n" +
	"stpEnabled\x88\x01\x01\x12Q\n" +
	"\x17spanning_tree_instances\x18\x02 \x03(\v2\x19.stp.SpanningTreeInstanceR\x15spanningTreeInstancesB\x0e\n" +
	"\f_stp_enabled\"\x91\x01\n" +
	"\x14SpanningTreeInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eroot_bridge_id\x18\x02 \x01(\tR\frootBridgeId\x122\n" +
	"\vport_states\x18\x03 \x03(\v2\x11.stp.StpPortStateR\n" +
	"portStates\"\x90\x01\n" +
	"\fStpPortState\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.stp.PortRoleR\x04role\x12$\n" +
	"\x05state\x18\x03 \x01(\x0e2\x0e.stp.PortStateR\x05state\x12\x1e\n" +
	"\n" +
	"forwarding\x18\x04 \x01(\bR\n" +
	"forwarding*\xb9\x01\n" +
	"\bPortRole\x12\x19\n" +
	"\x15PORT_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePORT_ROLE_ROOT\x10\x01\x12\x18\n" +
	"\x14PORT_ROLE_DESIGNATED\x10\x02\x12\x17\n" +
	"\x13PORT_ROLE_ALTERNATE\x10\x03\x12\x14\n" +
	"\x10PORT_ROLE_BACKUP\x10\x04\x12\x14\n" +
	"\x10PORT_ROLE_MASTER\x10\x05\x12\x1f\n" +
	"\x1bPORT_ROLE_NON_PARTICIPATING\x10\x06*v\n" +
	"\tPortState\x12\x1a\n" +
	"\x16PORT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PORT_STATE_DISCARDING\x10\x01\x12\x17\n" +
	"\x13PORT_STATE_LEARNING\x10\x02\x12\x19\n" +
	"\x15PORT_STATE_FORWARDING\x10\x03B/Z-OpenCNC_config_service/pkg/structures/stp;stpb\x06proto3"

var (
	file_pkg_structures_stp_stp_proto_rawDescOnce sync.Once
	file_pkg_structures_stp_stp_proto_rawDescData []byte
)

func file_pkg_structures_stp_stp_proto_rawDescGZIP() []byte {
	file_pkg_structures_stp_stp_proto_rawDescOnce.Do(func() {
		file_pkg_structures_stp_stp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_stp_stp_proto_rawDesc), len(file_pkg_structures_stp_stp_proto_rawDesc)))
	})
	return file_pkg_structures_stp_stp_proto_rawDescData
}

var file_pkg_structures_stp_stp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_structures_stp_stp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_structures_stp_stp_proto_goTypes = []any{
	(PortRole)(0),                // 0: stp.PortRole
	(PortState)(0),               // 1: stp.PortState
	(*StpConfiguration)(nil),     // 2: stp.StpConfiguration
	(*SpanningTreeInstance)(nil), // 3: stp.SpanningTreeInstance
	(*StpPortState)(nil),         // 4: stp.StpPortState
}
var file_pkg_structures_stp_stp_proto_depIdxs = []int32{
	3, // 0: stp.StpConfiguration.spanning_tree_instances:type_name -> stp.SpanningTreeInstance
	4, // 1: stp.SpanningTreeInstance.port_states:type_name -> stp.StpPortState
	0, // 2: stp.StpPortState.role:type_name -> stp.PortRole
	1, // 3: stp.StpPortState.state:type_name -> stp.PortState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_structures_stp_stp_proto_init() }
func file_pkg_structures_stp_stp_proto_init() {
	if File_pkg_structures_stp_stp_proto != nil {
		return
	}
	file_pkg_structures_stp_stp_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_stp_stp_proto_rawDesc), len(file_pkg_structures_stp_stp_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_stp_stp_proto_goTypes,
		DependencyIndexes: file_pkg_structures_stp_stp_proto_depIdxs,
		EnumInfos:         file_pkg_structures_stp_stp_proto_enumTypes,
		MessageInfos:      file_pkg_structures_stp_stp_proto_msgTypes,
	}.Build()
	File_pkg_structures_stp_stp_proto = out.File
	file_pkg_structures_stp_stp_proto_goTypes = nil
	file_pkg_structures_stp_stp_proto_depIdxs = nil
}
