// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/structures/stp/stp_status.proto

package stp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StpStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*BridgeStpStatus     `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"` // Status of all bridges in the network
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StpStatusReport) Reset() {
	*x = StpStatusReport{}
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpStatusReport) ProtoMessage() {}

func (x *StpStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpStatusReport.ProtoReflect.Descriptor instead.
func (*StpStatusReport) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_status_proto_rawDescGZIP(), []int{0}
}

func (x *StpStatusReport) GetBridges() []*BridgeStpStatus {
	if x != nil {
		return x.Bridges
	}
	return nil
}

type BridgeStpStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BridgeId       string                 `protobuf:"bytes,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`                   // Unique identifier for the bridge (MAC or UUID)
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                         // Matches Node.name in topology
	Instances      []*StpInstanceStatus   `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`                                 // Status of each STP instance on the bridge
	StpEnabled     bool                   `protobuf:"varint,4,opt,name=stp_enabled,json=stpEnabled,proto3" json:"stp_enabled,omitempty"`            // Global STP enable status (Clause 13.5.1)
	BridgePriority string                 `protobuf:"bytes,5,opt,name=bridge_priority,json=bridgePriority,proto3" json:"bridge_priority,omitempty"` // Bridge priority as seen in BPDUs (informational)
	LastUpdatedNs  uint64                 `protobuf:"varint,6,opt,name=last_updated_ns,json=lastUpdatedNs,proto3" json:"last_updated_ns,omitempty"` // Timestamp of last update (nanoseconds since epoch)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BridgeStpStatus) Reset() {
	*x = BridgeStpStatus{}
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeStpStatus) ProtoMessage() {}

func (x *BridgeStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeStpStatus.ProtoReflect.Descriptor instead.
func (*BridgeStpStatus) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_status_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeStpStatus) GetBridgeId() string {
	if x != nil {
		return x.BridgeId
	}
	return ""
}

func (x *BridgeStpStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BridgeStpStatus) GetInstances() []*StpInstanceStatus {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *BridgeStpStatus) GetStpEnabled() bool {
	if x != nil {
		return x.StpEnabled
	}
	return false
}

func (x *BridgeStpStatus) GetBridgePriority() string {
	if x != nil {
		return x.BridgePriority
	}
	return ""
}

func (x *BridgeStpStatus) GetLastUpdatedNs() uint64 {
	if x != nil {
		return x.LastUpdatedNs
	}
	return 0
}

type StpInstanceStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceId         string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`                           // Instance identifier ("cist", "mst0", etc.)
	RootBridgeId       string                 `protobuf:"bytes,2,opt,name=root_bridge_id,json=rootBridgeId,proto3" json:"root_bridge_id,omitempty"`                   // Root bridge ID for this instance
	RootPathCost       uint32                 `protobuf:"varint,3,opt,name=root_path_cost,json=rootPathCost,proto3" json:"root_path_cost,omitempty"`                  // Cost to reach root bridge
	DesignatedBridgeId string                 `protobuf:"bytes,4,opt,name=designated_bridge_id,json=designatedBridgeId,proto3" json:"designated_bridge_id,omitempty"` // Designated bridge ID for this instance
	PortStates         []*PortStpStatus       `protobuf:"bytes,5,rep,name=port_states,json=portStates,proto3" json:"port_states,omitempty"`                           // Per-port STP state information
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StpInstanceStatus) Reset() {
	*x = StpInstanceStatus{}
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpInstanceStatus) ProtoMessage() {}

func (x *StpInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpInstanceStatus.ProtoReflect.Descriptor instead.
func (*StpInstanceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_status_proto_rawDescGZIP(), []int{2}
}

func (x *StpInstanceStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StpInstanceStatus) GetRootBridgeId() string {
	if x != nil {
		return x.RootBridgeId
	}
	return ""
}

func (x *StpInstanceStatus) GetRootPathCost() uint32 {
	if x != nil {
		return x.RootPathCost
	}
	return 0
}

func (x *StpInstanceStatus) GetDesignatedBridgeId() string {
	if x != nil {
		return x.DesignatedBridgeId
	}
	return ""
}

func (x *StpInstanceStatus) GetPortStates() []*PortStpStatus {
	if x != nil {
		return x.PortStates
	}
	return nil
}

type PortStpStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PortId            string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`                                      // Matches Port.id in topology
	Role              PortRole               `protobuf:"varint,2,opt,name=role,proto3,enum=stp.PortRole" json:"role,omitempty"`                                     // Port role (Clause 13.25.5)
	State             PortState              `protobuf:"varint,3,opt,name=state,proto3,enum=stp.PortState" json:"state,omitempty"`                                  // Port state (Clause 13.25.6)
	Forwarding        bool                   `protobuf:"varint,4,opt,name=forwarding,proto3" json:"forwarding,omitempty"`                                           // Whether port is currently forwarding frames
	PortPriority      uint32                 `protobuf:"varint,5,opt,name=port_priority,json=portPriority,proto3" json:"port_priority,omitempty"`                   // Admin or operational port priority
	PortPathCost      uint32                 `protobuf:"varint,6,opt,name=port_path_cost,json=portPathCost,proto3" json:"port_path_cost,omitempty"`                 // Port cost (Clause 13.24.2)
	DesignatedRoot    string                 `protobuf:"bytes,7,opt,name=designated_root,json=designatedRoot,proto3" json:"designated_root,omitempty"`              // Root bridge ID as reported in BPDU
	DesignatedBridge  string                 `protobuf:"bytes,8,opt,name=designated_bridge,json=designatedBridge,proto3" json:"designated_bridge,omitempty"`        // Designated bridge on the segment
	DesignatedPortId  string                 `protobuf:"bytes,9,opt,name=designated_port_id,json=designatedPortId,proto3" json:"designated_port_id,omitempty"`      // Port ID of the designated port
	TopologyChangeAck bool                   `protobuf:"varint,10,opt,name=topology_change_ack,json=topologyChangeAck,proto3" json:"topology_change_ack,omitempty"` // True if Topology Change ACK received
	TcPropagation     bool                   `protobuf:"varint,11,opt,name=tc_propagation,json=tcPropagation,proto3" json:"tc_propagation,omitempty"`               // Topology Change propagation flag
	ProposalReceived  bool                   `protobuf:"varint,12,opt,name=proposal_received,json=proposalReceived,proto3" json:"proposal_received,omitempty"`      // Indicates if RSTP proposal was received
	Agreement         bool                   `protobuf:"varint,13,opt,name=agreement,proto3" json:"agreement,omitempty"`                                            // Indicates RSTP handshake agreement status
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortStpStatus) Reset() {
	*x = PortStpStatus{}
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortStpStatus) ProtoMessage() {}

func (x *PortStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_stp_stp_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortStpStatus.ProtoReflect.Descriptor instead.
func (*PortStpStatus) Descriptor() ([]byte, []int) {
	return file_pkg_structures_stp_stp_status_proto_rawDescGZIP(), []int{3}
}

func (x *PortStpStatus) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortStpStatus) GetRole() PortRole {
	if x != nil {
		return x.Role
	}
	return PortRole_PORT_ROLE_UNSPECIFIED
}

func (x *PortStpStatus) GetState() PortState {
	if x != nil {
		return x.State
	}
	return PortState_PORT_STATE_UNSPECIFIED
}

func (x *PortStpStatus) GetForwarding() bool {
	if x != nil {
		return x.Forwarding
	}
	return false
}

func (x *PortStpStatus) GetPortPriority() uint32 {
	if x != nil {
		return x.PortPriority
	}
	return 0
}

func (x *PortStpStatus) GetPortPathCost() uint32 {
	if x != nil {
		return x.PortPathCost
	}
	return 0
}

func (x *PortStpStatus) GetDesignatedRoot() string {
	if x != nil {
		return x.DesignatedRoot
	}
	return ""
}

func (x *PortStpStatus) GetDesignatedBridge() string {
	if x != nil {
		return x.DesignatedBridge
	}
	return ""
}

func (x *PortStpStatus) GetDesignatedPortId() string {
	if x != nil {
		return x.DesignatedPortId
	}
	return ""
}

func (x *PortStpStatus) GetTopologyChangeAck() bool {
	if x != nil {
		return x.TopologyChangeAck
	}
	return false
}

func (x *PortStpStatus) GetTcPropagation() bool {
	if x != nil {
		return x.TcPropagation
	}
	return false
}

func (x *PortStpStatus) GetProposalReceived() bool {
	if x != nil {
		return x.ProposalReceived
	}
	return false
}

func (x *PortStpStatus) GetAgreement() bool {
	if x != nil {
		return x.Agreement
	}
	return false
}

var File_pkg_structures_stp_stp_status_proto protoreflect.FileDescriptor

const file_pkg_structures_stp_stp_status_proto_rawDesc = "" +
	"\n" +
	"#pkg/structures/stp/stp_status.proto\x12\n" +
	"stp_status\x1a\x1cpkg/structures/stp/stp.proto\"H\n" +
	"\x0fStpStatusReport\x125\n" +
	"\abridges\x18\x01 \x03(\v2\x1b.stp_status.BridgeStpStatusR\abridges\"\xf6\x01\n" +
	"\x0fBridgeStpStatus\x12\x1b\n" +
	"\tbridge_id\x18\x01 \x01(\tR\bbridgeId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12;\n" +
	"\tinstances\x18\x03 \x03(\v2\x1d.stp_status.StpInstanceStatusR\tinstances\x12\x1f\n" +
	"\vstp_enabled\x18\x04 \x01(\bR\n" +
	"stpEnabled\x12'\n" +
	"\x0fbridge_priority\x18\x05 \x01(\tR\x0ebridgePriority\x12&\n" +
	"\x0flast_updated_ns\x18\x06 \x01(\x04R\rlastUpdatedNs\"\xee\x01\n" +
	"\x11StpInstanceStatus\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eroot_bridge_id\x18\x02 \x01(\tR\frootBridgeId\x12$\n" +
	"\x0eroot_path_cost\x18\x03 \x01(\rR\frootPathCost\x120\n" +
	"\x14designated_bridge_id\x18\x04 \x01(\tR\x12designatedBridgeId\x12:\n" +
	"\vport_states\x18\x05 \x03(\v2\x19.stp_status.PortStpStatusR\n" +
	"portStates\"\x82\x04\n" +
	"\rPortStpStatus\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.stp.PortRoleR\x04role\x12$\n" +
	"\x05state\x18\x03 \x01(\x0e2\x0e.stp.PortStateR\x05state\x12\x1e\n" +
	"\n" +
	"forwarding\x18\x04 \x01(\bR\n" +
	"forwarding\x12#\n" +
	"\rport_priority\x18\x05 \x01(\rR\fportPriority\x12$\n" +
	"\x0eport_path_cost\x18\x06 \x01(\rR\fportPathCost\x12'\n" +
	"\x0fdesignated_root\x18\a \x01(\tR\x0edesignatedRoot\x12+\n" +
	"\x11designated_bridge\x18\b \x01(\tR\x10designatedBridge\x12,\n" +
	"\x12designated_port_id\x18\t \x01(\tR\x10designatedPortId\x12.\n" +
	"\x13topology_change_ack\x18\n" +
	" \x01(\bR\x11topologyChangeAck\x12%\n" +
	"\x0etc_propagation\x18\v \x01(\bR\rtcPropagation\x12+\n" +
	"\x11proposal_received\x18\f \x01(\bR\x10proposalReceived\x12\x1c\n" +
	"\tagreement\x18\r \x01(\bR\tagreementB/Z-OpenCNC_config_service/pkg/structures/stp;stpb\x06proto3"

var (
	file_pkg_structures_stp_stp_status_proto_rawDescOnce sync.Once
	file_pkg_structures_stp_stp_status_proto_rawDescData []byte
)

func file_pkg_structures_stp_stp_status_proto_rawDescGZIP() []byte {
	file_pkg_structures_stp_stp_status_proto_rawDescOnce.Do(func() {
		file_pkg_structures_stp_stp_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_stp_stp_status_proto_rawDesc), len(file_pkg_structures_stp_stp_status_proto_rawDesc)))
	})
	return file_pkg_structures_stp_stp_status_proto_rawDescData
}

var file_pkg_structures_stp_stp_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_structures_stp_stp_status_proto_goTypes = []any{
	(*StpStatusReport)(nil),   // 0: stp_status.StpStatusReport
	(*BridgeStpStatus)(nil),   // 1: stp_status.BridgeStpStatus
	(*StpInstanceStatus)(nil), // 2: stp_status.StpInstanceStatus
	(*PortStpStatus)(nil),     // 3: stp_status.PortStpStatus
	(PortRole)(0),             // 4: stp.PortRole
	(PortState)(0),            // 5: stp.PortState
}
var file_pkg_structures_stp_stp_status_proto_depIdxs = []int32{
	1, // 0: stp_status.StpStatusReport.bridges:type_name -> stp_status.BridgeStpStatus
	2, // 1: stp_status.BridgeStpStatus.instances:type_name -> stp_status.StpInstanceStatus
	3, // 2: stp_status.StpInstanceStatus.port_states:type_name -> stp_status.PortStpStatus
	4, // 3: stp_status.PortStpStatus.role:type_name -> stp.PortRole
	5, // 4: stp_status.PortStpStatus.state:type_name -> stp.PortState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_structures_stp_stp_status_proto_init() }
func file_pkg_structures_stp_stp_status_proto_init() {
	if File_pkg_structures_stp_stp_status_proto != nil {
		return
	}
	file_pkg_structures_stp_stp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_stp_stp_status_proto_rawDesc), len(file_pkg_structures_stp_stp_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_stp_stp_status_proto_goTypes,
		DependencyIndexes: file_pkg_structures_stp_stp_status_proto_depIdxs,
		MessageInfos:      file_pkg_structures_stp_stp_status_proto_msgTypes,
	}.Build()
	File_pkg_structures_stp_stp_status_proto = out.File
	file_pkg_structures_stp_stp_status_proto_goTypes = nil
	file_pkg_structures_stp_stp_status_proto_depIdxs = nil
}
