// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/uni/uni.proto

package uni

import (
	stream "OpenCNC/common/structures/stream"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserToNetworkRequirements struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NumSeamlessTrees uint32                 `protobuf:"varint,1,opt,name=NumSeamlessTrees,json=num-seamless-trees,proto3" json:"NumSeamlessTrees,omitempty"`
	MaxLatency       uint32                 `protobuf:"varint,2,opt,name=MaxLatency,json=max-latency,proto3" json:"MaxLatency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserToNetworkRequirements) Reset() {
	*x = UserToNetworkRequirements{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToNetworkRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToNetworkRequirements) ProtoMessage() {}

func (x *UserToNetworkRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToNetworkRequirements.ProtoReflect.Descriptor instead.
func (*UserToNetworkRequirements) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{0}
}

func (x *UserToNetworkRequirements) GetNumSeamlessTrees() uint32 {
	if x != nil {
		return x.NumSeamlessTrees
	}
	return 0
}

func (x *UserToNetworkRequirements) GetMaxLatency() uint32 {
	if x != nil {
		return x.MaxLatency
	}
	return 0
}

type InterfaceCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VlanTagCapable bool                   `protobuf:"varint,1,opt,name=VlanTagCapable,json=vlan-tag-capable,proto3" json:"VlanTagCapable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterfaceCapabilities) Reset() {
	*x = InterfaceCapabilities{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceCapabilities) ProtoMessage() {}

func (x *InterfaceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceCapabilities.ProtoReflect.Descriptor instead.
func (*InterfaceCapabilities) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceCapabilities) GetVlanTagCapable() bool {
	if x != nil {
		return x.VlanTagCapable
	}
	return false
}

type InterfaceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=MacAddress,json=mac-address,proto3" json:"MacAddress,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=InterfaceName,json=interface-name,proto3" json:"InterfaceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceId) Reset() {
	*x = InterfaceId{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceId) ProtoMessage() {}

func (x *InterfaceId) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceId.ProtoReflect.Descriptor instead.
func (*InterfaceId) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceId) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *InterfaceId) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	InterfaceId   *InterfaceId           `protobuf:"bytes,2,opt,name=InterfaceId,json=interface-id,proto3" json:"InterfaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{3}
}

func (x *Interface) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Interface) GetInterfaceId() *InterfaceId {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

type ListenerGroup struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	Index                uint32                     `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	StrId                *stream.StreamId           `protobuf:"bytes,2,opt,name=StrId,json=stream-id,proto3" json:"StrId,omitempty"`
	EndStationInterfaces []*Interface               `protobuf:"bytes,3,rep,name=EndStationInterfaces,json=end-station-interfaces,proto3" json:"EndStationInterfaces,omitempty"`
	UserToNetReq         *UserToNetworkRequirements `protobuf:"bytes,4,opt,name=UserToNetReq,json=user-to-network-requirements,proto3" json:"UserToNetReq,omitempty"`
	InterfCap            *InterfaceCapabilities     `protobuf:"bytes,5,opt,name=InterfCap,json=interface-capabilities,proto3" json:"InterfCap,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListenerGroup) Reset() {
	*x = ListenerGroup{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerGroup) ProtoMessage() {}

func (x *ListenerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerGroup.ProtoReflect.Descriptor instead.
func (*ListenerGroup) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{4}
}

func (x *ListenerGroup) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ListenerGroup) GetStrId() *stream.StreamId {
	if x != nil {
		return x.StrId
	}
	return nil
}

func (x *ListenerGroup) GetEndStationInterfaces() []*Interface {
	if x != nil {
		return x.EndStationInterfaces
	}
	return nil
}

func (x *ListenerGroup) GetUserToNetReq() *UserToNetworkRequirements {
	if x != nil {
		return x.UserToNetReq
	}
	return nil
}

func (x *ListenerGroup) GetInterfCap() *InterfaceCapabilities {
	if x != nil {
		return x.InterfCap
	}
	return nil
}

type StreamRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          uint32                 `protobuf:"varint,1,opt,name=Rank,json=rank,proto3" json:"Rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRank) Reset() {
	*x = StreamRank{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRank) ProtoMessage() {}

func (x *StreamRank) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRank.ProtoReflect.Descriptor instead.
func (*StreamRank) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{5}
}

func (x *StreamRank) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type IeeeMacAddress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DestinationMac string                 `protobuf:"bytes,1,opt,name=DestinationMac,json=destination-mac-address,proto3" json:"DestinationMac,omitempty"`
	SourceMac      string                 `protobuf:"bytes,2,opt,name=SourceMac,json=source-mac,proto3" json:"SourceMac,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IeeeMacAddress) Reset() {
	*x = IeeeMacAddress{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IeeeMacAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IeeeMacAddress) ProtoMessage() {}

func (x *IeeeMacAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IeeeMacAddress.ProtoReflect.Descriptor instead.
func (*IeeeMacAddress) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{6}
}

func (x *IeeeMacAddress) GetDestinationMac() string {
	if x != nil {
		return x.DestinationMac
	}
	return ""
}

func (x *IeeeMacAddress) GetSourceMac() string {
	if x != nil {
		return x.SourceMac
	}
	return ""
}

type IeeeVlanTag struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PriorityCodePoint uint32                 `protobuf:"varint,1,opt,name=PriorityCodePoint,json=priority-code-point,proto3" json:"PriorityCodePoint,omitempty"`
	VlanId            uint32                 `protobuf:"varint,2,opt,name=VlanId,json=vlan-id,proto3" json:"VlanId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IeeeVlanTag) Reset() {
	*x = IeeeVlanTag{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IeeeVlanTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IeeeVlanTag) ProtoMessage() {}

func (x *IeeeVlanTag) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IeeeVlanTag.ProtoReflect.Descriptor instead.
func (*IeeeVlanTag) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{7}
}

func (x *IeeeVlanTag) GetPriorityCodePoint() uint32 {
	if x != nil {
		return x.PriorityCodePoint
	}
	return 0
}

func (x *IeeeVlanTag) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

type Ipv4Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIpAddr     string                 `protobuf:"bytes,1,opt,name=SrcIpAddr,json=src-ip-addr,proto3" json:"SrcIpAddr,omitempty"`
	DestIpAddr    string                 `protobuf:"bytes,2,opt,name=DestIpAddr,json=dest-ip-addr,proto3" json:"DestIpAddr,omitempty"`
	Dscp          uint32                 `protobuf:"varint,3,opt,name=Dscp,json=dscp,proto3" json:"Dscp,omitempty"`
	Protocol      uint32                 `protobuf:"varint,4,opt,name=Protocol,json=protocol,proto3" json:"Protocol,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,5,opt,name=SrcPort,json=src-port,proto3" json:"SrcPort,omitempty"`
	DestPort      uint32                 `protobuf:"varint,6,opt,name=DestPort,json=dest-port,proto3" json:"DestPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ipv4Tuple) Reset() {
	*x = Ipv4Tuple{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ipv4Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv4Tuple) ProtoMessage() {}

func (x *Ipv4Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv4Tuple.ProtoReflect.Descriptor instead.
func (*Ipv4Tuple) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{8}
}

func (x *Ipv4Tuple) GetSrcIpAddr() string {
	if x != nil {
		return x.SrcIpAddr
	}
	return ""
}

func (x *Ipv4Tuple) GetDestIpAddr() string {
	if x != nil {
		return x.DestIpAddr
	}
	return ""
}

func (x *Ipv4Tuple) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

func (x *Ipv4Tuple) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Ipv4Tuple) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Ipv4Tuple) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

type Ipv6Tuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIpAddr     string                 `protobuf:"bytes,1,opt,name=SrcIpAddr,json=src-ip-addr,proto3" json:"SrcIpAddr,omitempty"`
	DestIpAddr    string                 `protobuf:"bytes,2,opt,name=DestIpAddr,json=dest-ip-addr,proto3" json:"DestIpAddr,omitempty"`
	Dscp          uint32                 `protobuf:"varint,3,opt,name=Dscp,json=dscp,proto3" json:"Dscp,omitempty"`
	Protocol      uint32                 `protobuf:"varint,4,opt,name=Protocol,json=protocol,proto3" json:"Protocol,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,5,opt,name=SrcPort,json=src-port,proto3" json:"SrcPort,omitempty"`
	DestPort      uint32                 `protobuf:"varint,6,opt,name=DestPort,json=dest-port,proto3" json:"DestPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ipv6Tuple) Reset() {
	*x = Ipv6Tuple{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ipv6Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6Tuple) ProtoMessage() {}

func (x *Ipv6Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6Tuple.ProtoReflect.Descriptor instead.
func (*Ipv6Tuple) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{9}
}

func (x *Ipv6Tuple) GetSrcIpAddr() string {
	if x != nil {
		return x.SrcIpAddr
	}
	return ""
}

func (x *Ipv6Tuple) GetDestIpAddr() string {
	if x != nil {
		return x.DestIpAddr
	}
	return ""
}

func (x *Ipv6Tuple) GetDscp() uint32 {
	if x != nil {
		return x.Dscp
	}
	return 0
}

func (x *Ipv6Tuple) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Ipv6Tuple) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Ipv6Tuple) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

type DataFrameSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	MacAddr       *IeeeMacAddress        `protobuf:"bytes,2,opt,name=MacAddr,json=ieee802-mac-addresses,proto3" json:"MacAddr,omitempty"`
	VlanTag       *IeeeVlanTag           `protobuf:"bytes,3,opt,name=VlanTag,json=ieee802-vlan-tag,proto3" json:"VlanTag,omitempty"`
	Ipv4Tup       *Ipv4Tuple             `protobuf:"bytes,4,opt,name=Ipv4Tup,json=ipv4tup,proto3" json:"Ipv4Tup,omitempty"`
	Ipv6Tup       *Ipv6Tuple             `protobuf:"bytes,5,opt,name=Ipv6Tup,json=ipv6tup,proto3" json:"Ipv6Tup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFrameSpecification) Reset() {
	*x = DataFrameSpecification{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFrameSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFrameSpecification) ProtoMessage() {}

func (x *DataFrameSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFrameSpecification.ProtoReflect.Descriptor instead.
func (*DataFrameSpecification) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{10}
}

func (x *DataFrameSpecification) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DataFrameSpecification) GetMacAddr() *IeeeMacAddress {
	if x != nil {
		return x.MacAddr
	}
	return nil
}

func (x *DataFrameSpecification) GetVlanTag() *IeeeVlanTag {
	if x != nil {
		return x.VlanTag
	}
	return nil
}

func (x *DataFrameSpecification) GetIpv4Tup() *Ipv4Tuple {
	if x != nil {
		return x.Ipv4Tup
	}
	return nil
}

func (x *DataFrameSpecification) GetIpv6Tup() *Ipv6Tuple {
	if x != nil {
		return x.Ipv6Tup
	}
	return nil
}

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numerator     uint32                 `protobuf:"varint,1,opt,name=Numerator,json=numerator,proto3" json:"Numerator,omitempty"`
	Denominator   uint32                 `protobuf:"varint,2,opt,name=Denominator,json=denominator,proto3" json:"Denominator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{11}
}

func (x *Interval) GetNumerator() uint32 {
	if x != nil {
		return x.Numerator
	}
	return 0
}

func (x *Interval) GetDenominator() uint32 {
	if x != nil {
		return x.Denominator
	}
	return 0
}

type TimeAware struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EarliestTransmitOffset uint32                 `protobuf:"varint,1,opt,name=EarliestTransmitOffset,json=earliest-transmit-offset,proto3" json:"EarliestTransmitOffset,omitempty"`
	LatestTransmitOffset   uint32                 `protobuf:"varint,2,opt,name=LatestTransmitOffset,json=latest-transmit-offset,proto3" json:"LatestTransmitOffset,omitempty"`
	Jitter                 uint32                 `protobuf:"varint,3,opt,name=Jitter,json=jitter,proto3" json:"Jitter,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TimeAware) Reset() {
	*x = TimeAware{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAware) ProtoMessage() {}

func (x *TimeAware) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAware.ProtoReflect.Descriptor instead.
func (*TimeAware) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{12}
}

func (x *TimeAware) GetEarliestTransmitOffset() uint32 {
	if x != nil {
		return x.EarliestTransmitOffset
	}
	return 0
}

func (x *TimeAware) GetLatestTransmitOffset() uint32 {
	if x != nil {
		return x.LatestTransmitOffset
	}
	return 0
}

func (x *TimeAware) GetJitter() uint32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

type TrafficSpecification struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Interval              *Interval              `protobuf:"bytes,1,opt,name=Interval,json=interval,proto3" json:"Interval,omitempty"`
	MaxFramesPerInterval  uint32                 `protobuf:"varint,2,opt,name=MaxFramesPerInterval,json=max-frames-per-interval,proto3" json:"MaxFramesPerInterval,omitempty"`
	MaxFrameSize          uint32                 `protobuf:"varint,3,opt,name=MaxFrameSize,json=max-frame-size,proto3" json:"MaxFrameSize,omitempty"`
	TransmissionSelection uint32                 `protobuf:"varint,4,opt,name=TransmissionSelection,json=transmission-selection,proto3" json:"TransmissionSelection,omitempty"`
	TimeAware             *TimeAware             `protobuf:"bytes,5,opt,name=TimeAware,json=time-aware,proto3" json:"TimeAware,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrafficSpecification) Reset() {
	*x = TrafficSpecification{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficSpecification) ProtoMessage() {}

func (x *TrafficSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficSpecification.ProtoReflect.Descriptor instead.
func (*TrafficSpecification) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{13}
}

func (x *TrafficSpecification) GetInterval() *Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *TrafficSpecification) GetMaxFramesPerInterval() uint32 {
	if x != nil {
		return x.MaxFramesPerInterval
	}
	return 0
}

func (x *TrafficSpecification) GetMaxFrameSize() uint32 {
	if x != nil {
		return x.MaxFrameSize
	}
	return 0
}

func (x *TrafficSpecification) GetTransmissionSelection() uint32 {
	if x != nil {
		return x.TransmissionSelection
	}
	return 0
}

func (x *TrafficSpecification) GetTimeAware() *TimeAware {
	if x != nil {
		return x.TimeAware
	}
	return nil
}

type TalkerGroup struct {
	state                  protoimpl.MessageState     `protogen:"open.v1"`
	StrId                  *stream.StreamId           `protobuf:"bytes,1,opt,name=StrId,json=stream-id,proto3" json:"StrId,omitempty"`
	StrRank                *StreamRank                `protobuf:"bytes,2,opt,name=StrRank,json=stream-rank,proto3" json:"StrRank,omitempty"`
	EndStationInterfaces   []*Interface               `protobuf:"bytes,3,rep,name=EndStationInterfaces,json=end-station-interfaces,proto3" json:"EndStationInterfaces,omitempty"`
	DataFrameSpecification []*DataFrameSpecification  `protobuf:"bytes,4,rep,name=DataFrameSpecification,json=data-frame-specification,proto3" json:"DataFrameSpecification,omitempty"`
	TrafficSpecification   *TrafficSpecification      `protobuf:"bytes,5,opt,name=TrafficSpecification,json=traffic-specification,proto3" json:"TrafficSpecification,omitempty"`
	UserToNetReq           *UserToNetworkRequirements `protobuf:"bytes,6,opt,name=UserToNetReq,json=user-to-network-requirements,proto3" json:"UserToNetReq,omitempty"`
	InterfCap              *InterfaceCapabilities     `protobuf:"bytes,7,opt,name=InterfCap,json=interface-capabilities,proto3" json:"InterfCap,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TalkerGroup) Reset() {
	*x = TalkerGroup{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkerGroup) ProtoMessage() {}

func (x *TalkerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkerGroup.ProtoReflect.Descriptor instead.
func (*TalkerGroup) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{14}
}

func (x *TalkerGroup) GetStrId() *stream.StreamId {
	if x != nil {
		return x.StrId
	}
	return nil
}

func (x *TalkerGroup) GetStrRank() *StreamRank {
	if x != nil {
		return x.StrRank
	}
	return nil
}

func (x *TalkerGroup) GetEndStationInterfaces() []*Interface {
	if x != nil {
		return x.EndStationInterfaces
	}
	return nil
}

func (x *TalkerGroup) GetDataFrameSpecification() []*DataFrameSpecification {
	if x != nil {
		return x.DataFrameSpecification
	}
	return nil
}

func (x *TalkerGroup) GetTrafficSpecification() *TrafficSpecification {
	if x != nil {
		return x.TrafficSpecification
	}
	return nil
}

func (x *TalkerGroup) GetUserToNetReq() *UserToNetworkRequirements {
	if x != nil {
		return x.UserToNetReq
	}
	return nil
}

func (x *TalkerGroup) GetInterfCap() *InterfaceCapabilities {
	if x != nil {
		return x.InterfCap
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Talker        *TalkerGroup           `protobuf:"bytes,1,opt,name=Talker,json=talker,proto3" json:"Talker,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=Id,json=request-id,proto3" json:"Id,omitempty"`
	ListenerList  []*ListenerGroup       `protobuf:"bytes,3,rep,name=ListenerList,json=listener-list,proto3" json:"ListenerList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{15}
}

func (x *Request) GetTalker() *TalkerGroup {
	if x != nil {
		return x.Talker
	}
	return nil
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetListenerList() []*ListenerGroup {
	if x != nil {
		return x.ListenerList
	}
	return nil
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       float32                `protobuf:"fixed32,1,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Requests      []*Request             `protobuf:"bytes,2,rep,name=Requests,json=requests,proto3" json:"Requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigRequest) GetVersion() float32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigRequest) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type StatusInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TalkerStatus   int32                  `protobuf:"varint,1,opt,name=TalkerStatus,json=talker-status,proto3" json:"TalkerStatus,omitempty"`       // TODO: update to enum: 0 = None, 1 = ready, 2 = failed
	ListenerStatus int32                  `protobuf:"varint,2,opt,name=ListenerStatus,json=listener-status,proto3" json:"ListenerStatus,omitempty"` // TODO: update to enum: 0 = None, 1 = ready, 2 = partial-failed, 3 = failed
	FailureCode    uint32                 `protobuf:"varint,3,opt,name=FailureCode,json=failure-code,proto3" json:"FailureCode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusInfo) Reset() {
	*x = StatusInfo{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusInfo) ProtoMessage() {}

func (x *StatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusInfo.ProtoReflect.Descriptor instead.
func (*StatusInfo) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{17}
}

func (x *StatusInfo) GetTalkerStatus() int32 {
	if x != nil {
		return x.TalkerStatus
	}
	return 0
}

func (x *StatusInfo) GetListenerStatus() int32 {
	if x != nil {
		return x.ListenerStatus
	}
	return 0
}

func (x *StatusInfo) GetFailureCode() uint32 {
	if x != nil {
		return x.FailureCode
	}
	return 0
}

type AccumulatedLatency struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccumulatedLatency uint32                 `protobuf:"varint,1,opt,name=AccumulatedLatency,json=accumulated-latency,proto3" json:"AccumulatedLatency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccumulatedLatency) Reset() {
	*x = AccumulatedLatency{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccumulatedLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccumulatedLatency) ProtoMessage() {}

func (x *AccumulatedLatency) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccumulatedLatency.ProtoReflect.Descriptor instead.
func (*AccumulatedLatency) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{18}
}

func (x *AccumulatedLatency) GetAccumulatedLatency() uint32 {
	if x != nil {
		return x.AccumulatedLatency
	}
	return 0
}

type TimeAwareOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=Offset,json=offset,proto3" json:"Offset,omitempty"` // ns, EarlisetTransmitOffset < offset < LatestTransmitOffset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeAwareOffset) Reset() {
	*x = TimeAwareOffset{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeAwareOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeAwareOffset) ProtoMessage() {}

func (x *TimeAwareOffset) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeAwareOffset.ProtoReflect.Descriptor instead.
func (*TimeAwareOffset) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{19}
}

func (x *TimeAwareOffset) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type InterfaceConfiguration struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	InterfaceId *InterfaceId           `protobuf:"bytes,1,opt,name=InterfaceId,json=interface-id,proto3" json:"InterfaceId,omitempty"`
	Type        int32                  `protobuf:"varint,2,opt,name=Type,json=type,proto3" json:"Type,omitempty"` // 1 = mac-address/vlan, 2 = ipv4, 3 = ipv6
	MacAddr     *IeeeMacAddress        `protobuf:"bytes,3,opt,name=MacAddr,json=mac-address,proto3" json:"MacAddr,omitempty"`
	VlanTag     *IeeeVlanTag           `protobuf:"bytes,4,opt,name=VlanTag,json=vlan-tag,proto3" json:"VlanTag,omitempty"`
	Ipv4Tup     *Ipv4Tuple             `protobuf:"bytes,5,opt,name=Ipv4Tup,json=ipv4-tuple,proto3" json:"Ipv4Tup,omitempty"`
	Ipv6Tup     *Ipv6Tuple             `protobuf:"bytes,6,opt,name=Ipv6Tup,json=ipv6-tuple,proto3" json:"Ipv6Tup,omitempty"`
	// provided if TimeAware is present in talker group
	TimeAwareOffset *TimeAwareOffset `protobuf:"bytes,7,opt,name=TimeAwareOffset,json=time-aware-offset,proto3" json:"TimeAwareOffset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterfaceConfiguration) Reset() {
	*x = InterfaceConfiguration{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceConfiguration) ProtoMessage() {}

func (x *InterfaceConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceConfiguration.ProtoReflect.Descriptor instead.
func (*InterfaceConfiguration) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{20}
}

func (x *InterfaceConfiguration) GetInterfaceId() *InterfaceId {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *InterfaceConfiguration) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InterfaceConfiguration) GetMacAddr() *IeeeMacAddress {
	if x != nil {
		return x.MacAddr
	}
	return nil
}

func (x *InterfaceConfiguration) GetVlanTag() *IeeeVlanTag {
	if x != nil {
		return x.VlanTag
	}
	return nil
}

func (x *InterfaceConfiguration) GetIpv4Tup() *Ipv4Tuple {
	if x != nil {
		return x.Ipv4Tup
	}
	return nil
}

func (x *InterfaceConfiguration) GetIpv6Tup() *Ipv6Tuple {
	if x != nil {
		return x.Ipv6Tup
	}
	return nil
}

func (x *InterfaceConfiguration) GetTimeAwareOffset() *TimeAwareOffset {
	if x != nil {
		return x.TimeAwareOffset
	}
	return nil
}

type TalkerListenerStatus struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	Index                  uint32                    `protobuf:"varint,1,opt,name=Index,json=index,proto3" json:"Index,omitempty"`
	AccumulatedLatency     *AccumulatedLatency       `protobuf:"bytes,2,opt,name=AccumulatedLatency,json=accumulated-latency,proto3" json:"AccumulatedLatency,omitempty"`
	InterfaceConfiguration []*InterfaceConfiguration `protobuf:"bytes,3,rep,name=InterfaceConfiguration,json=interface-configuration,proto3" json:"InterfaceConfiguration,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TalkerListenerStatus) Reset() {
	*x = TalkerListenerStatus{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkerListenerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkerListenerStatus) ProtoMessage() {}

func (x *TalkerListenerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkerListenerStatus.ProtoReflect.Descriptor instead.
func (*TalkerListenerStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{21}
}

func (x *TalkerListenerStatus) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TalkerListenerStatus) GetAccumulatedLatency() *AccumulatedLatency {
	if x != nil {
		return x.AccumulatedLatency
	}
	return nil
}

func (x *TalkerListenerStatus) GetInterfaceConfiguration() []*InterfaceConfiguration {
	if x != nil {
		return x.InterfaceConfiguration
	}
	return nil
}

type StatusGroup struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	StrId                *stream.StreamId        `protobuf:"bytes,1,opt,name=StrId,json=stream-id,proto3" json:"StrId,omitempty"`
	StatusInfo           *StatusInfo             `protobuf:"bytes,2,opt,name=StatusInfo,json=status-info,proto3" json:"StatusInfo,omitempty"`
	FailedInterfaces     []*InterfaceId          `protobuf:"bytes,3,rep,name=FailedInterfaces,json=failed-interfaces,proto3" json:"FailedInterfaces,omitempty"`
	StatusTalkerListener []*TalkerListenerStatus `protobuf:"bytes,4,rep,name=StatusTalkerListener,json=status-talker-listener,proto3" json:"StatusTalkerListener,omitempty"`
	EndStationInterfaces []*Interface            `protobuf:"bytes,5,rep,name=EndStationInterfaces,json=end-station-interfaces,proto3" json:"EndStationInterfaces,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusGroup) Reset() {
	*x = StatusGroup{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGroup) ProtoMessage() {}

func (x *StatusGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGroup.ProtoReflect.Descriptor instead.
func (*StatusGroup) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{22}
}

func (x *StatusGroup) GetStrId() *stream.StreamId {
	if x != nil {
		return x.StrId
	}
	return nil
}

func (x *StatusGroup) GetStatusInfo() *StatusInfo {
	if x != nil {
		return x.StatusInfo
	}
	return nil
}

func (x *StatusGroup) GetFailedInterfaces() []*InterfaceId {
	if x != nil {
		return x.FailedInterfaces
	}
	return nil
}

func (x *StatusGroup) GetStatusTalkerListener() []*TalkerListenerStatus {
	if x != nil {
		return x.StatusTalkerListener
	}
	return nil
}

func (x *StatusGroup) GetEndStationInterfaces() []*Interface {
	if x != nil {
		return x.EndStationInterfaces
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusGroup   *StatusGroup           `protobuf:"bytes,1,opt,name=StatusGroup,json=status-group,proto3" json:"StatusGroup,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=RequestId,json=request-id,proto3" json:"RequestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{23}
}

func (x *Response) GetStatusGroup() *StatusGroup {
	if x != nil {
		return x.StatusGroup
	}
	return nil
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       float32                `protobuf:"fixed32,1,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	Responses     []*Response            `protobuf:"bytes,2,rep,name=Responses,json=responses,proto3" json:"Responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_common_structures_uni_uni_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_uni_uni_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_common_structures_uni_uni_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigResponse) GetVersion() float32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_common_structures_uni_uni_proto protoreflect.FileDescriptor

const file_common_structures_uni_uni_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon/structures/uni/uni.proto\x12\x03uni\x1a%common/structures/stream/stream.proto\"j\n" +
	"\x19UserToNetworkRequirements\x12,\n" +
	"\x10NumSeamlessTrees\x18\x01 \x01(\rR\x12num-seamless-trees\x12\x1f\n" +
	"\n" +
	"MaxLatency\x18\x02 \x01(\rR\vmax-latency\"A\n" +
	"\x15InterfaceCapabilities\x12(\n" +
	"\x0eVlanTagCapable\x18\x01 \x01(\bR\x10vlan-tag-capable\"U\n" +
	"\vInterfaceId\x12\x1f\n" +
	"\n" +
	"MacAddress\x18\x01 \x01(\tR\vmac-address\x12%\n" +
	"\rInterfaceName\x18\x02 \x01(\tR\x0einterface-name\"V\n" +
	"\tInterface\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\x05R\x05index\x123\n" +
	"\vInterfaceId\x18\x02 \x01(\v2\x10.uni.InterfaceIdR\finterface-id\"\xb2\x02\n" +
	"\rListenerGroup\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05index\x12*\n" +
	"\x05StrId\x18\x02 \x01(\v2\x10.stream.StreamIdR\tstream-id\x12D\n" +
	"\x14EndStationInterfaces\x18\x03 \x03(\v2\x0e.uni.InterfaceR\x16end-station-interfaces\x12R\n" +
	"\fUserToNetReq\x18\x04 \x01(\v2\x1e.uni.UserToNetworkRequirementsR\x1cuser-to-network-requirements\x12E\n" +
	"\tInterfCap\x18\x05 \x01(\v2\x1a.uni.InterfaceCapabilitiesR\x16interface-capabilities\" \n" +
	"\n" +
	"StreamRank\x12\x12\n" +
	"\x04Rank\x18\x01 \x01(\rR\x04rank\"`\n" +
	"\x0eIeeeMacAddress\x12/\n" +
	"\x0eDestinationMac\x18\x01 \x01(\tR\x17destination-mac-address\x12\x1d\n" +
	"\tSourceMac\x18\x02 \x01(\tR\n" +
	"source-mac\"V\n" +
	"\vIeeeVlanTag\x12.\n" +
	"\x11PriorityCodePoint\x18\x01 \x01(\rR\x13priority-code-point\x12\x17\n" +
	"\x06VlanId\x18\x02 \x01(\rR\avlan-id\"\xb5\x01\n" +
	"\tIpv4Tuple\x12\x1e\n" +
	"\tSrcIpAddr\x18\x01 \x01(\tR\vsrc-ip-addr\x12 \n" +
	"\n" +
	"DestIpAddr\x18\x02 \x01(\tR\fdest-ip-addr\x12\x12\n" +
	"\x04Dscp\x18\x03 \x01(\rR\x04dscp\x12\x1a\n" +
	"\bProtocol\x18\x04 \x01(\rR\bprotocol\x12\x19\n" +
	"\aSrcPort\x18\x05 \x01(\rR\bsrc-port\x12\x1b\n" +
	"\bDestPort\x18\x06 \x01(\rR\tdest-port\"\xb5\x01\n" +
	"\tIpv6Tuple\x12\x1e\n" +
	"\tSrcIpAddr\x18\x01 \x01(\tR\vsrc-ip-addr\x12 \n" +
	"\n" +
	"DestIpAddr\x18\x02 \x01(\tR\fdest-ip-addr\x12\x12\n" +
	"\x04Dscp\x18\x03 \x01(\rR\x04dscp\x12\x1a\n" +
	"\bProtocol\x18\x04 \x01(\rR\bprotocol\x12\x19\n" +
	"\aSrcPort\x18\x05 \x01(\rR\bsrc-port\x12\x1b\n" +
	"\bDestPort\x18\x06 \x01(\rR\tdest-port\"\xf4\x01\n" +
	"\x16DataFrameSpecification\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05index\x12;\n" +
	"\aMacAddr\x18\x02 \x01(\v2\x13.uni.IeeeMacAddressR\x15ieee802-mac-addresses\x123\n" +
	"\aVlanTag\x18\x03 \x01(\v2\x10.uni.IeeeVlanTagR\x10ieee802-vlan-tag\x12(\n" +
	"\aIpv4Tup\x18\x04 \x01(\v2\x0e.uni.Ipv4TupleR\aipv4tup\x12(\n" +
	"\aIpv6Tup\x18\x05 \x01(\v2\x0e.uni.Ipv6TupleR\aipv6tup\"J\n" +
	"\bInterval\x12\x1c\n" +
	"\tNumerator\x18\x01 \x01(\rR\tnumerator\x12 \n" +
	"\vDenominator\x18\x02 \x01(\rR\vdenominator\"\x93\x01\n" +
	"\tTimeAware\x128\n" +
	"\x16EarliestTransmitOffset\x18\x01 \x01(\rR\x18earliest-transmit-offset\x124\n" +
	"\x14LatestTransmitOffset\x18\x02 \x01(\rR\x16latest-transmit-offset\x12\x16\n" +
	"\x06Jitter\x18\x03 \x01(\rR\x06jitter\"\x84\x02\n" +
	"\x14TrafficSpecification\x12)\n" +
	"\bInterval\x18\x01 \x01(\v2\r.uni.IntervalR\binterval\x125\n" +
	"\x14MaxFramesPerInterval\x18\x02 \x01(\rR\x17max-frames-per-interval\x12$\n" +
	"\fMaxFrameSize\x18\x03 \x01(\rR\x0emax-frame-size\x125\n" +
	"\x15TransmissionSelection\x18\x04 \x01(\rR\x16transmission-selection\x12-\n" +
	"\tTimeAware\x18\x05 \x01(\v2\x0e.uni.TimeAwareR\n" +
	"time-aware\"\xf0\x03\n" +
	"\vTalkerGroup\x12*\n" +
	"\x05StrId\x18\x01 \x01(\v2\x10.stream.StreamIdR\tstream-id\x12-\n" +
	"\aStrRank\x18\x02 \x01(\v2\x0f.uni.StreamRankR\vstream-rank\x12D\n" +
	"\x14EndStationInterfaces\x18\x03 \x03(\v2\x0e.uni.InterfaceR\x16end-station-interfaces\x12U\n" +
	"\x16DataFrameSpecification\x18\x04 \x03(\v2\x1b.uni.DataFrameSpecificationR\x18data-frame-specification\x12N\n" +
	"\x14TrafficSpecification\x18\x05 \x01(\v2\x19.uni.TrafficSpecificationR\x15traffic-specification\x12R\n" +
	"\fUserToNetReq\x18\x06 \x01(\v2\x1e.uni.UserToNetworkRequirementsR\x1cuser-to-network-requirements\x12E\n" +
	"\tInterfCap\x18\a \x01(\v2\x1a.uni.InterfaceCapabilitiesR\x16interface-capabilities\"\x84\x01\n" +
	"\aRequest\x12(\n" +
	"\x06Talker\x18\x01 \x01(\v2\x10.uni.TalkerGroupR\x06talker\x12\x16\n" +
	"\x02Id\x18\x02 \x01(\tR\n" +
	"request-id\x127\n" +
	"\fListenerList\x18\x03 \x03(\v2\x12.uni.ListenerGroupR\rlistener-list\"S\n" +
	"\rConfigRequest\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\x02R\aversion\x12(\n" +
	"\bRequests\x18\x02 \x03(\v2\f.uni.RequestR\brequests\"}\n" +
	"\n" +
	"StatusInfo\x12#\n" +
	"\fTalkerStatus\x18\x01 \x01(\x05R\rtalker-status\x12'\n" +
	"\x0eListenerStatus\x18\x02 \x01(\x05R\x0flistener-status\x12!\n" +
	"\vFailureCode\x18\x03 \x01(\rR\ffailure-code\"E\n" +
	"\x12AccumulatedLatency\x12/\n" +
	"\x12AccumulatedLatency\x18\x01 \x01(\rR\x13accumulated-latency\")\n" +
	"\x0fTimeAwareOffset\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\rR\x06offset\"\xdd\x02\n" +
	"\x16InterfaceConfiguration\x123\n" +
	"\vInterfaceId\x18\x01 \x01(\v2\x10.uni.InterfaceIdR\finterface-id\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04type\x121\n" +
	"\aMacAddr\x18\x03 \x01(\v2\x13.uni.IeeeMacAddressR\vmac-address\x12+\n" +
	"\aVlanTag\x18\x04 \x01(\v2\x10.uni.IeeeVlanTagR\bvlan-tag\x12+\n" +
	"\aIpv4Tup\x18\x05 \x01(\v2\x0e.uni.Ipv4TupleR\n" +
	"ipv4-tuple\x12+\n" +
	"\aIpv6Tup\x18\x06 \x01(\v2\x0e.uni.Ipv6TupleR\n" +
	"ipv6-tuple\x12@\n" +
	"\x0fTimeAwareOffset\x18\a \x01(\v2\x14.uni.TimeAwareOffsetR\x11time-aware-offset\"\xcc\x01\n" +
	"\x14TalkerListenerStatus\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05index\x12H\n" +
	"\x12AccumulatedLatency\x18\x02 \x01(\v2\x17.uni.AccumulatedLatencyR\x13accumulated-latency\x12T\n" +
	"\x16InterfaceConfiguration\x18\x03 \x03(\v2\x1b.uni.InterfaceConfigurationR\x17interface-configuration\"\xc1\x02\n" +
	"\vStatusGroup\x12*\n" +
	"\x05StrId\x18\x01 \x01(\v2\x10.stream.StreamIdR\tstream-id\x120\n" +
	"\n" +
	"StatusInfo\x18\x02 \x01(\v2\x0f.uni.StatusInfoR\vstatus-info\x12=\n" +
	"\x10FailedInterfaces\x18\x03 \x03(\v2\x10.uni.InterfaceIdR\x11failed-interfaces\x12O\n" +
	"\x14StatusTalkerListener\x18\x04 \x03(\v2\x19.uni.TalkerListenerStatusR\x16status-talker-listener\x12D\n" +
	"\x14EndStationInterfaces\x18\x05 \x03(\v2\x0e.uni.InterfaceR\x16end-station-interfaces\"^\n" +
	"\bResponse\x123\n" +
	"\vStatusGroup\x18\x01 \x01(\v2\x10.uni.StatusGroupR\fstatus-group\x12\x1d\n" +
	"\tRequestId\x18\x02 \x01(\tR\n" +
	"request-id\"W\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\x02R\aversion\x12+\n" +
	"\tResponses\x18\x02 \x03(\v2\r.uni.ResponseR\tresponsesB\x06Z\x04/unib\x06proto3"

var (
	file_common_structures_uni_uni_proto_rawDescOnce sync.Once
	file_common_structures_uni_uni_proto_rawDescData []byte
)

func file_common_structures_uni_uni_proto_rawDescGZIP() []byte {
	file_common_structures_uni_uni_proto_rawDescOnce.Do(func() {
		file_common_structures_uni_uni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_uni_uni_proto_rawDesc), len(file_common_structures_uni_uni_proto_rawDesc)))
	})
	return file_common_structures_uni_uni_proto_rawDescData
}

var file_common_structures_uni_uni_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_common_structures_uni_uni_proto_goTypes = []any{
	(*UserToNetworkRequirements)(nil), // 0: uni.UserToNetworkRequirements
	(*InterfaceCapabilities)(nil),     // 1: uni.InterfaceCapabilities
	(*InterfaceId)(nil),               // 2: uni.InterfaceId
	(*Interface)(nil),                 // 3: uni.Interface
	(*ListenerGroup)(nil),             // 4: uni.ListenerGroup
	(*StreamRank)(nil),                // 5: uni.StreamRank
	(*IeeeMacAddress)(nil),            // 6: uni.IeeeMacAddress
	(*IeeeVlanTag)(nil),               // 7: uni.IeeeVlanTag
	(*Ipv4Tuple)(nil),                 // 8: uni.Ipv4Tuple
	(*Ipv6Tuple)(nil),                 // 9: uni.Ipv6Tuple
	(*DataFrameSpecification)(nil),    // 10: uni.DataFrameSpecification
	(*Interval)(nil),                  // 11: uni.Interval
	(*TimeAware)(nil),                 // 12: uni.TimeAware
	(*TrafficSpecification)(nil),      // 13: uni.TrafficSpecification
	(*TalkerGroup)(nil),               // 14: uni.TalkerGroup
	(*Request)(nil),                   // 15: uni.Request
	(*ConfigRequest)(nil),             // 16: uni.ConfigRequest
	(*StatusInfo)(nil),                // 17: uni.StatusInfo
	(*AccumulatedLatency)(nil),        // 18: uni.AccumulatedLatency
	(*TimeAwareOffset)(nil),           // 19: uni.TimeAwareOffset
	(*InterfaceConfiguration)(nil),    // 20: uni.InterfaceConfiguration
	(*TalkerListenerStatus)(nil),      // 21: uni.TalkerListenerStatus
	(*StatusGroup)(nil),               // 22: uni.StatusGroup
	(*Response)(nil),                  // 23: uni.Response
	(*ConfigResponse)(nil),            // 24: uni.ConfigResponse
	(*stream.StreamId)(nil),           // 25: stream.StreamId
}
var file_common_structures_uni_uni_proto_depIdxs = []int32{
	2,  // 0: uni.Interface.InterfaceId:type_name -> uni.InterfaceId
	25, // 1: uni.ListenerGroup.StrId:type_name -> stream.StreamId
	3,  // 2: uni.ListenerGroup.EndStationInterfaces:type_name -> uni.Interface
	0,  // 3: uni.ListenerGroup.UserToNetReq:type_name -> uni.UserToNetworkRequirements
	1,  // 4: uni.ListenerGroup.InterfCap:type_name -> uni.InterfaceCapabilities
	6,  // 5: uni.DataFrameSpecification.MacAddr:type_name -> uni.IeeeMacAddress
	7,  // 6: uni.DataFrameSpecification.VlanTag:type_name -> uni.IeeeVlanTag
	8,  // 7: uni.DataFrameSpecification.Ipv4Tup:type_name -> uni.Ipv4Tuple
	9,  // 8: uni.DataFrameSpecification.Ipv6Tup:type_name -> uni.Ipv6Tuple
	11, // 9: uni.TrafficSpecification.Interval:type_name -> uni.Interval
	12, // 10: uni.TrafficSpecification.TimeAware:type_name -> uni.TimeAware
	25, // 11: uni.TalkerGroup.StrId:type_name -> stream.StreamId
	5,  // 12: uni.TalkerGroup.StrRank:type_name -> uni.StreamRank
	3,  // 13: uni.TalkerGroup.EndStationInterfaces:type_name -> uni.Interface
	10, // 14: uni.TalkerGroup.DataFrameSpecification:type_name -> uni.DataFrameSpecification
	13, // 15: uni.TalkerGroup.TrafficSpecification:type_name -> uni.TrafficSpecification
	0,  // 16: uni.TalkerGroup.UserToNetReq:type_name -> uni.UserToNetworkRequirements
	1,  // 17: uni.TalkerGroup.InterfCap:type_name -> uni.InterfaceCapabilities
	14, // 18: uni.Request.Talker:type_name -> uni.TalkerGroup
	4,  // 19: uni.Request.ListenerList:type_name -> uni.ListenerGroup
	15, // 20: uni.ConfigRequest.Requests:type_name -> uni.Request
	2,  // 21: uni.InterfaceConfiguration.InterfaceId:type_name -> uni.InterfaceId
	6,  // 22: uni.InterfaceConfiguration.MacAddr:type_name -> uni.IeeeMacAddress
	7,  // 23: uni.InterfaceConfiguration.VlanTag:type_name -> uni.IeeeVlanTag
	8,  // 24: uni.InterfaceConfiguration.Ipv4Tup:type_name -> uni.Ipv4Tuple
	9,  // 25: uni.InterfaceConfiguration.Ipv6Tup:type_name -> uni.Ipv6Tuple
	19, // 26: uni.InterfaceConfiguration.TimeAwareOffset:type_name -> uni.TimeAwareOffset
	18, // 27: uni.TalkerListenerStatus.AccumulatedLatency:type_name -> uni.AccumulatedLatency
	20, // 28: uni.TalkerListenerStatus.InterfaceConfiguration:type_name -> uni.InterfaceConfiguration
	25, // 29: uni.StatusGroup.StrId:type_name -> stream.StreamId
	17, // 30: uni.StatusGroup.StatusInfo:type_name -> uni.StatusInfo
	2,  // 31: uni.StatusGroup.FailedInterfaces:type_name -> uni.InterfaceId
	21, // 32: uni.StatusGroup.StatusTalkerListener:type_name -> uni.TalkerListenerStatus
	3,  // 33: uni.StatusGroup.EndStationInterfaces:type_name -> uni.Interface
	22, // 34: uni.Response.StatusGroup:type_name -> uni.StatusGroup
	23, // 35: uni.ConfigResponse.Responses:type_name -> uni.Response
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_common_structures_uni_uni_proto_init() }
func file_common_structures_uni_uni_proto_init() {
	if File_common_structures_uni_uni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_uni_uni_proto_rawDesc), len(file_common_structures_uni_uni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_uni_uni_proto_goTypes,
		DependencyIndexes: file_common_structures_uni_uni_proto_depIdxs,
		MessageInfos:      file_common_structures_uni_uni_proto_msgTypes,
	}.Build()
	File_common_structures_uni_uni_proto = out.File
	file_common_structures_uni_uni_proto_goTypes = nil
	file_common_structures_uni_uni_proto_depIdxs = nil
}
