// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/structures/topology_config/topology_config.proto

package topology_config

import (
	qav "OpenCNC_config_service/pkg/structures/qav"
	qbv "OpenCNC_config_service/pkg/structures/qbv"
	stp "OpenCNC_config_service/pkg/structures/stp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminState int32

const (
	AdminState_ADMIN_STATE_UNSPECIFIED AdminState = 0
	AdminState_ADMIN_STATE_ENABLED     AdminState = 1
	AdminState_ADMIN_STATE_DISABLED    AdminState = 2
)

// Enum value maps for AdminState.
var (
	AdminState_name = map[int32]string{
		0: "ADMIN_STATE_UNSPECIFIED",
		1: "ADMIN_STATE_ENABLED",
		2: "ADMIN_STATE_DISABLED",
	}
	AdminState_value = map[string]int32{
		"ADMIN_STATE_UNSPECIFIED": 0,
		"ADMIN_STATE_ENABLED":     1,
		"ADMIN_STATE_DISABLED":    2,
	}
)

func (x AdminState) Enum() *AdminState {
	p := new(AdminState)
	*p = x
	return p
}

func (x AdminState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_topology_config_topology_config_proto_enumTypes[0].Descriptor()
}

func (AdminState) Type() protoreflect.EnumType {
	return &file_pkg_structures_topology_config_topology_config_proto_enumTypes[0]
}

func (x AdminState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminState.Descriptor instead.
func (AdminState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{0}
}

type GptpRole int32

const (
	GptpRole_GPTP_ROLE_UNSPECIFIED GptpRole = 0
	GptpRole_GPTP_ROLE_MASTER      GptpRole = 1
	GptpRole_GPTP_ROLE_SLAVE       GptpRole = 2
	GptpRole_GPTP_ROLE_PASSIVE     GptpRole = 3
	GptpRole_GPTP_ROLE_DISABLED    GptpRole = 4
)

// Enum value maps for GptpRole.
var (
	GptpRole_name = map[int32]string{
		0: "GPTP_ROLE_UNSPECIFIED",
		1: "GPTP_ROLE_MASTER",
		2: "GPTP_ROLE_SLAVE",
		3: "GPTP_ROLE_PASSIVE",
		4: "GPTP_ROLE_DISABLED",
	}
	GptpRole_value = map[string]int32{
		"GPTP_ROLE_UNSPECIFIED": 0,
		"GPTP_ROLE_MASTER":      1,
		"GPTP_ROLE_SLAVE":       2,
		"GPTP_ROLE_PASSIVE":     3,
		"GPTP_ROLE_DISABLED":    4,
	}
)

func (x GptpRole) Enum() *GptpRole {
	p := new(GptpRole)
	*p = x
	return p
}

func (x GptpRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GptpRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_topology_config_topology_config_proto_enumTypes[1].Descriptor()
}

func (GptpRole) Type() protoreflect.EnumType {
	return &file_pkg_structures_topology_config_topology_config_proto_enumTypes[1]
}

func (x GptpRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GptpRole.Descriptor instead.
func (GptpRole) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{1}
}

type SchedulingModel int32

const (
	SchedulingModel_SCHEDULING_UNSPECIFIED    SchedulingModel = 0
	SchedulingModel_STRICT_PRIORITY           SchedulingModel = 1 // SP
	SchedulingModel_CREDIT_BASED_SHAPER       SchedulingModel = 2 // CBS
	SchedulingModel_TIME_AWARE_SCHEDULING     SchedulingModel = 3 // Qbv
	SchedulingModel_CYCLIC_QUEUING_FORWARDING SchedulingModel = 4 // CQF
)

// Enum value maps for SchedulingModel.
var (
	SchedulingModel_name = map[int32]string{
		0: "SCHEDULING_UNSPECIFIED",
		1: "STRICT_PRIORITY",
		2: "CREDIT_BASED_SHAPER",
		3: "TIME_AWARE_SCHEDULING",
		4: "CYCLIC_QUEUING_FORWARDING",
	}
	SchedulingModel_value = map[string]int32{
		"SCHEDULING_UNSPECIFIED":    0,
		"STRICT_PRIORITY":           1,
		"CREDIT_BASED_SHAPER":       2,
		"TIME_AWARE_SCHEDULING":     3,
		"CYCLIC_QUEUING_FORWARDING": 4,
	}
)

func (x SchedulingModel) Enum() *SchedulingModel {
	p := new(SchedulingModel)
	*p = x
	return p
}

func (x SchedulingModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulingModel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_topology_config_topology_config_proto_enumTypes[2].Descriptor()
}

func (SchedulingModel) Type() protoreflect.EnumType {
	return &file_pkg_structures_topology_config_topology_config_proto_enumTypes[2]
}

func (x SchedulingModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulingModel.Descriptor instead.
func (SchedulingModel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{2}
}

type LinkStateOverride int32

const (
	LinkStateOverride_UNDEFINED  LinkStateOverride = 0
	LinkStateOverride_FORCE_UP   LinkStateOverride = 1
	LinkStateOverride_FORCE_DOWN LinkStateOverride = 2
)

// Enum value maps for LinkStateOverride.
var (
	LinkStateOverride_name = map[int32]string{
		0: "UNDEFINED",
		1: "FORCE_UP",
		2: "FORCE_DOWN",
	}
	LinkStateOverride_value = map[string]int32{
		"UNDEFINED":  0,
		"FORCE_UP":   1,
		"FORCE_DOWN": 2,
	}
)

func (x LinkStateOverride) Enum() *LinkStateOverride {
	p := new(LinkStateOverride)
	*p = x
	return p
}

func (x LinkStateOverride) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkStateOverride) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_topology_config_topology_config_proto_enumTypes[3].Descriptor()
}

func (LinkStateOverride) Type() protoreflect.EnumType {
	return &file_pkg_structures_topology_config_topology_config_proto_enumTypes[3]
}

func (x LinkStateOverride) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkStateOverride.Descriptor instead.
func (LinkStateOverride) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{3}
}

type TopologyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeConfigs   []*NodeConfig          `protobuf:"bytes,1,rep,name=node_configs,json=nodeConfigs,proto3" json:"node_configs,omitempty"`
	LinkConfigs   []*LinkConfig          `protobuf:"bytes,2,rep,name=link_configs,json=linkConfigs,proto3" json:"link_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyConfig) Reset() {
	*x = TopologyConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyConfig) ProtoMessage() {}

func (x *TopologyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyConfig.ProtoReflect.Descriptor instead.
func (*TopologyConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{0}
}

func (x *TopologyConfig) GetNodeConfigs() []*NodeConfig {
	if x != nil {
		return x.NodeConfigs
	}
	return nil
}

func (x *TopologyConfig) GetLinkConfigs() []*LinkConfig {
	if x != nil {
		return x.LinkConfigs
	}
	return nil
}

//
// Per-node configuration matching Node.name in topology.proto
type NodeConfig struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ConfigId          string                   `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Bridge            *BridgeConfig            `protobuf:"bytes,2,opt,name=bridge,proto3,oneof" json:"bridge,omitempty"`
	EndStation        *EndStationConfig        `protobuf:"bytes,3,opt,name=end_station,json=endStation,proto3,oneof" json:"end_station,omitempty"`
	BridgedEndStation *BridgedEndStationConfig `protobuf:"bytes,4,opt,name=bridged_end_station,json=bridgedEndStation,proto3,oneof" json:"bridged_end_station,omitempty"`
	PortConfigs       []*PortConfig            `protobuf:"bytes,5,rep,name=port_configs,json=portConfigs,proto3" json:"port_configs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{1}
}

func (x *NodeConfig) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *NodeConfig) GetBridge() *BridgeConfig {
	if x != nil {
		return x.Bridge
	}
	return nil
}

func (x *NodeConfig) GetEndStation() *EndStationConfig {
	if x != nil {
		return x.EndStation
	}
	return nil
}

func (x *NodeConfig) GetBridgedEndStation() *BridgedEndStationConfig {
	if x != nil {
		return x.BridgedEndStation
	}
	return nil
}

func (x *NodeConfig) GetPortConfigs() []*PortConfig {
	if x != nil {
		return x.PortConfigs
	}
	return nil
}

type BridgeConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Stp                    *stp.StpConfiguration  `protobuf:"bytes,1,opt,name=stp,proto3,oneof" json:"stp,omitempty"`
	GptpEnabled            *bool                  `protobuf:"varint,2,opt,name=gptp_enabled,json=gptpEnabled,proto3,oneof" json:"gptp_enabled,omitempty"`
	FramePreemptionEnabled *bool                  `protobuf:"varint,3,opt,name=frame_preemption_enabled,json=framePreemptionEnabled,proto3,oneof" json:"frame_preemption_enabled,omitempty"`
	VlanConfig             *BridgeVlanConfig      `protobuf:"bytes,4,opt,name=vlan_config,json=vlanConfig,proto3,oneof" json:"vlan_config,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BridgeConfig) Reset() {
	*x = BridgeConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeConfig) ProtoMessage() {}

func (x *BridgeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeConfig.ProtoReflect.Descriptor instead.
func (*BridgeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{2}
}

func (x *BridgeConfig) GetStp() *stp.StpConfiguration {
	if x != nil {
		return x.Stp
	}
	return nil
}

func (x *BridgeConfig) GetGptpEnabled() bool {
	if x != nil && x.GptpEnabled != nil {
		return *x.GptpEnabled
	}
	return false
}

func (x *BridgeConfig) GetFramePreemptionEnabled() bool {
	if x != nil && x.FramePreemptionEnabled != nil {
		return *x.FramePreemptionEnabled
	}
	return false
}

func (x *BridgeConfig) GetVlanConfig() *BridgeVlanConfig {
	if x != nil {
		return x.VlanConfig
	}
	return nil
}

type BridgeVlanConfig struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	VlanRegistrationEntries []*VlanRegistrationEntry `protobuf:"bytes,1,rep,name=vlan_registration_entries,json=vlanRegistrationEntries,proto3" json:"vlan_registration_entries,omitempty"`
	VidToFidMappings        []*VidToFidMapping       `protobuf:"bytes,2,rep,name=vid_to_fid_mappings,json=vidToFidMappings,proto3" json:"vid_to_fid_mappings,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BridgeVlanConfig) Reset() {
	*x = BridgeVlanConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeVlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeVlanConfig) ProtoMessage() {}

func (x *BridgeVlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeVlanConfig.ProtoReflect.Descriptor instead.
func (*BridgeVlanConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{3}
}

func (x *BridgeVlanConfig) GetVlanRegistrationEntries() []*VlanRegistrationEntry {
	if x != nil {
		return x.VlanRegistrationEntries
	}
	return nil
}

func (x *BridgeVlanConfig) GetVidToFidMappings() []*VidToFidMapping {
	if x != nil {
		return x.VidToFidMappings
	}
	return nil
}

type VlanRegistrationEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    uint32                 `protobuf:"varint,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	VlanIds       []uint32               `protobuf:"varint,2,rep,packed,name=vlan_ids,json=vlanIds,proto3" json:"vlan_ids,omitempty"`
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"` // static or dynamic
	PortMaps      []*VlanPortMap         `protobuf:"bytes,4,rep,name=port_maps,json=portMaps,proto3" json:"port_maps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanRegistrationEntry) Reset() {
	*x = VlanRegistrationEntry{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanRegistrationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanRegistrationEntry) ProtoMessage() {}

func (x *VlanRegistrationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanRegistrationEntry.ProtoReflect.Descriptor instead.
func (*VlanRegistrationEntry) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{4}
}

func (x *VlanRegistrationEntry) GetDatabaseId() uint32 {
	if x != nil {
		return x.DatabaseId
	}
	return 0
}

func (x *VlanRegistrationEntry) GetVlanIds() []uint32 {
	if x != nil {
		return x.VlanIds
	}
	return nil
}

func (x *VlanRegistrationEntry) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VlanRegistrationEntry) GetPortMaps() []*VlanPortMap {
	if x != nil {
		return x.PortMaps
	}
	return nil
}

type VlanPortMap struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PortRef               uint32                 `protobuf:"varint,1,opt,name=port_ref,json=portRef,proto3" json:"port_ref,omitempty"`
	RegistrarAdminControl string                 `protobuf:"bytes,2,opt,name=registrar_admin_control,json=registrarAdminControl,proto3" json:"registrar_admin_control,omitempty"`
	VlanTransmitted       string                 `protobuf:"bytes,3,opt,name=vlan_transmitted,json=vlanTransmitted,proto3" json:"vlan_transmitted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VlanPortMap) Reset() {
	*x = VlanPortMap{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanPortMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanPortMap) ProtoMessage() {}

func (x *VlanPortMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanPortMap.ProtoReflect.Descriptor instead.
func (*VlanPortMap) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{5}
}

func (x *VlanPortMap) GetPortRef() uint32 {
	if x != nil {
		return x.PortRef
	}
	return 0
}

func (x *VlanPortMap) GetRegistrarAdminControl() string {
	if x != nil {
		return x.RegistrarAdminControl
	}
	return ""
}

func (x *VlanPortMap) GetVlanTransmitted() string {
	if x != nil {
		return x.VlanTransmitted
	}
	return ""
}

type VidToFidMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           uint32                 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Fid           uint32                 `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VidToFidMapping) Reset() {
	*x = VidToFidMapping{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VidToFidMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VidToFidMapping) ProtoMessage() {}

func (x *VidToFidMapping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VidToFidMapping.ProtoReflect.Descriptor instead.
func (*VidToFidMapping) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{6}
}

func (x *VidToFidMapping) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VidToFidMapping) GetFid() uint32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type EndStationConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParticipateInTimeSync *bool                  `protobuf:"varint,1,opt,name=participate_in_time_sync,json=participateInTimeSync,proto3,oneof" json:"participate_in_time_sync,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EndStationConfig) Reset() {
	*x = EndStationConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndStationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndStationConfig) ProtoMessage() {}

func (x *EndStationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndStationConfig.ProtoReflect.Descriptor instead.
func (*EndStationConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{7}
}

func (x *EndStationConfig) GetParticipateInTimeSync() bool {
	if x != nil && x.ParticipateInTimeSync != nil {
		return *x.ParticipateInTimeSync
	}
	return false
}

type BridgedEndStationConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ForwardingEnabled *bool                  `protobuf:"varint,1,opt,name=forwarding_enabled,json=forwardingEnabled,proto3,oneof" json:"forwarding_enabled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BridgedEndStationConfig) Reset() {
	*x = BridgedEndStationConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgedEndStationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgedEndStationConfig) ProtoMessage() {}

func (x *BridgedEndStationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgedEndStationConfig.ProtoReflect.Descriptor instead.
func (*BridgedEndStationConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{8}
}

func (x *BridgedEndStationConfig) GetForwardingEnabled() bool {
	if x != nil && x.ForwardingEnabled != nil {
		return *x.ForwardingEnabled
	}
	return false
}

type PortConfig struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	PortId            string                    `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	IsEdgePort        *bool                     `protobuf:"varint,2,opt,name=is_edge_port,json=isEdgePort,proto3,oneof" json:"is_edge_port,omitempty"`
	AdminState        *AdminState               `protobuf:"varint,3,opt,name=admin_state,json=adminState,proto3,enum=topology_config.AdminState,oneof" json:"admin_state,omitempty"`
	IngressEnabled    *bool                     `protobuf:"varint,4,opt,name=ingress_enabled,json=ingressEnabled,proto3,oneof" json:"ingress_enabled,omitempty"`
	EgressEnabled     *bool                     `protobuf:"varint,5,opt,name=egress_enabled,json=egressEnabled,proto3,oneof" json:"egress_enabled,omitempty"`
	DefaultPriority   *uint32                   `protobuf:"varint,6,opt,name=default_priority,json=defaultPriority,proto3,oneof" json:"default_priority,omitempty"`         // 0–7, used for untagged ingress frames
	PcpMappingEnabled *bool                     `protobuf:"varint,7,opt,name=pcp_mapping_enabled,json=pcpMappingEnabled,proto3,oneof" json:"pcp_mapping_enabled,omitempty"` // Enables PCP → internal priority mapping (8.6.6.1)
	TrafficClassTable []*TrafficClassTableEntry `protobuf:"bytes,8,rep,name=traffic_class_table,json=trafficClassTable,proto3" json:"traffic_class_table,omitempty"`
	DefaultVlanId     *uint32                   `protobuf:"varint,9,opt,name=default_vlan_id,json=defaultVlanId,proto3,oneof" json:"default_vlan_id,omitempty"`
	VlanMemberships   []*VlanMembership         `protobuf:"bytes,10,rep,name=vlan_memberships,json=vlanMemberships,proto3" json:"vlan_memberships,omitempty"`
	// New: Optional gPTP port role (if gPTP is enabled at node level)
	GptpRole      *GptpRole            `protobuf:"varint,11,opt,name=gptp_role,json=gptpRole,proto3,enum=topology_config.GptpRole,oneof" json:"gptp_role,omitempty"`
	StpEnabled    *bool                `protobuf:"varint,12,opt,name=stp_enabled,json=stpEnabled,proto3,oneof" json:"stp_enabled,omitempty"`
	Gcl           *qbv.GateControlList `protobuf:"bytes,13,opt,name=gcl,proto3,oneof" json:"gcl,omitempty"`
	QueueConfigs  []*QueueConfig       `protobuf:"bytes,14,rep,name=queue_configs,json=queueConfigs,proto3" json:"queue_configs,omitempty"`
	Description   string               `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortConfig) Reset() {
	*x = PortConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortConfig) ProtoMessage() {}

func (x *PortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortConfig.ProtoReflect.Descriptor instead.
func (*PortConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{9}
}

func (x *PortConfig) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortConfig) GetIsEdgePort() bool {
	if x != nil && x.IsEdgePort != nil {
		return *x.IsEdgePort
	}
	return false
}

func (x *PortConfig) GetAdminState() AdminState {
	if x != nil && x.AdminState != nil {
		return *x.AdminState
	}
	return AdminState_ADMIN_STATE_UNSPECIFIED
}

func (x *PortConfig) GetIngressEnabled() bool {
	if x != nil && x.IngressEnabled != nil {
		return *x.IngressEnabled
	}
	return false
}

func (x *PortConfig) GetEgressEnabled() bool {
	if x != nil && x.EgressEnabled != nil {
		return *x.EgressEnabled
	}
	return false
}

func (x *PortConfig) GetDefaultPriority() uint32 {
	if x != nil && x.DefaultPriority != nil {
		return *x.DefaultPriority
	}
	return 0
}

func (x *PortConfig) GetPcpMappingEnabled() bool {
	if x != nil && x.PcpMappingEnabled != nil {
		return *x.PcpMappingEnabled
	}
	return false
}

func (x *PortConfig) GetTrafficClassTable() []*TrafficClassTableEntry {
	if x != nil {
		return x.TrafficClassTable
	}
	return nil
}

func (x *PortConfig) GetDefaultVlanId() uint32 {
	if x != nil && x.DefaultVlanId != nil {
		return *x.DefaultVlanId
	}
	return 0
}

func (x *PortConfig) GetVlanMemberships() []*VlanMembership {
	if x != nil {
		return x.VlanMemberships
	}
	return nil
}

func (x *PortConfig) GetGptpRole() GptpRole {
	if x != nil && x.GptpRole != nil {
		return *x.GptpRole
	}
	return GptpRole_GPTP_ROLE_UNSPECIFIED
}

func (x *PortConfig) GetStpEnabled() bool {
	if x != nil && x.StpEnabled != nil {
		return *x.StpEnabled
	}
	return false
}

func (x *PortConfig) GetGcl() *qbv.GateControlList {
	if x != nil {
		return x.Gcl
	}
	return nil
}

func (x *PortConfig) GetQueueConfigs() []*QueueConfig {
	if x != nil {
		return x.QueueConfigs
	}
	return nil
}

func (x *PortConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type VlanMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlanId        uint32                 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	Tagged        bool                   `protobuf:"varint,2,opt,name=tagged,proto3" json:"tagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanMembership) Reset() {
	*x = VlanMembership{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanMembership) ProtoMessage() {}

func (x *VlanMembership) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanMembership.ProtoReflect.Descriptor instead.
func (*VlanMembership) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{10}
}

func (x *VlanMembership) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *VlanMembership) GetTagged() bool {
	if x != nil {
		return x.Tagged
	}
	return false
}

// IEEE 802.1Q Clause 8.6.6.1
// Per-port Priority to traffic class (=egress queue id) mapping
type TrafficClassTableEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pcp           uint32                 `protobuf:"varint,1,opt,name=pcp,proto3" json:"pcp,omitempty"`                                            // Priority Code Point (0–7)
	EgressQueueId uint32                 `protobuf:"varint,2,opt,name=egress_queue_id,json=egressQueueId,proto3" json:"egress_queue_id,omitempty"` // Traffic class index (0–7)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficClassTableEntry) Reset() {
	*x = TrafficClassTableEntry{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficClassTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficClassTableEntry) ProtoMessage() {}

func (x *TrafficClassTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficClassTableEntry.ProtoReflect.Descriptor instead.
func (*TrafficClassTableEntry) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{11}
}

func (x *TrafficClassTableEntry) GetPcp() uint32 {
	if x != nil {
		return x.Pcp
	}
	return 0
}

func (x *TrafficClassTableEntry) GetEgressQueueId() uint32 {
	if x != nil {
		return x.EgressQueueId
	}
	return 0
}

type QueueConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       uint32                 `protobuf:"varint,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	MaxFrameSize  uint32                 `protobuf:"varint,2,opt,name=max_frame_size,json=maxFrameSize,proto3" json:"max_frame_size,omitempty"`
	ShaperRateBps uint64                 `protobuf:"varint,3,opt,name=shaper_rate_bps,json=shaperRateBps,proto3" json:"shaper_rate_bps,omitempty"`
	Cbs           []*qav.CbsQueueConfig  `protobuf:"bytes,4,rep,name=cbs,proto3" json:"cbs,omitempty"`
	// New: Optional scheduling model (future extensibility)
	Scheduling    *SchedulingModel `protobuf:"varint,5,opt,name=scheduling,proto3,enum=topology_config.SchedulingModel,oneof" json:"scheduling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueConfig) Reset() {
	*x = QueueConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConfig) ProtoMessage() {}

func (x *QueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConfig.ProtoReflect.Descriptor instead.
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{12}
}

func (x *QueueConfig) GetQueueId() uint32 {
	if x != nil {
		return x.QueueId
	}
	return 0
}

func (x *QueueConfig) GetMaxFrameSize() uint32 {
	if x != nil {
		return x.MaxFrameSize
	}
	return 0
}

func (x *QueueConfig) GetShaperRateBps() uint64 {
	if x != nil {
		return x.ShaperRateBps
	}
	return 0
}

func (x *QueueConfig) GetCbs() []*qav.CbsQueueConfig {
	if x != nil {
		return x.Cbs
	}
	return nil
}

func (x *QueueConfig) GetScheduling() SchedulingModel {
	if x != nil && x.Scheduling != nil {
		return *x.Scheduling
	}
	return SchedulingModel_SCHEDULING_UNSPECIFIED
}

type LinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	StateOverride *LinkStateOverride     `protobuf:"varint,2,opt,name=state_override,json=stateOverride,proto3,enum=topology_config.LinkStateOverride,oneof" json:"state_override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkConfig) Reset() {
	*x = LinkConfig{}
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkConfig) ProtoMessage() {}

func (x *LinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_topology_config_topology_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkConfig.ProtoReflect.Descriptor instead.
func (*LinkConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP(), []int{13}
}

func (x *LinkConfig) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *LinkConfig) GetStateOverride() LinkStateOverride {
	if x != nil && x.StateOverride != nil {
		return *x.StateOverride
	}
	return LinkStateOverride_UNDEFINED
}

var File_pkg_structures_topology_config_topology_config_proto protoreflect.FileDescriptor

const file_pkg_structures_topology_config_topology_config_proto_rawDesc = "" +
	"\n" +
	"4pkg/structures/topology_config/topology_config.proto\x12\x0ftopology_config\x1a\x1cpkg/structures/qbv/qbv.proto\x1a\x1cpkg/structures/qav/qav.proto\x1a\x1cpkg/structures/stp/stp.proto\"\x90\x01\n" +
	"\x0eTopologyConfig\x12>\n" +
	"\fnode_configs\x18\x01 \x03(\v2\x1b.topology_config.NodeConfigR\vnodeConfigs\x12>\n" +
	"\flink_configs\x18\x02 \x03(\v2\x1b.topology_config.LinkConfigR\vlinkConfigs\"\x80\x03\n" +
	"\n" +
	"NodeConfig\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12:\n" +
	"\x06bridge\x18\x02 \x01(\v2\x1d.topology_config.BridgeConfigH\x00R\x06bridge\x88\x01\x01\x12G\n" +
	"\vend_station\x18\x03 \x01(\v2!.topology_config.EndStationConfigH\x01R\n" +
	"endStation\x88\x01\x01\x12]\n" +
	"\x13bridged_end_station\x18\x04 \x01(\v2(.topology_config.BridgedEndStationConfigH\x02R\x11bridgedEndStation\x88\x01\x01\x12>\n" +
	"\fport_configs\x18\x05 \x03(\v2\x1b.topology_config.PortConfigR\vportConfigsB\t\n" +
	"\a_bridgeB\x0e\n" +
	"\f_end_stationB\x16\n" +
	"\x14_bridged_end_station\"\xb2\x02\n" +
	"\fBridgeConfig\x12,\n" +
	"\x03stp\x18\x01 \x01(\v2\x15.stp.StpConfigurationH\x00R\x03stp\x88\x01\x01\x12&\n" +
	"\fgptp_enabled\x18\x02 \x01(\bH\x01R\vgptpEnabled\x88\x01\x01\x12=\n" +
	"\x18frame_preemption_enabled\x18\x03 \x01(\bH\x02R\x16framePreemptionEnabled\x88\x01\x01\x12G\n" +
	"\vvlan_config\x18\x04 \x01(\v2!.topology_config.BridgeVlanConfigH\x03R\n" +
	"vlanConfig\x88\x01\x01B\x06\n" +
	"\x04_stpB\x0f\n" +
	"\r_gptp_enabledB\x1b\n" +
	"\x19_frame_preemption_enabledB\x0e\n" +
	"\f_vlan_config\"\xc7\x01\n" +
	"\x10BridgeVlanConfig\x12b\n" +
	"\x19vlan_registration_entries\x18\x01 \x03(\v2&.topology_config.VlanRegistrationEntryR\x17vlanRegistrationEntries\x12O\n" +
	"\x13vid_to_fid_mappings\x18\x02 \x03(\v2 .topology_config.VidToFidMappingR\x10vidToFidMappings\"\xad\x01\n" +
	"\x15VlanRegistrationEntry\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\rR\n" +
	"databaseId\x12\x19\n" +
	"\bvlan_ids\x18\x02 \x03(\rR\avlanIds\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x129\n" +
	"\tport_maps\x18\x04 \x03(\v2\x1c.topology_config.VlanPortMapR\bportMaps\"\x8b\x01\n" +
	"\vVlanPortMap\x12\x19\n" +
	"\bport_ref\x18\x01 \x01(\rR\aportRef\x126\n" +
	"\x17registrar_admin_control\x18\x02 \x01(\tR\x15registrarAdminControl\x12)\n" +
	"\x10vlan_transmitted\x18\x03 \x01(\tR\x0fvlanTransmitted\"5\n" +
	"\x0fVidToFidMapping\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\rR\x03vid\x12\x10\n" +
	"\x03fid\x18\x02 \x01(\rR\x03fid\"m\n" +
	"\x10EndStationConfig\x12<\n" +
	"\x18participate_in_time_sync\x18\x01 \x01(\bH\x00R\x15participateInTimeSync\x88\x01\x01B\x1b\n" +
	"\x19_participate_in_time_sync\"d\n" +
	"\x17BridgedEndStationConfig\x122\n" +
	"\x12forwarding_enabled\x18\x01 \x01(\bH\x00R\x11forwardingEnabled\x88\x01\x01B\x15\n" +
	"\x13_forwarding_enabled\"\xc4\a\n" +
	"\n" +
	"PortConfig\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12%\n" +
	"\fis_edge_port\x18\x02 \x01(\bH\x00R\n" +
	"isEdgePort\x88\x01\x01\x12A\n" +
	"\vadmin_state\x18\x03 \x01(\x0e2\x1b.topology_config.AdminStateH\x01R\n" +
	"adminState\x88\x01\x01\x12,\n" +
	"\x0fingress_enabled\x18\x04 \x01(\bH\x02R\x0eingressEnabled\x88\x01\x01\x12*\n" +
	"\x0eegress_enabled\x18\x05 \x01(\bH\x03R\regressEnabled\x88\x01\x01\x12.\n" +
	"\x10default_priority\x18\x06 \x01(\rH\x04R\x0fdefaultPriority\x88\x01\x01\x123\n" +
	"\x13pcp_mapping_enabled\x18\a \x01(\bH\x05R\x11pcpMappingEnabled\x88\x01\x01\x12W\n" +
	"\x13traffic_class_table\x18\b \x03(\v2'.topology_config.TrafficClassTableEntryR\x11trafficClassTable\x12+\n" +
	"\x0fdefault_vlan_id\x18\t \x01(\rH\x06R\rdefaultVlanId\x88\x01\x01\x12J\n" +
	"\x10vlan_memberships\x18\n" +
	" \x03(\v2\x1f.topology_config.VlanMembershipR\x0fvlanMemberships\x12;\n" +
	"\tgptp_role\x18\v \x01(\x0e2\x19.topology_config.GptpRoleH\aR\bgptpRole\x88\x01\x01\x12$\n" +
	"\vstp_enabled\x18\f \x01(\bH\bR\n" +
	"stpEnabled\x88\x01\x01\x12+\n" +
	"\x03gcl\x18\r \x01(\v2\x14.qbv.GateControlListH\tR\x03gcl\x88\x01\x01\x12A\n" +
	"\rqueue_configs\x18\x0e \x03(\v2\x1c.topology_config.QueueConfigR\fqueueConfigs\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescriptionB\x0f\n" +
	"\r_is_edge_portB\x0e\n" +
	"\f_admin_stateB\x12\n" +
	"\x10_ingress_enabledB\x11\n" +
	"\x0f_egress_enabledB\x13\n" +
	"\x11_default_priorityB\x16\n" +
	"\x14_pcp_mapping_enabledB\x12\n" +
	"\x10_default_vlan_idB\f\n" +
	"\n" +
	"_gptp_roleB\x0e\n" +
	"\f_stp_enabledB\x06\n" +
	"\x04_gcl\"A\n" +
	"\x0eVlanMembership\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12\x16\n" +
	"\x06tagged\x18\x02 \x01(\bR\x06tagged\"R\n" +
	"\x16TrafficClassTableEntry\x12\x10\n" +
	"\x03pcp\x18\x01 \x01(\rR\x03pcp\x12&\n" +
	"\x0fegress_queue_id\x18\x02 \x01(\rR\regressQueueId\"\xf3\x01\n" +
	"\vQueueConfig\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\rR\aqueueId\x12$\n" +
	"\x0emax_frame_size\x18\x02 \x01(\rR\fmaxFrameSize\x12&\n" +
	"\x0fshaper_rate_bps\x18\x03 \x01(\x04R\rshaperRateBps\x12%\n" +
	"\x03cbs\x18\x04 \x03(\v2\x13.qav.CbsQueueConfigR\x03cbs\x12E\n" +
	"\n" +
	"scheduling\x18\x05 \x01(\x0e2 .topology_config.SchedulingModelH\x00R\n" +
	"scheduling\x88\x01\x01B\r\n" +
	"\v_scheduling\"\x88\x01\n" +
	"\n" +
	"LinkConfig\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12N\n" +
	"\x0estate_override\x18\x02 \x01(\x0e2\".topology_config.LinkStateOverrideH\x00R\rstateOverride\x88\x01\x01B\x11\n" +
	"\x0f_state_override*\\\n" +
	"\n" +
	"AdminState\x12\x1b\n" +
	"\x17ADMIN_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ADMIN_STATE_ENABLED\x10\x01\x12\x18\n" +
	"\x14ADMIN_STATE_DISABLED\x10\x02*\x7f\n" +
	"\bGptpRole\x12\x19\n" +
	"\x15GPTP_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GPTP_ROLE_MASTER\x10\x01\x12\x13\n" +
	"\x0fGPTP_ROLE_SLAVE\x10\x02\x12\x15\n" +
	"\x11GPTP_ROLE_PASSIVE\x10\x03\x12\x16\n" +
	"\x12GPTP_ROLE_DISABLED\x10\x04*\x95\x01\n" +
	"\x0fSchedulingModel\x12\x1a\n" +
	"\x16SCHEDULING_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTRICT_PRIORITY\x10\x01\x12\x17\n" +
	"\x13CREDIT_BASED_SHAPER\x10\x02\x12\x19\n" +
	"\x15TIME_AWARE_SCHEDULING\x10\x03\x12\x1d\n" +
	"\x19CYCLIC_QUEUING_FORWARDING\x10\x04*@\n" +
	"\x11LinkStateOverride\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\f\n" +
	"\bFORCE_UP\x10\x01\x12\x0e\n" +
	"\n" +
	"FORCE_DOWN\x10\x02B\x12Z\x10/topology_configb\x06proto3"

var (
	file_pkg_structures_topology_config_topology_config_proto_rawDescOnce sync.Once
	file_pkg_structures_topology_config_topology_config_proto_rawDescData []byte
)

func file_pkg_structures_topology_config_topology_config_proto_rawDescGZIP() []byte {
	file_pkg_structures_topology_config_topology_config_proto_rawDescOnce.Do(func() {
		file_pkg_structures_topology_config_topology_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_topology_config_topology_config_proto_rawDesc), len(file_pkg_structures_topology_config_topology_config_proto_rawDesc)))
	})
	return file_pkg_structures_topology_config_topology_config_proto_rawDescData
}

var file_pkg_structures_topology_config_topology_config_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_structures_topology_config_topology_config_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_structures_topology_config_topology_config_proto_goTypes = []any{
	(AdminState)(0),                 // 0: topology_config.AdminState
	(GptpRole)(0),                   // 1: topology_config.GptpRole
	(SchedulingModel)(0),            // 2: topology_config.SchedulingModel
	(LinkStateOverride)(0),          // 3: topology_config.LinkStateOverride
	(*TopologyConfig)(nil),          // 4: topology_config.TopologyConfig
	(*NodeConfig)(nil),              // 5: topology_config.NodeConfig
	(*BridgeConfig)(nil),            // 6: topology_config.BridgeConfig
	(*BridgeVlanConfig)(nil),        // 7: topology_config.BridgeVlanConfig
	(*VlanRegistrationEntry)(nil),   // 8: topology_config.VlanRegistrationEntry
	(*VlanPortMap)(nil),             // 9: topology_config.VlanPortMap
	(*VidToFidMapping)(nil),         // 10: topology_config.VidToFidMapping
	(*EndStationConfig)(nil),        // 11: topology_config.EndStationConfig
	(*BridgedEndStationConfig)(nil), // 12: topology_config.BridgedEndStationConfig
	(*PortConfig)(nil),              // 13: topology_config.PortConfig
	(*VlanMembership)(nil),          // 14: topology_config.VlanMembership
	(*TrafficClassTableEntry)(nil),  // 15: topology_config.TrafficClassTableEntry
	(*QueueConfig)(nil),             // 16: topology_config.QueueConfig
	(*LinkConfig)(nil),              // 17: topology_config.LinkConfig
	(*stp.StpConfiguration)(nil),    // 18: stp.StpConfiguration
	(*qbv.GateControlList)(nil),     // 19: qbv.GateControlList
	(*qav.CbsQueueConfig)(nil),      // 20: qav.CbsQueueConfig
}
var file_pkg_structures_topology_config_topology_config_proto_depIdxs = []int32{
	5,  // 0: topology_config.TopologyConfig.node_configs:type_name -> topology_config.NodeConfig
	17, // 1: topology_config.TopologyConfig.link_configs:type_name -> topology_config.LinkConfig
	6,  // 2: topology_config.NodeConfig.bridge:type_name -> topology_config.BridgeConfig
	11, // 3: topology_config.NodeConfig.end_station:type_name -> topology_config.EndStationConfig
	12, // 4: topology_config.NodeConfig.bridged_end_station:type_name -> topology_config.BridgedEndStationConfig
	13, // 5: topology_config.NodeConfig.port_configs:type_name -> topology_config.PortConfig
	18, // 6: topology_config.BridgeConfig.stp:type_name -> stp.StpConfiguration
	7,  // 7: topology_config.BridgeConfig.vlan_config:type_name -> topology_config.BridgeVlanConfig
	8,  // 8: topology_config.BridgeVlanConfig.vlan_registration_entries:type_name -> topology_config.VlanRegistrationEntry
	10, // 9: topology_config.BridgeVlanConfig.vid_to_fid_mappings:type_name -> topology_config.VidToFidMapping
	9,  // 10: topology_config.VlanRegistrationEntry.port_maps:type_name -> topology_config.VlanPortMap
	0,  // 11: topology_config.PortConfig.admin_state:type_name -> topology_config.AdminState
	15, // 12: topology_config.PortConfig.traffic_class_table:type_name -> topology_config.TrafficClassTableEntry
	14, // 13: topology_config.PortConfig.vlan_memberships:type_name -> topology_config.VlanMembership
	1,  // 14: topology_config.PortConfig.gptp_role:type_name -> topology_config.GptpRole
	19, // 15: topology_config.PortConfig.gcl:type_name -> qbv.GateControlList
	16, // 16: topology_config.PortConfig.queue_configs:type_name -> topology_config.QueueConfig
	20, // 17: topology_config.QueueConfig.cbs:type_name -> qav.CbsQueueConfig
	2,  // 18: topology_config.QueueConfig.scheduling:type_name -> topology_config.SchedulingModel
	3,  // 19: topology_config.LinkConfig.state_override:type_name -> topology_config.LinkStateOverride
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_structures_topology_config_topology_config_proto_init() }
func file_pkg_structures_topology_config_topology_config_proto_init() {
	if File_pkg_structures_topology_config_topology_config_proto != nil {
		return
	}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[8].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_structures_topology_config_topology_config_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_topology_config_topology_config_proto_rawDesc), len(file_pkg_structures_topology_config_topology_config_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_topology_config_topology_config_proto_goTypes,
		DependencyIndexes: file_pkg_structures_topology_config_topology_config_proto_depIdxs,
		EnumInfos:         file_pkg_structures_topology_config_topology_config_proto_enumTypes,
		MessageInfos:      file_pkg_structures_topology_config_topology_config_proto_msgTypes,
	}.Build()
	File_pkg_structures_topology_config_topology_config_proto = out.File
	file_pkg_structures_topology_config_topology_config_proto_goTypes = nil
	file_pkg_structures_topology_config_topology_config_proto_depIdxs = nil
}
