// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/stp/stp_status.proto

package stp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// Runtime STP status for one or more bridges.
//
// This message is useful for STP-specific telemetry or APIs.
//
// topology_status.proto may instead embed the individual
// BridgeStpStatus and PortStpStatus objects into the topology status model.
type StpStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridges       []*BridgeStpStatus     `protobuf:"bytes,1,rep,name=bridges,proto3" json:"bridges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StpStatusReport) Reset() {
	*x = StpStatusReport{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpStatusReport) ProtoMessage() {}

func (x *StpStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpStatusReport.ProtoReflect.Descriptor instead.
func (*StpStatusReport) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{0}
}

func (x *StpStatusReport) GetBridges() []*BridgeStpStatus {
	if x != nil {
		return x.Bridges
	}
	return nil
}

//
// Operational STP status for one bridge.
//
// This message contains bridge/node-level STP state only.
//
// Port-specific state belongs exclusively to PortStpStatus.
type BridgeStpStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// OpenCNC topology node identifier.
	//
	// Matches Node.name in topology.proto.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	//
	// Protocol mode currently operating on the bridge.
	ProtocolMode StpProtocolMode `protobuf:"varint,3,opt,name=protocol_mode,json=protocolMode,proto3,enum=stp.StpProtocolMode" json:"protocol_mode,omitempty"`
	//
	// Operational state of the CIST and MSTIs.
	//
	// These are instance-level values only.
	//
	// Port-specific values are not stored here.
	Instances []*StpInstanceStatus `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	//
	// Whether STP is currently operationally enabled.
	StpEnabled bool `protobuf:"varint,5,opt,name=stp_enabled,json=stpEnabled,proto3" json:"stp_enabled,omitempty"`
	//
	// Current operational bridge priority.
	BridgePriority uint32 `protobuf:"varint,6,opt,name=bridge_priority,json=bridgePriority,proto3" json:"bridge_priority,omitempty"`
	//
	// Timestamp of this status sample.
	//
	// Nanoseconds since Unix epoch.
	LastUpdatedNs uint64 `protobuf:"varint,7,opt,name=last_updated_ns,json=lastUpdatedNs,proto3" json:"last_updated_ns,omitempty"`
	//
	// Operational MST configuration.
	//
	// Present when MSTP is active.
	MstConfiguration *MstConfigurationStatus `protobuf:"bytes,8,opt,name=mst_configuration,json=mstConfiguration,proto3,oneof" json:"mst_configuration,omitempty"`
	//
	// Whether the bridge is currently operating as part of an MST region.
	MstRegionActive bool `protobuf:"varint,9,opt,name=mst_region_active,json=mstRegionActive,proto3" json:"mst_region_active,omitempty"`
	//
	// Number of topology changes observed by the bridge.
	TopologyChangeCount uint64 `protobuf:"varint,10,opt,name=topology_change_count,json=topologyChangeCount,proto3" json:"topology_change_count,omitempty"`
	//
	// Timestamp of the most recent bridge-level topology change.
	//
	// Nanoseconds since Unix epoch.
	LastTopologyChangeNs uint64 `protobuf:"varint,11,opt,name=last_topology_change_ns,json=lastTopologyChangeNs,proto3" json:"last_topology_change_ns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BridgeStpStatus) Reset() {
	*x = BridgeStpStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeStpStatus) ProtoMessage() {}

func (x *BridgeStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeStpStatus.ProtoReflect.Descriptor instead.
func (*BridgeStpStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{1}
}

func (x *BridgeStpStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BridgeStpStatus) GetProtocolMode() StpProtocolMode {
	if x != nil {
		return x.ProtocolMode
	}
	return StpProtocolMode_STP_PROTOCOL_UNSPECIFIED
}

func (x *BridgeStpStatus) GetInstances() []*StpInstanceStatus {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *BridgeStpStatus) GetStpEnabled() bool {
	if x != nil {
		return x.StpEnabled
	}
	return false
}

func (x *BridgeStpStatus) GetBridgePriority() uint32 {
	if x != nil {
		return x.BridgePriority
	}
	return 0
}

func (x *BridgeStpStatus) GetLastUpdatedNs() uint64 {
	if x != nil {
		return x.LastUpdatedNs
	}
	return 0
}

func (x *BridgeStpStatus) GetMstConfiguration() *MstConfigurationStatus {
	if x != nil {
		return x.MstConfiguration
	}
	return nil
}

func (x *BridgeStpStatus) GetMstRegionActive() bool {
	if x != nil {
		return x.MstRegionActive
	}
	return false
}

func (x *BridgeStpStatus) GetTopologyChangeCount() uint64 {
	if x != nil {
		return x.TopologyChangeCount
	}
	return 0
}

func (x *BridgeStpStatus) GetLastTopologyChangeNs() uint64 {
	if x != nil {
		return x.LastTopologyChangeNs
	}
	return 0
}

//
// Operational status of one spanning-tree instance.
//
// This message contains INSTANCE-LEVEL state only.
//
// It does not contain any per-port state.
//
// msti_id:
//
//   0       = CIST
//   1..4094 = MSTI
type StpInstanceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Canonical spanning-tree instance identifier.
	//
	// 0 = CIST.
	// 1..4094 = MSTI.
	MstiId uint32 `protobuf:"varint,1,opt,name=msti_id,json=mstiId,proto3" json:"msti_id,omitempty"`
	//
	// Human-readable instance identifier.
	//
	// Examples:
	//
	//   "cist"
	//   "mst1"
	//   "mst2"
	//
	// The numeric msti_id is authoritative.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	//
	// Operational IEEE Bridge Identifier of the current root bridge
	// for this instance.
	RootBridgeId string `protobuf:"bytes,3,opt,name=root_bridge_id,json=rootBridgeId,proto3" json:"root_bridge_id,omitempty"`
	//
	// Operational path cost from this bridge to the root bridge.
	RootPathCost uint32 `protobuf:"varint,4,opt,name=root_path_cost,json=rootPathCost,proto3" json:"root_path_cost,omitempty"`
	//
	// Operational designated bridge identifier for the relevant
	// spanning-tree instance context.
	DesignatedBridgeId string `protobuf:"bytes,5,opt,name=designated_bridge_id,json=designatedBridgeId,proto3" json:"designated_bridge_id,omitempty"`
	//
	// Whether this bridge is currently the root bridge for this instance.
	IsRootBridge bool `protobuf:"varint,6,opt,name=is_root_bridge,json=isRootBridge,proto3" json:"is_root_bridge,omitempty"`
	//
	// Current operational bridge priority for this instance.
	BridgePriority uint32 `protobuf:"varint,7,opt,name=bridge_priority,json=bridgePriority,proto3" json:"bridge_priority,omitempty"`
	//
	// Number of topology changes observed for this instance.
	TopologyChangeCount uint64 `protobuf:"varint,8,opt,name=topology_change_count,json=topologyChangeCount,proto3" json:"topology_change_count,omitempty"`
	//
	// Timestamp of the most recent topology change for this instance.
	//
	// Nanoseconds since Unix epoch.
	LastTopologyChangeNs uint64 `protobuf:"varint,9,opt,name=last_topology_change_ns,json=lastTopologyChangeNs,proto3" json:"last_topology_change_ns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StpInstanceStatus) Reset() {
	*x = StpInstanceStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StpInstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StpInstanceStatus) ProtoMessage() {}

func (x *StpInstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StpInstanceStatus.ProtoReflect.Descriptor instead.
func (*StpInstanceStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{2}
}

func (x *StpInstanceStatus) GetMstiId() uint32 {
	if x != nil {
		return x.MstiId
	}
	return 0
}

func (x *StpInstanceStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StpInstanceStatus) GetRootBridgeId() string {
	if x != nil {
		return x.RootBridgeId
	}
	return ""
}

func (x *StpInstanceStatus) GetRootPathCost() uint32 {
	if x != nil {
		return x.RootPathCost
	}
	return 0
}

func (x *StpInstanceStatus) GetDesignatedBridgeId() string {
	if x != nil {
		return x.DesignatedBridgeId
	}
	return ""
}

func (x *StpInstanceStatus) GetIsRootBridge() bool {
	if x != nil {
		return x.IsRootBridge
	}
	return false
}

func (x *StpInstanceStatus) GetBridgePriority() uint32 {
	if x != nil {
		return x.BridgePriority
	}
	return 0
}

func (x *StpInstanceStatus) GetTopologyChangeCount() uint64 {
	if x != nil {
		return x.TopologyChangeCount
	}
	return 0
}

func (x *StpInstanceStatus) GetLastTopologyChangeNs() uint64 {
	if x != nil {
		return x.LastTopologyChangeNs
	}
	return 0
}

//
// Operational STP status for one topology port.
//
// This message is intended to be embedded in:
//
//   topology_status.PortStatus
//
// This is the SINGLE authoritative STP status object for a topology port.
//
// It contains:
//
//   - port-wide STP state
//   - CIST port state
//   - MSTI-specific port state
//   - BPDU state/counters
//   - edge state
//   - point-to-point state
//   - port-level topology-change information
//
// No port state is duplicated in BridgeStpStatus or StpInstanceStatus.
type PortStpStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// OpenCNC topology Port.id.
	//
	// Identifies the topology port to which this status belongs.
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	//
	// Operational STP state of this port in the CIST/common spanning tree.
	Cist *PortInstanceStpStatus `protobuf:"bytes,2,opt,name=cist,proto3" json:"cist,omitempty"`
	//
	// Operational STP state of this port for MSTIs.
	//
	// Empty when MSTP is not active or the port has no MSTI state.
	MstiStates []*MstiPortStpStatus `protobuf:"bytes,3,rep,name=msti_states,json=mstiStates,proto3" json:"msti_states,omitempty"`
	//
	// Whether the port is currently participating in STP.
	//
	// This is a PORT-WIDE operational value.
	Participating bool `protobuf:"varint,4,opt,name=participating,proto3" json:"participating,omitempty"`
	//
	// Current operational edge-port state.
	OperEdgePort bool `protobuf:"varint,5,opt,name=oper_edge_port,json=operEdgePort,proto3" json:"oper_edge_port,omitempty"`
	//
	// Current operational point-to-point status.
	OperPointToPoint bool `protobuf:"varint,6,opt,name=oper_point_to_point,json=operPointToPoint,proto3" json:"oper_point_to_point,omitempty"`
	//
	// Current BPDU reception status.
	BpduRxActive bool `protobuf:"varint,7,opt,name=bpdu_rx_active,json=bpduRxActive,proto3" json:"bpdu_rx_active,omitempty"`
	//
	// Current BPDU transmission status.
	BpduTxActive bool `protobuf:"varint,8,opt,name=bpdu_tx_active,json=bpduTxActive,proto3" json:"bpdu_tx_active,omitempty"`
	//
	// Number of BPDUs received on this port.
	BpduRxCount uint64 `protobuf:"varint,9,opt,name=bpdu_rx_count,json=bpduRxCount,proto3" json:"bpdu_rx_count,omitempty"`
	//
	// Number of BPDUs transmitted on this port.
	BpduTxCount uint64 `protobuf:"varint,10,opt,name=bpdu_tx_count,json=bpduTxCount,proto3" json:"bpdu_tx_count,omitempty"`
	//
	// Number of topology changes observed on this port.
	TopologyChangeCount uint64 `protobuf:"varint,11,opt,name=topology_change_count,json=topologyChangeCount,proto3" json:"topology_change_count,omitempty"`
	//
	// Timestamp at which the port entered its current common/CIST
	// operational STP state.
	//
	// Nanoseconds since Unix epoch.
	StateChangeTimeNs uint64 `protobuf:"varint,12,opt,name=state_change_time_ns,json=stateChangeTimeNs,proto3" json:"state_change_time_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortStpStatus) Reset() {
	*x = PortStpStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortStpStatus) ProtoMessage() {}

func (x *PortStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortStpStatus.ProtoReflect.Descriptor instead.
func (*PortStpStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{3}
}

func (x *PortStpStatus) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *PortStpStatus) GetCist() *PortInstanceStpStatus {
	if x != nil {
		return x.Cist
	}
	return nil
}

func (x *PortStpStatus) GetMstiStates() []*MstiPortStpStatus {
	if x != nil {
		return x.MstiStates
	}
	return nil
}

func (x *PortStpStatus) GetParticipating() bool {
	if x != nil {
		return x.Participating
	}
	return false
}

func (x *PortStpStatus) GetOperEdgePort() bool {
	if x != nil {
		return x.OperEdgePort
	}
	return false
}

func (x *PortStpStatus) GetOperPointToPoint() bool {
	if x != nil {
		return x.OperPointToPoint
	}
	return false
}

func (x *PortStpStatus) GetBpduRxActive() bool {
	if x != nil {
		return x.BpduRxActive
	}
	return false
}

func (x *PortStpStatus) GetBpduTxActive() bool {
	if x != nil {
		return x.BpduTxActive
	}
	return false
}

func (x *PortStpStatus) GetBpduRxCount() uint64 {
	if x != nil {
		return x.BpduRxCount
	}
	return 0
}

func (x *PortStpStatus) GetBpduTxCount() uint64 {
	if x != nil {
		return x.BpduTxCount
	}
	return 0
}

func (x *PortStpStatus) GetTopologyChangeCount() uint64 {
	if x != nil {
		return x.TopologyChangeCount
	}
	return 0
}

func (x *PortStpStatus) GetStateChangeTimeNs() uint64 {
	if x != nil {
		return x.StateChangeTimeNs
	}
	return 0
}

//
// Operational STP state of a port within the CIST/common spanning tree.
//
// This is PORT + CIST state.
type PortInstanceStpStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Current operational STP port role.
	Role PortRole `protobuf:"varint,1,opt,name=role,proto3,enum=stp.PortRole" json:"role,omitempty"`
	//
	// Current operational STP port state.
	State PortState `protobuf:"varint,2,opt,name=state,proto3,enum=stp.PortState" json:"state,omitempty"`
	//
	// Whether the port is currently forwarding frames in the CIST.
	//
	// Retained as a convenient operational value even though it can
	// normally be inferred from state.
	Forwarding bool `protobuf:"varint,3,opt,name=forwarding,proto3" json:"forwarding,omitempty"`
	//
	// Current operational port priority in the CIST.
	PortPriority uint32 `protobuf:"varint,4,opt,name=port_priority,json=portPriority,proto3" json:"port_priority,omitempty"`
	//
	// Current operational path cost in the CIST.
	PortPathCost uint32 `protobuf:"varint,5,opt,name=port_path_cost,json=portPathCost,proto3" json:"port_path_cost,omitempty"`
	//
	// Root bridge identifier currently associated with this port.
	DesignatedRoot string `protobuf:"bytes,6,opt,name=designated_root,json=designatedRoot,proto3" json:"designated_root,omitempty"`
	//
	// Designated bridge identifier for the segment.
	DesignatedBridge string `protobuf:"bytes,7,opt,name=designated_bridge,json=designatedBridge,proto3" json:"designated_bridge,omitempty"`
	//
	// Designated port identifier for the segment.
	DesignatedPortId string `protobuf:"bytes,8,opt,name=designated_port_id,json=designatedPortId,proto3" json:"designated_port_id,omitempty"`
	//
	// Whether a topology-change acknowledgement was received.
	TopologyChangeAck bool `protobuf:"varint,9,opt,name=topology_change_ack,json=topologyChangeAck,proto3" json:"topology_change_ack,omitempty"`
	//
	// Whether topology-change propagation is currently active.
	TcPropagation bool `protobuf:"varint,10,opt,name=tc_propagation,json=tcPropagation,proto3" json:"tc_propagation,omitempty"`
	//
	// Whether an RSTP/MSTP proposal was received.
	ProposalReceived bool `protobuf:"varint,11,opt,name=proposal_received,json=proposalReceived,proto3" json:"proposal_received,omitempty"`
	//
	// Whether the RSTP/MSTP proposal/agreement handshake has reached
	// agreement.
	Agreement bool `protobuf:"varint,12,opt,name=agreement,proto3" json:"agreement,omitempty"`
	//
	// Number of topology changes observed for this CIST port state.
	TopologyChangeCount uint64 `protobuf:"varint,13,opt,name=topology_change_count,json=topologyChangeCount,proto3" json:"topology_change_count,omitempty"`
	//
	// Timestamp at which the port entered this CIST STP state.
	//
	// Nanoseconds since Unix epoch.
	StateChangeTimeNs uint64 `protobuf:"varint,14,opt,name=state_change_time_ns,json=stateChangeTimeNs,proto3" json:"state_change_time_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortInstanceStpStatus) Reset() {
	*x = PortInstanceStpStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInstanceStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInstanceStpStatus) ProtoMessage() {}

func (x *PortInstanceStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInstanceStpStatus.ProtoReflect.Descriptor instead.
func (*PortInstanceStpStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{4}
}

func (x *PortInstanceStpStatus) GetRole() PortRole {
	if x != nil {
		return x.Role
	}
	return PortRole_PORT_ROLE_UNSPECIFIED
}

func (x *PortInstanceStpStatus) GetState() PortState {
	if x != nil {
		return x.State
	}
	return PortState_PORT_STATE_UNSPECIFIED
}

func (x *PortInstanceStpStatus) GetForwarding() bool {
	if x != nil {
		return x.Forwarding
	}
	return false
}

func (x *PortInstanceStpStatus) GetPortPriority() uint32 {
	if x != nil {
		return x.PortPriority
	}
	return 0
}

func (x *PortInstanceStpStatus) GetPortPathCost() uint32 {
	if x != nil {
		return x.PortPathCost
	}
	return 0
}

func (x *PortInstanceStpStatus) GetDesignatedRoot() string {
	if x != nil {
		return x.DesignatedRoot
	}
	return ""
}

func (x *PortInstanceStpStatus) GetDesignatedBridge() string {
	if x != nil {
		return x.DesignatedBridge
	}
	return ""
}

func (x *PortInstanceStpStatus) GetDesignatedPortId() string {
	if x != nil {
		return x.DesignatedPortId
	}
	return ""
}

func (x *PortInstanceStpStatus) GetTopologyChangeAck() bool {
	if x != nil {
		return x.TopologyChangeAck
	}
	return false
}

func (x *PortInstanceStpStatus) GetTcPropagation() bool {
	if x != nil {
		return x.TcPropagation
	}
	return false
}

func (x *PortInstanceStpStatus) GetProposalReceived() bool {
	if x != nil {
		return x.ProposalReceived
	}
	return false
}

func (x *PortInstanceStpStatus) GetAgreement() bool {
	if x != nil {
		return x.Agreement
	}
	return false
}

func (x *PortInstanceStpStatus) GetTopologyChangeCount() uint64 {
	if x != nil {
		return x.TopologyChangeCount
	}
	return 0
}

func (x *PortInstanceStpStatus) GetStateChangeTimeNs() uint64 {
	if x != nil {
		return x.StateChangeTimeNs
	}
	return 0
}

//
// Operational STP state of a port within one MSTI.
//
// This is PORT + MSTI state.
type MstiPortStpStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// MSTI identifier.
	//
	// 1..4094.
	MstiId uint32 `protobuf:"varint,1,opt,name=msti_id,json=mstiId,proto3" json:"msti_id,omitempty"`
	//
	// Current operational MSTI port role.
	Role PortRole `protobuf:"varint,2,opt,name=role,proto3,enum=stp.PortRole" json:"role,omitempty"`
	//
	// Current operational MSTI port state.
	State PortState `protobuf:"varint,3,opt,name=state,proto3,enum=stp.PortState" json:"state,omitempty"`
	//
	// Whether this port is currently forwarding frames for this MSTI.
	Forwarding bool `protobuf:"varint,4,opt,name=forwarding,proto3" json:"forwarding,omitempty"`
	//
	// Current operational MSTI port priority.
	PortPriority uint32 `protobuf:"varint,5,opt,name=port_priority,json=portPriority,proto3" json:"port_priority,omitempty"`
	//
	// Current operational MSTI path cost.
	PortPathCost uint32 `protobuf:"varint,6,opt,name=port_path_cost,json=portPathCost,proto3" json:"port_path_cost,omitempty"`
	//
	// Whether this port is currently acting as the MSTI master port.
	//
	// This may also be represented by PORT_ROLE_MASTER where applicable,
	// but is retained as an explicit operational value for convenience.
	MasterPort bool `protobuf:"varint,7,opt,name=master_port,json=masterPort,proto3" json:"master_port,omitempty"`
	//
	// Number of topology changes observed for this MSTI on this port.
	TopologyChangeCount uint64 `protobuf:"varint,8,opt,name=topology_change_count,json=topologyChangeCount,proto3" json:"topology_change_count,omitempty"`
	//
	// Timestamp at which the port entered this MSTI state.
	//
	// Nanoseconds since Unix epoch.
	StateChangeTimeNs uint64 `protobuf:"varint,9,opt,name=state_change_time_ns,json=stateChangeTimeNs,proto3" json:"state_change_time_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MstiPortStpStatus) Reset() {
	*x = MstiPortStpStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MstiPortStpStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MstiPortStpStatus) ProtoMessage() {}

func (x *MstiPortStpStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MstiPortStpStatus.ProtoReflect.Descriptor instead.
func (*MstiPortStpStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{5}
}

func (x *MstiPortStpStatus) GetMstiId() uint32 {
	if x != nil {
		return x.MstiId
	}
	return 0
}

func (x *MstiPortStpStatus) GetRole() PortRole {
	if x != nil {
		return x.Role
	}
	return PortRole_PORT_ROLE_UNSPECIFIED
}

func (x *MstiPortStpStatus) GetState() PortState {
	if x != nil {
		return x.State
	}
	return PortState_PORT_STATE_UNSPECIFIED
}

func (x *MstiPortStpStatus) GetForwarding() bool {
	if x != nil {
		return x.Forwarding
	}
	return false
}

func (x *MstiPortStpStatus) GetPortPriority() uint32 {
	if x != nil {
		return x.PortPriority
	}
	return 0
}

func (x *MstiPortStpStatus) GetPortPathCost() uint32 {
	if x != nil {
		return x.PortPathCost
	}
	return 0
}

func (x *MstiPortStpStatus) GetMasterPort() bool {
	if x != nil {
		return x.MasterPort
	}
	return false
}

func (x *MstiPortStpStatus) GetTopologyChangeCount() uint64 {
	if x != nil {
		return x.TopologyChangeCount
	}
	return 0
}

func (x *MstiPortStpStatus) GetStateChangeTimeNs() uint64 {
	if x != nil {
		return x.StateChangeTimeNs
	}
	return 0
}

//
// Operational MST Configuration Identifier.
//
// This describes the MST configuration currently being used by the bridge.
type MstConfigurationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Operational MST Configuration Name.
	ConfigurationName string `protobuf:"bytes,1,opt,name=configuration_name,json=configurationName,proto3" json:"configuration_name,omitempty"`
	//
	// Operational MST Configuration Revision Level.
	RevisionLevel uint32 `protobuf:"varint,2,opt,name=revision_level,json=revisionLevel,proto3" json:"revision_level,omitempty"`
	//
	// Operational MST Configuration Format Selector.
	FormatSelector uint32 `protobuf:"varint,3,opt,name=format_selector,json=formatSelector,proto3" json:"format_selector,omitempty"`
	//
	// Operational MST Configuration Digest.
	//
	// Typically the 16-octet digest calculated from the MST configuration
	// according to IEEE MSTP.
	ConfigurationDigest []byte `protobuf:"bytes,4,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	//
	// Whether the operational MST configuration matches the expected
	// local configuration.
	ConfigurationMatch *bool `protobuf:"varint,5,opt,name=configuration_match,json=configurationMatch,proto3,oneof" json:"configuration_match,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MstConfigurationStatus) Reset() {
	*x = MstConfigurationStatus{}
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MstConfigurationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MstConfigurationStatus) ProtoMessage() {}

func (x *MstConfigurationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_stp_stp_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MstConfigurationStatus.ProtoReflect.Descriptor instead.
func (*MstConfigurationStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_stp_stp_status_proto_rawDescGZIP(), []int{6}
}

func (x *MstConfigurationStatus) GetConfigurationName() string {
	if x != nil {
		return x.ConfigurationName
	}
	return ""
}

func (x *MstConfigurationStatus) GetRevisionLevel() uint32 {
	if x != nil {
		return x.RevisionLevel
	}
	return 0
}

func (x *MstConfigurationStatus) GetFormatSelector() uint32 {
	if x != nil {
		return x.FormatSelector
	}
	return 0
}

func (x *MstConfigurationStatus) GetConfigurationDigest() []byte {
	if x != nil {
		return x.ConfigurationDigest
	}
	return nil
}

func (x *MstConfigurationStatus) GetConfigurationMatch() bool {
	if x != nil && x.ConfigurationMatch != nil {
		return *x.ConfigurationMatch
	}
	return false
}

var File_common_structures_stp_stp_status_proto protoreflect.FileDescriptor

const file_common_structures_stp_stp_status_proto_rawDesc = "" +
	"\n" +
	"&common/structures/stp/stp_status.proto\x12\n" +
	"stp_status\x1a\x1fcommon/structures/stp/stp.proto\"H\n" +
	"\x0fStpStatusReport\x125\n" +
	"\abridges\x18\x01 \x03(\v2\x1b.stp_status.BridgeStpStatusR\abridges\"\x97\x04\n" +
	"\x0fBridgeStpStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\rprotocol_mode\x18\x03 \x01(\x0e2\x14.stp.StpProtocolModeR\fprotocolMode\x12;\n" +
	"\tinstances\x18\x04 \x03(\v2\x1d.stp_status.StpInstanceStatusR\tinstances\x12\x1f\n" +
	"\vstp_enabled\x18\x05 \x01(\bR\n" +
	"stpEnabled\x12'\n" +
	"\x0fbridge_priority\x18\x06 \x01(\rR\x0ebridgePriority\x12&\n" +
	"\x0flast_updated_ns\x18\a \x01(\x04R\rlastUpdatedNs\x12T\n" +
	"\x11mst_configuration\x18\b \x01(\v2\".stp_status.MstConfigurationStatusH\x00R\x10mstConfiguration\x88\x01\x01\x12*\n" +
	"\x11mst_region_active\x18\t \x01(\bR\x0fmstRegionActive\x122\n" +
	"\x15topology_change_count\x18\n" +
	" \x01(\x04R\x13topologyChangeCount\x125\n" +
	"\x17last_topology_change_ns\x18\v \x01(\x04R\x14lastTopologyChangeNsB\x14\n" +
	"\x12_mst_configuration\"\x85\x03\n" +
	"\x11StpInstanceStatus\x12\x17\n" +
	"\amsti_id\x18\x01 \x01(\rR\x06mstiId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12$\n" +
	"\x0eroot_bridge_id\x18\x03 \x01(\tR\frootBridgeId\x12$\n" +
	"\x0eroot_path_cost\x18\x04 \x01(\rR\frootPathCost\x120\n" +
	"\x14designated_bridge_id\x18\x05 \x01(\tR\x12designatedBridgeId\x12$\n" +
	"\x0eis_root_bridge\x18\x06 \x01(\bR\fisRootBridge\x12'\n" +
	"\x0fbridge_priority\x18\a \x01(\rR\x0ebridgePriority\x122\n" +
	"\x15topology_change_count\x18\b \x01(\x04R\x13topologyChangeCount\x125\n" +
	"\x17last_topology_change_ns\x18\t \x01(\x04R\x14lastTopologyChangeNs\"\x93\x04\n" +
	"\rPortStpStatus\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x125\n" +
	"\x04cist\x18\x02 \x01(\v2!.stp_status.PortInstanceStpStatusR\x04cist\x12>\n" +
	"\vmsti_states\x18\x03 \x03(\v2\x1d.stp_status.MstiPortStpStatusR\n" +
	"mstiStates\x12$\n" +
	"\rparticipating\x18\x04 \x01(\bR\rparticipating\x12$\n" +
	"\x0eoper_edge_port\x18\x05 \x01(\bR\foperEdgePort\x12-\n" +
	"\x13oper_point_to_point\x18\x06 \x01(\bR\x10operPointToPoint\x12$\n" +
	"\x0ebpdu_rx_active\x18\a \x01(\bR\fbpduRxActive\x12$\n" +
	"\x0ebpdu_tx_active\x18\b \x01(\bR\fbpduTxActive\x12\"\n" +
	"\rbpdu_rx_count\x18\t \x01(\x04R\vbpduRxCount\x12\"\n" +
	"\rbpdu_tx_count\x18\n" +
	" \x01(\x04R\vbpduTxCount\x122\n" +
	"\x15topology_change_count\x18\v \x01(\x04R\x13topologyChangeCount\x12/\n" +
	"\x14state_change_time_ns\x18\f \x01(\x04R\x11stateChangeTimeNs\"\xd6\x04\n" +
	"\x15PortInstanceStpStatus\x12!\n" +
	"\x04role\x18\x01 \x01(\x0e2\r.stp.PortRoleR\x04role\x12$\n" +
	"\x05state\x18\x02 \x01(\x0e2\x0e.stp.PortStateR\x05state\x12\x1e\n" +
	"\n" +
	"forwarding\x18\x03 \x01(\bR\n" +
	"forwarding\x12#\n" +
	"\rport_priority\x18\x04 \x01(\rR\fportPriority\x12$\n" +
	"\x0eport_path_cost\x18\x05 \x01(\rR\fportPathCost\x12'\n" +
	"\x0fdesignated_root\x18\x06 \x01(\tR\x0edesignatedRoot\x12+\n" +
	"\x11designated_bridge\x18\a \x01(\tR\x10designatedBridge\x12,\n" +
	"\x12designated_port_id\x18\b \x01(\tR\x10designatedPortId\x12.\n" +
	"\x13topology_change_ack\x18\t \x01(\bR\x11topologyChangeAck\x12%\n" +
	"\x0etc_propagation\x18\n" +
	" \x01(\bR\rtcPropagation\x12+\n" +
	"\x11proposal_received\x18\v \x01(\bR\x10proposalReceived\x12\x1c\n" +
	"\tagreement\x18\f \x01(\bR\tagreement\x122\n" +
	"\x15topology_change_count\x18\r \x01(\x04R\x13topologyChangeCount\x12/\n" +
	"\x14state_change_time_ns\x18\x0e \x01(\x04R\x11stateChangeTimeNs\"\xe6\x02\n" +
	"\x11MstiPortStpStatus\x12\x17\n" +
	"\amsti_id\x18\x01 \x01(\rR\x06mstiId\x12!\n" +
	"\x04role\x18\x02 \x01(\x0e2\r.stp.PortRoleR\x04role\x12$\n" +
	"\x05state\x18\x03 \x01(\x0e2\x0e.stp.PortStateR\x05state\x12\x1e\n" +
	"\n" +
	"forwarding\x18\x04 \x01(\bR\n" +
	"forwarding\x12#\n" +
	"\rport_priority\x18\x05 \x01(\rR\fportPriority\x12$\n" +
	"\x0eport_path_cost\x18\x06 \x01(\rR\fportPathCost\x12\x1f\n" +
	"\vmaster_port\x18\a \x01(\bR\n" +
	"masterPort\x122\n" +
	"\x15topology_change_count\x18\b \x01(\x04R\x13topologyChangeCount\x12/\n" +
	"\x14state_change_time_ns\x18\t \x01(\x04R\x11stateChangeTimeNs\"\x98\x02\n" +
	"\x16MstConfigurationStatus\x12-\n" +
	"\x12configuration_name\x18\x01 \x01(\tR\x11configurationName\x12%\n" +
	"\x0erevision_level\x18\x02 \x01(\rR\rrevisionLevel\x12'\n" +
	"\x0fformat_selector\x18\x03 \x01(\rR\x0eformatSelector\x121\n" +
	"\x14configuration_digest\x18\x04 \x01(\fR\x13configurationDigest\x124\n" +
	"\x13configuration_match\x18\x05 \x01(\bH\x00R\x12configurationMatch\x88\x01\x01B\x16\n" +
	"\x14_configuration_matchB#Z!OpenCNC/common/structures/stp;stpb\x06proto3"

var (
	file_common_structures_stp_stp_status_proto_rawDescOnce sync.Once
	file_common_structures_stp_stp_status_proto_rawDescData []byte
)

func file_common_structures_stp_stp_status_proto_rawDescGZIP() []byte {
	file_common_structures_stp_stp_status_proto_rawDescOnce.Do(func() {
		file_common_structures_stp_stp_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_stp_stp_status_proto_rawDesc), len(file_common_structures_stp_stp_status_proto_rawDesc)))
	})
	return file_common_structures_stp_stp_status_proto_rawDescData
}

var file_common_structures_stp_stp_status_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_structures_stp_stp_status_proto_goTypes = []any{
	(*StpStatusReport)(nil),        // 0: stp_status.StpStatusReport
	(*BridgeStpStatus)(nil),        // 1: stp_status.BridgeStpStatus
	(*StpInstanceStatus)(nil),      // 2: stp_status.StpInstanceStatus
	(*PortStpStatus)(nil),          // 3: stp_status.PortStpStatus
	(*PortInstanceStpStatus)(nil),  // 4: stp_status.PortInstanceStpStatus
	(*MstiPortStpStatus)(nil),      // 5: stp_status.MstiPortStpStatus
	(*MstConfigurationStatus)(nil), // 6: stp_status.MstConfigurationStatus
	(StpProtocolMode)(0),           // 7: stp.StpProtocolMode
	(PortRole)(0),                  // 8: stp.PortRole
	(PortState)(0),                 // 9: stp.PortState
}
var file_common_structures_stp_stp_status_proto_depIdxs = []int32{
	1,  // 0: stp_status.StpStatusReport.bridges:type_name -> stp_status.BridgeStpStatus
	7,  // 1: stp_status.BridgeStpStatus.protocol_mode:type_name -> stp.StpProtocolMode
	2,  // 2: stp_status.BridgeStpStatus.instances:type_name -> stp_status.StpInstanceStatus
	6,  // 3: stp_status.BridgeStpStatus.mst_configuration:type_name -> stp_status.MstConfigurationStatus
	4,  // 4: stp_status.PortStpStatus.cist:type_name -> stp_status.PortInstanceStpStatus
	5,  // 5: stp_status.PortStpStatus.msti_states:type_name -> stp_status.MstiPortStpStatus
	8,  // 6: stp_status.PortInstanceStpStatus.role:type_name -> stp.PortRole
	9,  // 7: stp_status.PortInstanceStpStatus.state:type_name -> stp.PortState
	8,  // 8: stp_status.MstiPortStpStatus.role:type_name -> stp.PortRole
	9,  // 9: stp_status.MstiPortStpStatus.state:type_name -> stp.PortState
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_common_structures_stp_stp_status_proto_init() }
func file_common_structures_stp_stp_status_proto_init() {
	if File_common_structures_stp_stp_status_proto != nil {
		return
	}
	file_common_structures_stp_stp_proto_init()
	file_common_structures_stp_stp_status_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_structures_stp_stp_status_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_stp_stp_status_proto_rawDesc), len(file_common_structures_stp_stp_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_stp_stp_status_proto_goTypes,
		DependencyIndexes: file_common_structures_stp_stp_status_proto_depIdxs,
		MessageInfos:      file_common_structures_stp_stp_status_proto_msgTypes,
	}.Build()
	File_common_structures_stp_stp_status_proto = out.File
	file_common_structures_stp_stp_status_proto_goTypes = nil
	file_common_structures_stp_stp_status_proto_depIdxs = nil
}
