package engine

import (
	"fmt"
	"sync"

	"OpenCNC_config_service/common/observability"
	"OpenCNC_config_service/common/structures/credentials"
	"OpenCNC_config_service/common/structures/topology"
	"OpenCNC_config_service/monitor_service/pkg/catalog"
	"OpenCNC_config_service/monitor_service/pkg/managementSessions"
	monitor "OpenCNC_config_service/monitor_service/pkg/monitors"
	"OpenCNC_config_service/monitor_service/structures/monitoring"

	"google.golang.org/protobuf/proto"
)

type Engine struct {
	Catalog  *catalog.Catalog
	monitors map[string]monitor.Monitor
	mu       sync.Mutex // to protect the map
	obs      *observability.Client
}

func NewEngine(catalog *catalog.Catalog, obs *observability.Client) *Engine {
	return &Engine{
		Catalog:  catalog,
		monitors: make(map[string]monitor.Monitor),
		obs:      obs,
	}
}

// AddMonitor registers a monitor with the engine and starts it. The monitor name must be unique.
// The name must uniquely identify the monitored resource.
func (e *Engine) AddMonitor(name string, m monitor.Monitor) error {
	if m == nil {
		return fmt.Errorf("monitor is nil")
	}

	if name == "" {
		return fmt.Errorf("monitor name is empty")
	}

	e.mu.Lock()

	if _, exists := e.monitors[name]; exists {
		e.mu.Unlock()
		return fmt.Errorf("monitor %q already registered", name)
	}

	e.monitors[name] = m

	e.mu.Unlock()

	// Start outside the mutex.
	if err := m.Start(); err != nil {
		e.mu.Lock()
		delete(e.monitors, name)
		e.mu.Unlock()

		return fmt.Errorf("start monitor %q: %w", name, err)
	}

	return nil
}

// RemoveMonitor removes a monitor from the engine.
// The monitor must not be running.
func (e *Engine) RemoveMonitor(name string) error {
	e.mu.Lock()

	m, exists := e.monitors[name]
	if !exists {
		e.mu.Unlock()
		return fmt.Errorf("monitor %q not found", name)
	}

	delete(e.monitors, name)

	e.mu.Unlock()

	// Stop outside the mutex.
	m.Stop()

	return nil
}

// Monitor returns a registered monitor by name.
func (e *Engine) Monitor(name string) (monitor.Monitor, bool) {
	e.mu.Lock()
	defer e.mu.Unlock()

	m, exists := e.monitors[name]

	return m, exists
}

func (e *Engine) StartMonitoring(resource *monitoring.ResourceKey, node *topology.Node, creds *credentials.ManagementCredentials, counters []*monitoring.Counter, metrics []*monitoring.Metric) error {

	if resource == nil {
		return fmt.Errorf("monitoring resource is nil")
	}

	id := resource.String() // unique monitor per resource

	if len(counters) == 0 && len(metrics) == 0 {
		return fmt.Errorf("no monitoring items specified")
	}

	// ------------------------------------------------------------
	// Check that this monitoring ID is not already active.
	// the req id is used as the monitor name in the engine.
	// The monitor name is the unique identifier. this is not accurate
	// ------------------------------------------------------------

	e.mu.Lock()
	resourceMonitor, exists := e.monitors[id]
	e.mu.Unlock()
	if !exists {
		resourceMonitor = monitor.NewResourceMonitor(
			resource,
			e.HandleEvent,
			e.obs,
		)
	}

	//------------------------------------------------------------
	// Create monitor
	session, err := managementSessions.CreateSessionWithPassword(
		node.ManagementInfo.IpAddress,
		creds.GetUsernamePassword(),
	)
	if err != nil {
		return fmt.Errorf("failed to reach target node: %w", err)
	}

	// Add collectors to the monitor
	for _, counter := range counters {
		err := resourceMonitor.AddCollector(counter, resource, session, e.Catalog)
		if err != nil {
			return fmt.Errorf("failed to add collector for counter %q: %w", counter.Name, err)
		}
	}

	// Add meters to the monitor
	for _, metric := range metrics {
		// Add dependencies counters of the monitor
		for _, counterID := range metric.InputIds {
			//need to add the counters to the collector
			counter := proto.Clone(e.Catalog.GetCounter(counterID)).(*monitoring.Counter)
			if counter == nil {
				return fmt.Errorf("failed to add dependency counter %q for metric %q", counterID, metric.Name)
			}
			counter.PollIntervalMs = metric.EvaluationIntervalMs
			err := resourceMonitor.AddCollector(counter, resource, session, e.Catalog)
			if err != nil {
				return fmt.Errorf("failed to add collector for counter %q: %w", counter.Name, err)
			}
		}

		err := resourceMonitor.AddMeter(metric, resource)
		if err != nil {
			return fmt.Errorf("failed to add meter for metric %q: %w", metric.Name, err)
		}
	}

	// Start the monitor
	if err := e.AddMonitor(id, resourceMonitor); err != nil {
		return fmt.Errorf("failed to start monitoring: %w", err)
	}

	return nil
}

func (e *Engine) StopMonitoring(id string) error {
	if id == "" {
		return fmt.Errorf("monitoring id is empty")
	}

	return e.RemoveMonitor(id)
}

// HandleEvent receives events generated by monitors.
// The engine is the owner of event processing. The monitor only detects
// and reports the event.
func (e *Engine) HandleEvent(event *monitoring.MonitoringEvent) error {
	if event == nil {
		return fmt.Errorf("event is nil")
	}

	for _, action := range event.Actions {
		switch action {
		case monitoring.EventAction_REQUEST_ROLLBACK:
			if err := HandleRequestRollback(event); err != nil {
				return fmt.Errorf("handle rollback action: %w", err)
			}
		case monitoring.EventAction_REQUEST_RECONFIGURATION:
			if err := handleRequestReconfiguration(event); err != nil {
				return fmt.Errorf("handle reconfiguration action: %w", err)
			}
		}
	}

	// TODO:
	//
	// 1. Update engine monitoring state.
	// 2. Publish/forward the event.
	// 3. Execute or request the configured action.
	//
	// For the first version, simply accept the event once all configured actions have been dispatched.

	return nil
}
