package engine

import (
	"fmt"
	"sync"

	monitor "OpenCNC_config_service/monitor_service/pkg/monitors"
	"OpenCNC_config_service/monitor_service/structures/monitoring"
)

type Engine struct {
	monitors map[string]monitor.Monitor

	mu      sync.Mutex
	running bool
}

func NewEngine() *Engine {
	return &Engine{
		monitors: make(map[string]monitor.Monitor),
	}
}

// AddMonitor registers a monitor with the engine.
// The name must uniquely identify the monitored resource.
func (e *Engine) AddMonitor(name string, m monitor.Monitor) error {
	if m == nil {
		return fmt.Errorf("monitor is nil")
	}

	if name == "" {
		return fmt.Errorf("monitor name is empty")
	}

	e.mu.Lock()
	defer e.mu.Unlock()

	if e.running {
		return fmt.Errorf(
			"cannot add monitor while engine is running",
		)
	}

	if _, exists := e.monitors[name]; exists {
		return fmt.Errorf(
			"monitor %q already registered",
			name,
		)
	}

	e.monitors[name] = m

	return nil
}

// RemoveMonitor removes a monitor from the engine.
// The monitor must not be running.
func (e *Engine) RemoveMonitor(name string) error {
	e.mu.Lock()
	defer e.mu.Unlock()

	if e.running {
		return fmt.Errorf(
			"cannot remove monitor while engine is running",
		)
	}

	if _, exists := e.monitors[name]; !exists {
		return fmt.Errorf(
			"monitor %q not found",
			name,
		)
	}

	delete(e.monitors, name)

	return nil
}

// Start starts all registered monitors.
func (e *Engine) Start() error {
	e.mu.Lock()

	if e.running {
		e.mu.Unlock()
		return fmt.Errorf("engine is already running")
	}

	monitors := make(
		[]monitor.Monitor,
		0,
		len(e.monitors),
	)

	for _, m := range e.monitors {
		monitors = append(monitors, m)
	}

	e.running = true

	e.mu.Unlock()

	for _, m := range monitors {
		if err := m.Start(); err != nil {
			// Stop monitors that were already started.
			for _, started := range monitors {
				if started == m {
					break
				}

				started.Stop()
			}

			e.mu.Lock()
			e.running = false
			e.mu.Unlock()

			return fmt.Errorf(
				"start monitor: %w",
				err,
			)
		}
	}

	return nil
}

// Stop stops all registered monitors.
func (e *Engine) Stop() {
	e.mu.Lock()

	if !e.running {
		e.mu.Unlock()
		return
	}

	monitors := make(
		[]monitor.Monitor,
		0,
		len(e.monitors),
	)

	for _, m := range e.monitors {
		monitors = append(monitors, m)
	}

	e.running = false

	e.mu.Unlock()

	for _, m := range monitors {
		m.Stop()
	}
}

// IsRunning reports whether the engine is running.
func (e *Engine) IsRunning() bool {
	e.mu.Lock()
	defer e.mu.Unlock()

	return e.running
}

// Monitor returns a registered monitor by name.
func (e *Engine) Monitor(name string) (monitor.Monitor, bool) {
	e.mu.Lock()
	defer e.mu.Unlock()

	m, exists := e.monitors[name]

	return m, exists
}

// HandleEvent receives events generated by monitors.
// The engine is the owner of event processing. The monitor only detects
// and reports the event.
func (e *Engine) HandleEvent(event *monitoring.MonitoringEvent) error {
	if event == nil {
		return fmt.Errorf("event is nil")
	}

	// TODO:
	//
	// 1. Update engine monitoring state.
	// 2. Publish/forward the event.
	// 3. Execute or request the configured action.
	//
	// For the first version, simply accept the event.

	return nil
}
