// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common/structures/vlan/vlan.proto

package vlan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VlanRegistrationEntryType int32

const (
	VlanRegistrationEntryType_VLAN_REG_ENTRY_TYPE_UNSPECIFIED VlanRegistrationEntryType = 0
	VlanRegistrationEntryType_VLAN_REG_ENTRY_TYPE_STATIC      VlanRegistrationEntryType = 1
	VlanRegistrationEntryType_VLAN_REG_ENTRY_TYPE_DYNAMIC     VlanRegistrationEntryType = 2
)

// Enum value maps for VlanRegistrationEntryType.
var (
	VlanRegistrationEntryType_name = map[int32]string{
		0: "VLAN_REG_ENTRY_TYPE_UNSPECIFIED",
		1: "VLAN_REG_ENTRY_TYPE_STATIC",
		2: "VLAN_REG_ENTRY_TYPE_DYNAMIC",
	}
	VlanRegistrationEntryType_value = map[string]int32{
		"VLAN_REG_ENTRY_TYPE_UNSPECIFIED": 0,
		"VLAN_REG_ENTRY_TYPE_STATIC":      1,
		"VLAN_REG_ENTRY_TYPE_DYNAMIC":     2,
	}
)

func (x VlanRegistrationEntryType) Enum() *VlanRegistrationEntryType {
	p := new(VlanRegistrationEntryType)
	*p = x
	return p
}

func (x VlanRegistrationEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VlanRegistrationEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_vlan_vlan_proto_enumTypes[0].Descriptor()
}

func (VlanRegistrationEntryType) Type() protoreflect.EnumType {
	return &file_pkg_structures_vlan_vlan_proto_enumTypes[0]
}

func (x VlanRegistrationEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VlanRegistrationEntryType.Descriptor instead.
func (VlanRegistrationEntryType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{0}
}

type RegistrarAdminControl int32

const (
	RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_UNSPECIFIED          RegistrarAdminControl = 0
	RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_FIXED_NEW_IGNORED    RegistrarAdminControl = 1
	RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_FIXED_NEW_PROPAGATED RegistrarAdminControl = 2
	RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_FORBIDDEN            RegistrarAdminControl = 3
	RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_NORMAL               RegistrarAdminControl = 4
)

// Enum value maps for RegistrarAdminControl.
var (
	RegistrarAdminControl_name = map[int32]string{
		0: "REGISTRAR_ADMIN_CONTROL_UNSPECIFIED",
		1: "REGISTRAR_ADMIN_CONTROL_FIXED_NEW_IGNORED",
		2: "REGISTRAR_ADMIN_CONTROL_FIXED_NEW_PROPAGATED",
		3: "REGISTRAR_ADMIN_CONTROL_FORBIDDEN",
		4: "REGISTRAR_ADMIN_CONTROL_NORMAL",
	}
	RegistrarAdminControl_value = map[string]int32{
		"REGISTRAR_ADMIN_CONTROL_UNSPECIFIED":          0,
		"REGISTRAR_ADMIN_CONTROL_FIXED_NEW_IGNORED":    1,
		"REGISTRAR_ADMIN_CONTROL_FIXED_NEW_PROPAGATED": 2,
		"REGISTRAR_ADMIN_CONTROL_FORBIDDEN":            3,
		"REGISTRAR_ADMIN_CONTROL_NORMAL":               4,
	}
)

func (x RegistrarAdminControl) Enum() *RegistrarAdminControl {
	p := new(RegistrarAdminControl)
	*p = x
	return p
}

func (x RegistrarAdminControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrarAdminControl) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_vlan_vlan_proto_enumTypes[1].Descriptor()
}

func (RegistrarAdminControl) Type() protoreflect.EnumType {
	return &file_pkg_structures_vlan_vlan_proto_enumTypes[1]
}

func (x RegistrarAdminControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrarAdminControl.Descriptor instead.
func (RegistrarAdminControl) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{1}
}

type VlanTransmitted int32

const (
	VlanTransmitted_VLAN_TRANSMITTED_UNSPECIFIED VlanTransmitted = 0
	VlanTransmitted_VLAN_TRANSMITTED_TAGGED      VlanTransmitted = 1
	VlanTransmitted_VLAN_TRANSMITTED_UNTAGGED    VlanTransmitted = 2
)

// Enum value maps for VlanTransmitted.
var (
	VlanTransmitted_name = map[int32]string{
		0: "VLAN_TRANSMITTED_UNSPECIFIED",
		1: "VLAN_TRANSMITTED_TAGGED",
		2: "VLAN_TRANSMITTED_UNTAGGED",
	}
	VlanTransmitted_value = map[string]int32{
		"VLAN_TRANSMITTED_UNSPECIFIED": 0,
		"VLAN_TRANSMITTED_TAGGED":      1,
		"VLAN_TRANSMITTED_UNTAGGED":    2,
	}
)

func (x VlanTransmitted) Enum() *VlanTransmitted {
	p := new(VlanTransmitted)
	*p = x
	return p
}

func (x VlanTransmitted) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VlanTransmitted) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_vlan_vlan_proto_enumTypes[2].Descriptor()
}

func (VlanTransmitted) Type() protoreflect.EnumType {
	return &file_pkg_structures_vlan_vlan_proto_enumTypes[2]
}

func (x VlanTransmitted) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VlanTransmitted.Descriptor instead.
func (VlanTransmitted) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{2}
}

type AcceptableFrameType int32

const (
	AcceptableFrameType_ACCEPTABLE_FRAME_TYPE_UNSPECIFIED                             AcceptableFrameType = 0
	AcceptableFrameType_ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_VLAN_TAGGED                  AcceptableFrameType = 1
	AcceptableFrameType_ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_UNTAGGED_AND_PRIORITY_TAGGED AcceptableFrameType = 2
	AcceptableFrameType_ACCEPTABLE_FRAME_TYPE_ADMIT_ALL_FRAMES                        AcceptableFrameType = 3
)

// Enum value maps for AcceptableFrameType.
var (
	AcceptableFrameType_name = map[int32]string{
		0: "ACCEPTABLE_FRAME_TYPE_UNSPECIFIED",
		1: "ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_VLAN_TAGGED",
		2: "ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_UNTAGGED_AND_PRIORITY_TAGGED",
		3: "ACCEPTABLE_FRAME_TYPE_ADMIT_ALL_FRAMES",
	}
	AcceptableFrameType_value = map[string]int32{
		"ACCEPTABLE_FRAME_TYPE_UNSPECIFIED":                             0,
		"ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_VLAN_TAGGED":                  1,
		"ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_UNTAGGED_AND_PRIORITY_TAGGED": 2,
		"ACCEPTABLE_FRAME_TYPE_ADMIT_ALL_FRAMES":                        3,
	}
)

func (x AcceptableFrameType) Enum() *AcceptableFrameType {
	p := new(AcceptableFrameType)
	*p = x
	return p
}

func (x AcceptableFrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcceptableFrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_vlan_vlan_proto_enumTypes[3].Descriptor()
}

func (AcceptableFrameType) Type() protoreflect.EnumType {
	return &file_pkg_structures_vlan_vlan_proto_enumTypes[3]
}

func (x AcceptableFrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcceptableFrameType.Descriptor instead.
func (AcceptableFrameType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{3}
}

type ProtocolFrameFormatType int32

const (
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_UNSPECIFIED ProtocolFrameFormatType = 0
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_ETHERNET    ProtocolFrameFormatType = 1
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_RFC1042     ProtocolFrameFormatType = 2
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_SNAP8021H   ProtocolFrameFormatType = 3
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_SNAP_OTHER  ProtocolFrameFormatType = 4
	ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_LLC_OTHER   ProtocolFrameFormatType = 5
)

// Enum value maps for ProtocolFrameFormatType.
var (
	ProtocolFrameFormatType_name = map[int32]string{
		0: "PROTOCOL_FRAME_FORMAT_UNSPECIFIED",
		1: "PROTOCOL_FRAME_FORMAT_ETHERNET",
		2: "PROTOCOL_FRAME_FORMAT_RFC1042",
		3: "PROTOCOL_FRAME_FORMAT_SNAP8021H",
		4: "PROTOCOL_FRAME_FORMAT_SNAP_OTHER",
		5: "PROTOCOL_FRAME_FORMAT_LLC_OTHER",
	}
	ProtocolFrameFormatType_value = map[string]int32{
		"PROTOCOL_FRAME_FORMAT_UNSPECIFIED": 0,
		"PROTOCOL_FRAME_FORMAT_ETHERNET":    1,
		"PROTOCOL_FRAME_FORMAT_RFC1042":     2,
		"PROTOCOL_FRAME_FORMAT_SNAP8021H":   3,
		"PROTOCOL_FRAME_FORMAT_SNAP_OTHER":  4,
		"PROTOCOL_FRAME_FORMAT_LLC_OTHER":   5,
	}
)

func (x ProtocolFrameFormatType) Enum() *ProtocolFrameFormatType {
	p := new(ProtocolFrameFormatType)
	*p = x
	return p
}

func (x ProtocolFrameFormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolFrameFormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_vlan_vlan_proto_enumTypes[4].Descriptor()
}

func (ProtocolFrameFormatType) Type() protoreflect.EnumType {
	return &file_pkg_structures_vlan_vlan_proto_enumTypes[4]
}

func (x ProtocolFrameFormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolFrameFormatType.Descriptor instead.
func (ProtocolFrameFormatType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{4}
}

type BridgeVlanConfig struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	VlanRegistrationEntries []*VlanRegistrationEntry `protobuf:"bytes,1,rep,name=vlan_registration_entries,json=vlanRegistrationEntries,proto3" json:"vlan_registration_entries,omitempty"`
	VidToFidMappings        []*VidToFidMapping       `protobuf:"bytes,2,rep,name=vid_to_fid_mappings,json=vidToFidMappings,proto3" json:"vid_to_fid_mappings,omitempty"`
	// Optional advanced protocol-based VLAN grouping.
	ProtocolGroupDatabase []*ProtocolGroupDatabaseEntry `protobuf:"bytes,3,rep,name=protocol_group_database,json=protocolGroupDatabase,proto3" json:"protocol_group_database,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BridgeVlanConfig) Reset() {
	*x = BridgeVlanConfig{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeVlanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeVlanConfig) ProtoMessage() {}

func (x *BridgeVlanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeVlanConfig.ProtoReflect.Descriptor instead.
func (*BridgeVlanConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeVlanConfig) GetVlanRegistrationEntries() []*VlanRegistrationEntry {
	if x != nil {
		return x.VlanRegistrationEntries
	}
	return nil
}

func (x *BridgeVlanConfig) GetVidToFidMappings() []*VidToFidMapping {
	if x != nil {
		return x.VidToFidMappings
	}
	return nil
}

func (x *BridgeVlanConfig) GetProtocolGroupDatabase() []*ProtocolGroupDatabaseEntry {
	if x != nil {
		return x.ProtocolGroupDatabase
	}
	return nil
}

type VlanRegistrationEntry struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	DatabaseId    uint32                    `protobuf:"varint,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	VlanIds       []uint32                  `protobuf:"varint,2,rep,packed,name=vlan_ids,json=vlanIds,proto3" json:"vlan_ids,omitempty"` // 1..4094
	EntryType     VlanRegistrationEntryType `protobuf:"varint,3,opt,name=entry_type,json=entryType,proto3,enum=vlan.VlanRegistrationEntryType" json:"entry_type,omitempty"`
	PortMaps      []*VlanPortMap            `protobuf:"bytes,4,rep,name=port_maps,json=portMaps,proto3" json:"port_maps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanRegistrationEntry) Reset() {
	*x = VlanRegistrationEntry{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanRegistrationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanRegistrationEntry) ProtoMessage() {}

func (x *VlanRegistrationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanRegistrationEntry.ProtoReflect.Descriptor instead.
func (*VlanRegistrationEntry) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{1}
}

func (x *VlanRegistrationEntry) GetDatabaseId() uint32 {
	if x != nil {
		return x.DatabaseId
	}
	return 0
}

func (x *VlanRegistrationEntry) GetVlanIds() []uint32 {
	if x != nil {
		return x.VlanIds
	}
	return nil
}

func (x *VlanRegistrationEntry) GetEntryType() VlanRegistrationEntryType {
	if x != nil {
		return x.EntryType
	}
	return VlanRegistrationEntryType_VLAN_REG_ENTRY_TYPE_UNSPECIFIED
}

func (x *VlanRegistrationEntry) GetPortMaps() []*VlanPortMap {
	if x != nil {
		return x.PortMaps
	}
	return nil
}

type VlanPortMap struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PortId                string                 `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	RegistrarAdminControl RegistrarAdminControl  `protobuf:"varint,2,opt,name=registrar_admin_control,json=registrarAdminControl,proto3,enum=vlan.RegistrarAdminControl" json:"registrar_admin_control,omitempty"`
	VlanTransmitted       VlanTransmitted        `protobuf:"varint,3,opt,name=vlan_transmitted,json=vlanTransmitted,proto3,enum=vlan.VlanTransmitted" json:"vlan_transmitted,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VlanPortMap) Reset() {
	*x = VlanPortMap{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanPortMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanPortMap) ProtoMessage() {}

func (x *VlanPortMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanPortMap.ProtoReflect.Descriptor instead.
func (*VlanPortMap) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{2}
}

func (x *VlanPortMap) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *VlanPortMap) GetRegistrarAdminControl() RegistrarAdminControl {
	if x != nil {
		return x.RegistrarAdminControl
	}
	return RegistrarAdminControl_REGISTRAR_ADMIN_CONTROL_UNSPECIFIED
}

func (x *VlanPortMap) GetVlanTransmitted() VlanTransmitted {
	if x != nil {
		return x.VlanTransmitted
	}
	return VlanTransmitted_VLAN_TRANSMITTED_UNSPECIFIED
}

type VidToFidMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           uint32                 `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"` // 1..4094
	Fid           uint32                 `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VidToFidMapping) Reset() {
	*x = VidToFidMapping{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VidToFidMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VidToFidMapping) ProtoMessage() {}

func (x *VidToFidMapping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VidToFidMapping.ProtoReflect.Descriptor instead.
func (*VidToFidMapping) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{3}
}

func (x *VidToFidMapping) GetVid() uint32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VidToFidMapping) GetFid() uint32 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type VlanMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlanId        uint32                 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"` // 1..4094
	Tagged        bool                   `protobuf:"varint,2,opt,name=tagged,proto3" json:"tagged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VlanMembership) Reset() {
	*x = VlanMembership{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VlanMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanMembership) ProtoMessage() {}

func (x *VlanMembership) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanMembership.ProtoReflect.Descriptor instead.
func (*VlanMembership) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{4}
}

func (x *VlanMembership) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *VlanMembership) GetTagged() bool {
	if x != nil {
		return x.Tagged
	}
	return false
}

type VidTranslation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalVid      uint32                 `protobuf:"varint,1,opt,name=local_vid,json=localVid,proto3" json:"local_vid,omitempty"`
	RelayVid      uint32                 `protobuf:"varint,2,opt,name=relay_vid,json=relayVid,proto3" json:"relay_vid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VidTranslation) Reset() {
	*x = VidTranslation{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VidTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VidTranslation) ProtoMessage() {}

func (x *VidTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VidTranslation.ProtoReflect.Descriptor instead.
func (*VidTranslation) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{5}
}

func (x *VidTranslation) GetLocalVid() uint32 {
	if x != nil {
		return x.LocalVid
	}
	return 0
}

func (x *VidTranslation) GetRelayVid() uint32 {
	if x != nil {
		return x.RelayVid
	}
	return 0
}

type ProtocolGroupDatabaseEntry struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	DbIndex         uint32                  `protobuf:"varint,1,opt,name=db_index,json=dbIndex,proto3" json:"db_index,omitempty"`
	FrameFormatType ProtocolFrameFormatType `protobuf:"varint,2,opt,name=frame_format_type,json=frameFormatType,proto3,enum=vlan.ProtocolFrameFormatType" json:"frame_format_type,omitempty"`
	// Exactly one discriminator payload should be set depending on frame_format_type.
	Ethertype      *uint32 `protobuf:"varint,3,opt,name=ethertype,proto3,oneof" json:"ethertype,omitempty"`
	ProtocolId     *string `protobuf:"bytes,4,opt,name=protocol_id,json=protocolId,proto3,oneof" json:"protocol_id,omitempty"`               // xx-xx-xx-xx-xx
	LlcAddressPair *string `protobuf:"bytes,5,opt,name=llc_address_pair,json=llcAddressPair,proto3,oneof" json:"llc_address_pair,omitempty"` // xx-xx (dsap-ssap)
	GroupId        uint32  `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProtocolGroupDatabaseEntry) Reset() {
	*x = ProtocolGroupDatabaseEntry{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolGroupDatabaseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolGroupDatabaseEntry) ProtoMessage() {}

func (x *ProtocolGroupDatabaseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolGroupDatabaseEntry.ProtoReflect.Descriptor instead.
func (*ProtocolGroupDatabaseEntry) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{6}
}

func (x *ProtocolGroupDatabaseEntry) GetDbIndex() uint32 {
	if x != nil {
		return x.DbIndex
	}
	return 0
}

func (x *ProtocolGroupDatabaseEntry) GetFrameFormatType() ProtocolFrameFormatType {
	if x != nil {
		return x.FrameFormatType
	}
	return ProtocolFrameFormatType_PROTOCOL_FRAME_FORMAT_UNSPECIFIED
}

func (x *ProtocolGroupDatabaseEntry) GetEthertype() uint32 {
	if x != nil && x.Ethertype != nil {
		return *x.Ethertype
	}
	return 0
}

func (x *ProtocolGroupDatabaseEntry) GetProtocolId() string {
	if x != nil && x.ProtocolId != nil {
		return *x.ProtocolId
	}
	return ""
}

func (x *ProtocolGroupDatabaseEntry) GetLlcAddressPair() string {
	if x != nil && x.LlcAddressPair != nil {
		return *x.LlcAddressPair
	}
	return ""
}

func (x *ProtocolGroupDatabaseEntry) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ProtocolGroupVidSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	VlanIds       []uint32               `protobuf:"varint,2,rep,packed,name=vlan_ids,json=vlanIds,proto3" json:"vlan_ids,omitempty"` // 1..4094
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolGroupVidSet) Reset() {
	*x = ProtocolGroupVidSet{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolGroupVidSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolGroupVidSet) ProtoMessage() {}

func (x *ProtocolGroupVidSet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolGroupVidSet.ProtoReflect.Descriptor instead.
func (*ProtocolGroupVidSet) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{7}
}

func (x *ProtocolGroupVidSet) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ProtocolGroupVidSet) GetVlanIds() []uint32 {
	if x != nil {
		return x.VlanIds
	}
	return nil
}

type PortVlanAdvancedConfig struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	AcceptableFrame                   *AcceptableFrameType   `protobuf:"varint,1,opt,name=acceptable_frame,json=acceptableFrame,proto3,enum=vlan.AcceptableFrameType,oneof" json:"acceptable_frame,omitempty"`
	IngressFilteringEnabled           *bool                  `protobuf:"varint,2,opt,name=ingress_filtering_enabled,json=ingressFilteringEnabled,proto3,oneof" json:"ingress_filtering_enabled,omitempty"`
	RestrictedVlanRegistrationEnabled *bool                  `protobuf:"varint,3,opt,name=restricted_vlan_registration_enabled,json=restrictedVlanRegistrationEnabled,proto3,oneof" json:"restricted_vlan_registration_enabled,omitempty"`
	VidTranslationTableEnabled        *bool                  `protobuf:"varint,4,opt,name=vid_translation_table_enabled,json=vidTranslationTableEnabled,proto3,oneof" json:"vid_translation_table_enabled,omitempty"`
	EgressVidTranslationTableEnabled  *bool                  `protobuf:"varint,5,opt,name=egress_vid_translation_table_enabled,json=egressVidTranslationTableEnabled,proto3,oneof" json:"egress_vid_translation_table_enabled,omitempty"`
	VidTranslations                   []*VidTranslation      `protobuf:"bytes,6,rep,name=vid_translations,json=vidTranslations,proto3" json:"vid_translations,omitempty"`
	EgressVidTranslations             []*VidTranslation      `protobuf:"bytes,7,rep,name=egress_vid_translations,json=egressVidTranslations,proto3" json:"egress_vid_translations,omitempty"`
	// Optional mapping from protocol groups to VLAN sets for ingress classification.
	ProtocolGroupVidSets []*ProtocolGroupVidSet `protobuf:"bytes,8,rep,name=protocol_group_vid_sets,json=protocolGroupVidSets,proto3" json:"protocol_group_vid_sets,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PortVlanAdvancedConfig) Reset() {
	*x = PortVlanAdvancedConfig{}
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortVlanAdvancedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortVlanAdvancedConfig) ProtoMessage() {}

func (x *PortVlanAdvancedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_vlan_vlan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortVlanAdvancedConfig.ProtoReflect.Descriptor instead.
func (*PortVlanAdvancedConfig) Descriptor() ([]byte, []int) {
	return file_pkg_structures_vlan_vlan_proto_rawDescGZIP(), []int{8}
}

func (x *PortVlanAdvancedConfig) GetAcceptableFrame() AcceptableFrameType {
	if x != nil && x.AcceptableFrame != nil {
		return *x.AcceptableFrame
	}
	return AcceptableFrameType_ACCEPTABLE_FRAME_TYPE_UNSPECIFIED
}

func (x *PortVlanAdvancedConfig) GetIngressFilteringEnabled() bool {
	if x != nil && x.IngressFilteringEnabled != nil {
		return *x.IngressFilteringEnabled
	}
	return false
}

func (x *PortVlanAdvancedConfig) GetRestrictedVlanRegistrationEnabled() bool {
	if x != nil && x.RestrictedVlanRegistrationEnabled != nil {
		return *x.RestrictedVlanRegistrationEnabled
	}
	return false
}

func (x *PortVlanAdvancedConfig) GetVidTranslationTableEnabled() bool {
	if x != nil && x.VidTranslationTableEnabled != nil {
		return *x.VidTranslationTableEnabled
	}
	return false
}

func (x *PortVlanAdvancedConfig) GetEgressVidTranslationTableEnabled() bool {
	if x != nil && x.EgressVidTranslationTableEnabled != nil {
		return *x.EgressVidTranslationTableEnabled
	}
	return false
}

func (x *PortVlanAdvancedConfig) GetVidTranslations() []*VidTranslation {
	if x != nil {
		return x.VidTranslations
	}
	return nil
}

func (x *PortVlanAdvancedConfig) GetEgressVidTranslations() []*VidTranslation {
	if x != nil {
		return x.EgressVidTranslations
	}
	return nil
}

func (x *PortVlanAdvancedConfig) GetProtocolGroupVidSets() []*ProtocolGroupVidSet {
	if x != nil {
		return x.ProtocolGroupVidSets
	}
	return nil
}

var File_pkg_structures_vlan_vlan_proto protoreflect.FileDescriptor

const file_pkg_structures_vlan_vlan_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/structures/vlan/vlan.proto\x12\x04vlan\"\x8b\x02\n" +
	"\x10BridgeVlanConfig\x12W\n" +
	"\x19vlan_registration_entries\x18\x01 \x03(\v2\x1b.vlan.VlanRegistrationEntryR\x17vlanRegistrationEntries\x12D\n" +
	"\x13vid_to_fid_mappings\x18\x02 \x03(\v2\x15.vlan.VidToFidMappingR\x10vidToFidMappings\x12X\n" +
	"\x17protocol_group_database\x18\x03 \x03(\v2 .vlan.ProtocolGroupDatabaseEntryR\x15protocolGroupDatabase\"\xc3\x01\n" +
	"\x15VlanRegistrationEntry\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\rR\n" +
	"databaseId\x12\x19\n" +
	"\bvlan_ids\x18\x02 \x03(\rR\avlanIds\x12>\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\x0e2\x1f.vlan.VlanRegistrationEntryTypeR\tentryType\x12.\n" +
	"\tport_maps\x18\x04 \x03(\v2\x11.vlan.VlanPortMapR\bportMaps\"\xbd\x01\n" +
	"\vVlanPortMap\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12S\n" +
	"\x17registrar_admin_control\x18\x02 \x01(\x0e2\x1b.vlan.RegistrarAdminControlR\x15registrarAdminControl\x12@\n" +
	"\x10vlan_transmitted\x18\x03 \x01(\x0e2\x15.vlan.VlanTransmittedR\x0fvlanTransmitted\"5\n" +
	"\x0fVidToFidMapping\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\rR\x03vid\x12\x10\n" +
	"\x03fid\x18\x02 \x01(\rR\x03fid\"A\n" +
	"\x0eVlanMembership\x12\x17\n" +
	"\avlan_id\x18\x01 \x01(\rR\x06vlanId\x12\x16\n" +
	"\x06tagged\x18\x02 \x01(\bR\x06tagged\"J\n" +
	"\x0eVidTranslation\x12\x1b\n" +
	"\tlocal_vid\x18\x01 \x01(\rR\blocalVid\x12\x1b\n" +
	"\trelay_vid\x18\x02 \x01(\rR\brelayVid\"\xc8\x02\n" +
	"\x1aProtocolGroupDatabaseEntry\x12\x19\n" +
	"\bdb_index\x18\x01 \x01(\rR\adbIndex\x12I\n" +
	"\x11frame_format_type\x18\x02 \x01(\x0e2\x1d.vlan.ProtocolFrameFormatTypeR\x0fframeFormatType\x12!\n" +
	"\tethertype\x18\x03 \x01(\rH\x00R\tethertype\x88\x01\x01\x12$\n" +
	"\vprotocol_id\x18\x04 \x01(\tH\x01R\n" +
	"protocolId\x88\x01\x01\x12-\n" +
	"\x10llc_address_pair\x18\x05 \x01(\tH\x02R\x0ellcAddressPair\x88\x01\x01\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\rR\agroupIdB\f\n" +
	"\n" +
	"_ethertypeB\x0e\n" +
	"\f_protocol_idB\x13\n" +
	"\x11_llc_address_pair\"K\n" +
	"\x13ProtocolGroupVidSet\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x19\n" +
	"\bvlan_ids\x18\x02 \x03(\rR\avlanIds\"\x9f\x06\n" +
	"\x16PortVlanAdvancedConfig\x12I\n" +
	"\x10acceptable_frame\x18\x01 \x01(\x0e2\x19.vlan.AcceptableFrameTypeH\x00R\x0facceptableFrame\x88\x01\x01\x12?\n" +
	"\x19ingress_filtering_enabled\x18\x02 \x01(\bH\x01R\x17ingressFilteringEnabled\x88\x01\x01\x12T\n" +
	"$restricted_vlan_registration_enabled\x18\x03 \x01(\bH\x02R!restrictedVlanRegistrationEnabled\x88\x01\x01\x12F\n" +
	"\x1dvid_translation_table_enabled\x18\x04 \x01(\bH\x03R\x1avidTranslationTableEnabled\x88\x01\x01\x12S\n" +
	"$egress_vid_translation_table_enabled\x18\x05 \x01(\bH\x04R egressVidTranslationTableEnabled\x88\x01\x01\x12?\n" +
	"\x10vid_translations\x18\x06 \x03(\v2\x14.vlan.VidTranslationR\x0fvidTranslations\x12L\n" +
	"\x17egress_vid_translations\x18\a \x03(\v2\x14.vlan.VidTranslationR\x15egressVidTranslations\x12P\n" +
	"\x17protocol_group_vid_sets\x18\b \x03(\v2\x19.vlan.ProtocolGroupVidSetR\x14protocolGroupVidSetsB\x13\n" +
	"\x11_acceptable_frameB\x1c\n" +
	"\x1a_ingress_filtering_enabledB'\n" +
	"%_restricted_vlan_registration_enabledB \n" +
	"\x1e_vid_translation_table_enabledB'\n" +
	"%_egress_vid_translation_table_enabled*\x81\x01\n" +
	"\x19VlanRegistrationEntryType\x12#\n" +
	"\x1fVLAN_REG_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVLAN_REG_ENTRY_TYPE_STATIC\x10\x01\x12\x1f\n" +
	"\x1bVLAN_REG_ENTRY_TYPE_DYNAMIC\x10\x02*\xec\x01\n" +
	"\x15RegistrarAdminControl\x12'\n" +
	"#REGISTRAR_ADMIN_CONTROL_UNSPECIFIED\x10\x00\x12-\n" +
	")REGISTRAR_ADMIN_CONTROL_FIXED_NEW_IGNORED\x10\x01\x120\n" +
	",REGISTRAR_ADMIN_CONTROL_FIXED_NEW_PROPAGATED\x10\x02\x12%\n" +
	"!REGISTRAR_ADMIN_CONTROL_FORBIDDEN\x10\x03\x12\"\n" +
	"\x1eREGISTRAR_ADMIN_CONTROL_NORMAL\x10\x04*o\n" +
	"\x0fVlanTransmitted\x12 \n" +
	"\x1cVLAN_TRANSMITTED_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VLAN_TRANSMITTED_TAGGED\x10\x01\x12\x1d\n" +
	"\x19VLAN_TRANSMITTED_UNTAGGED\x10\x02*\xdd\x01\n" +
	"\x13AcceptableFrameType\x12%\n" +
	"!ACCEPTABLE_FRAME_TYPE_UNSPECIFIED\x10\x00\x120\n" +
	",ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_VLAN_TAGGED\x10\x01\x12A\n" +
	"=ACCEPTABLE_FRAME_TYPE_ADMIT_ONLY_UNTAGGED_AND_PRIORITY_TAGGED\x10\x02\x12*\n" +
	"&ACCEPTABLE_FRAME_TYPE_ADMIT_ALL_FRAMES\x10\x03*\xf7\x01\n" +
	"\x17ProtocolFrameFormatType\x12%\n" +
	"!PROTOCOL_FRAME_FORMAT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePROTOCOL_FRAME_FORMAT_ETHERNET\x10\x01\x12!\n" +
	"\x1dPROTOCOL_FRAME_FORMAT_RFC1042\x10\x02\x12#\n" +
	"\x1fPROTOCOL_FRAME_FORMAT_SNAP8021H\x10\x03\x12$\n" +
	" PROTOCOL_FRAME_FORMAT_SNAP_OTHER\x10\x04\x12#\n" +
	"\x1fPROTOCOL_FRAME_FORMAT_LLC_OTHER\x10\x05B\fZ\n" +
	"/vlan;vlanb\x06proto3"

var (
	file_pkg_structures_vlan_vlan_proto_rawDescOnce sync.Once
	file_pkg_structures_vlan_vlan_proto_rawDescData []byte
)

func file_pkg_structures_vlan_vlan_proto_rawDescGZIP() []byte {
	file_pkg_structures_vlan_vlan_proto_rawDescOnce.Do(func() {
		file_pkg_structures_vlan_vlan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_vlan_vlan_proto_rawDesc), len(file_pkg_structures_vlan_vlan_proto_rawDesc)))
	})
	return file_pkg_structures_vlan_vlan_proto_rawDescData
}

var file_pkg_structures_vlan_vlan_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_pkg_structures_vlan_vlan_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_structures_vlan_vlan_proto_goTypes = []any{
	(VlanRegistrationEntryType)(0),     // 0: vlan.VlanRegistrationEntryType
	(RegistrarAdminControl)(0),         // 1: vlan.RegistrarAdminControl
	(VlanTransmitted)(0),               // 2: vlan.VlanTransmitted
	(AcceptableFrameType)(0),           // 3: vlan.AcceptableFrameType
	(ProtocolFrameFormatType)(0),       // 4: vlan.ProtocolFrameFormatType
	(*BridgeVlanConfig)(nil),           // 5: vlan.BridgeVlanConfig
	(*VlanRegistrationEntry)(nil),      // 6: vlan.VlanRegistrationEntry
	(*VlanPortMap)(nil),                // 7: vlan.VlanPortMap
	(*VidToFidMapping)(nil),            // 8: vlan.VidToFidMapping
	(*VlanMembership)(nil),             // 9: vlan.VlanMembership
	(*VidTranslation)(nil),             // 10: vlan.VidTranslation
	(*ProtocolGroupDatabaseEntry)(nil), // 11: vlan.ProtocolGroupDatabaseEntry
	(*ProtocolGroupVidSet)(nil),        // 12: vlan.ProtocolGroupVidSet
	(*PortVlanAdvancedConfig)(nil),     // 13: vlan.PortVlanAdvancedConfig
}
var file_pkg_structures_vlan_vlan_proto_depIdxs = []int32{
	6,  // 0: vlan.BridgeVlanConfig.vlan_registration_entries:type_name -> vlan.VlanRegistrationEntry
	8,  // 1: vlan.BridgeVlanConfig.vid_to_fid_mappings:type_name -> vlan.VidToFidMapping
	11, // 2: vlan.BridgeVlanConfig.protocol_group_database:type_name -> vlan.ProtocolGroupDatabaseEntry
	0,  // 3: vlan.VlanRegistrationEntry.entry_type:type_name -> vlan.VlanRegistrationEntryType
	7,  // 4: vlan.VlanRegistrationEntry.port_maps:type_name -> vlan.VlanPortMap
	1,  // 5: vlan.VlanPortMap.registrar_admin_control:type_name -> vlan.RegistrarAdminControl
	2,  // 6: vlan.VlanPortMap.vlan_transmitted:type_name -> vlan.VlanTransmitted
	4,  // 7: vlan.ProtocolGroupDatabaseEntry.frame_format_type:type_name -> vlan.ProtocolFrameFormatType
	3,  // 8: vlan.PortVlanAdvancedConfig.acceptable_frame:type_name -> vlan.AcceptableFrameType
	10, // 9: vlan.PortVlanAdvancedConfig.vid_translations:type_name -> vlan.VidTranslation
	10, // 10: vlan.PortVlanAdvancedConfig.egress_vid_translations:type_name -> vlan.VidTranslation
	12, // 11: vlan.PortVlanAdvancedConfig.protocol_group_vid_sets:type_name -> vlan.ProtocolGroupVidSet
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_structures_vlan_vlan_proto_init() }
func file_pkg_structures_vlan_vlan_proto_init() {
	if File_pkg_structures_vlan_vlan_proto != nil {
		return
	}
	file_pkg_structures_vlan_vlan_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_structures_vlan_vlan_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_vlan_vlan_proto_rawDesc), len(file_pkg_structures_vlan_vlan_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_vlan_vlan_proto_goTypes,
		DependencyIndexes: file_pkg_structures_vlan_vlan_proto_depIdxs,
		EnumInfos:         file_pkg_structures_vlan_vlan_proto_enumTypes,
		MessageInfos:      file_pkg_structures_vlan_vlan_proto_msgTypes,
	}.Build()
	File_pkg_structures_vlan_vlan_proto = out.File
	file_pkg_structures_vlan_vlan_proto_goTypes = nil
	file_pkg_structures_vlan_vlan_proto_depIdxs = nil
}
