// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/draft_additions_tocheck/resources_status.proto

package resource_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NodeId                  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUtilization          float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	MemoryUsedBytes         uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes        uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	TemperatureMillicelsius uint64                 `protobuf:"varint,5,opt,name=temperature_millicelsius,json=temperatureMillicelsius,proto3" json:"temperature_millicelsius,omitempty"`
	TimestampNs             uint64                 `protobuf:"varint,6,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceStatus) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *ResourceStatus) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *ResourceStatus) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *ResourceStatus) GetTemperatureMillicelsius() uint64 {
	if x != nil {
		return x.TemperatureMillicelsius
	}
	return 0
}

func (x *ResourceStatus) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type ResourceAllocationStatus struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// TAS
	AvailableGateEntries uint32 `protobuf:"varint,2,opt,name=available_gate_entries,json=availableGateEntries,proto3" json:"available_gate_entries,omitempty"`
	TotalGateEntries     uint32 `protobuf:"varint,3,opt,name=total_gate_entries,json=totalGateEntries,proto3" json:"total_gate_entries,omitempty"`
	// PSFP
	AvailableFilters uint32 `protobuf:"varint,4,opt,name=available_filters,json=availableFilters,proto3" json:"available_filters,omitempty"`
	TotalFilters     uint32 `protobuf:"varint,5,opt,name=total_filters,json=totalFilters,proto3" json:"total_filters,omitempty"`
	// Queues
	AvailableQueues uint32 `protobuf:"varint,6,opt,name=available_queues,json=availableQueues,proto3" json:"available_queues,omitempty"`
	TimestampNs     uint64 `protobuf:"varint,7,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceAllocationStatus) Reset() {
	*x = ResourceAllocationStatus{}
	mi := &file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAllocationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAllocationStatus) ProtoMessage() {}

func (x *ResourceAllocationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAllocationStatus.ProtoReflect.Descriptor instead.
func (*ResourceAllocationStatus) Descriptor() ([]byte, []int) {
	return file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceAllocationStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResourceAllocationStatus) GetAvailableGateEntries() uint32 {
	if x != nil {
		return x.AvailableGateEntries
	}
	return 0
}

func (x *ResourceAllocationStatus) GetTotalGateEntries() uint32 {
	if x != nil {
		return x.TotalGateEntries
	}
	return 0
}

func (x *ResourceAllocationStatus) GetAvailableFilters() uint32 {
	if x != nil {
		return x.AvailableFilters
	}
	return 0
}

func (x *ResourceAllocationStatus) GetTotalFilters() uint32 {
	if x != nil {
		return x.TotalFilters
	}
	return 0
}

func (x *ResourceAllocationStatus) GetAvailableQueues() uint32 {
	if x != nil {
		return x.AvailableQueues
	}
	return 0
}

func (x *ResourceAllocationStatus) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

var File_common_structures_draft_additions_tocheck_resources_status_proto protoreflect.FileDescriptor

const file_common_structures_draft_additions_tocheck_resources_status_proto_rawDesc = "" +
	"\n" +
	"@common/structures/draft_additions_tocheck/resources_status.proto\x12\x0fresource_status\"\x8a\x02\n" +
	"\x0eResourceStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x129\n" +
	"\x18temperature_millicelsius\x18\x05 \x01(\x04R\x17temperatureMillicelsius\x12!\n" +
	"\ftimestamp_ns\x18\x06 \x01(\x04R\vtimestampNs\"\xb7\x02\n" +
	"\x18ResourceAllocationStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x124\n" +
	"\x16available_gate_entries\x18\x02 \x01(\rR\x14availableGateEntries\x12,\n" +
	"\x12total_gate_entries\x18\x03 \x01(\rR\x10totalGateEntries\x12+\n" +
	"\x11available_filters\x18\x04 \x01(\rR\x10availableFilters\x12#\n" +
	"\rtotal_filters\x18\x05 \x01(\rR\ftotalFilters\x12)\n" +
	"\x10available_queues\x18\x06 \x01(\rR\x0favailableQueues\x12!\n" +
	"\ftimestamp_ns\x18\a \x01(\x04R\vtimestampNsB;Z9OpenCNC/common/structures/resource_status;resource_statusb\x06proto3"

var (
	file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescOnce sync.Once
	file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescData []byte
)

func file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescGZIP() []byte {
	file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescOnce.Do(func() {
		file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_draft_additions_tocheck_resources_status_proto_rawDesc), len(file_common_structures_draft_additions_tocheck_resources_status_proto_rawDesc)))
	})
	return file_common_structures_draft_additions_tocheck_resources_status_proto_rawDescData
}

var file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_structures_draft_additions_tocheck_resources_status_proto_goTypes = []any{
	(*ResourceStatus)(nil),           // 0: resource_status.ResourceStatus
	(*ResourceAllocationStatus)(nil), // 1: resource_status.ResourceAllocationStatus
}
var file_common_structures_draft_additions_tocheck_resources_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_structures_draft_additions_tocheck_resources_status_proto_init() }
func file_common_structures_draft_additions_tocheck_resources_status_proto_init() {
	if File_common_structures_draft_additions_tocheck_resources_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_draft_additions_tocheck_resources_status_proto_rawDesc), len(file_common_structures_draft_additions_tocheck_resources_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_draft_additions_tocheck_resources_status_proto_goTypes,
		DependencyIndexes: file_common_structures_draft_additions_tocheck_resources_status_proto_depIdxs,
		MessageInfos:      file_common_structures_draft_additions_tocheck_resources_status_proto_msgTypes,
	}.Build()
	File_common_structures_draft_additions_tocheck_resources_status_proto = out.File
	file_common_structures_draft_additions_tocheck_resources_status_proto_goTypes = nil
	file_common_structures_draft_additions_tocheck_resources_status_proto_depIdxs = nil
}
