// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/structures/qbv/qbv_status.proto

package qbv

import (
	sync "OpenCNC_config_service/pkg/structures/sync"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync1 "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateState int32

const (
	GateState_GATE_STATE_UNSPECIFIED GateState = 0
	GateState_OPEN                   GateState = 1
	GateState_CLOSED                 GateState = 2
)

// Enum value maps for GateState.
var (
	GateState_name = map[int32]string{
		0: "GATE_STATE_UNSPECIFIED",
		1: "OPEN",
		2: "CLOSED",
	}
	GateState_value = map[string]int32{
		"GATE_STATE_UNSPECIFIED": 0,
		"OPEN":                   1,
		"CLOSED":                 2,
	}
)

func (x GateState) Enum() *GateState {
	p := new(GateState)
	*p = x
	return p
}

func (x GateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_structures_qbv_qbv_status_proto_enumTypes[0].Descriptor()
}

func (GateState) Type() protoreflect.EnumType {
	return &file_pkg_structures_qbv_qbv_status_proto_enumTypes[0]
}

func (x GateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateState.Descriptor instead.
func (GateState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_structures_qbv_qbv_status_proto_rawDescGZIP(), []int{0}
}

// Represents the runtime state of a single gate control entry (timeslot)
type GateControlEntryState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SlotId          uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                                    // Timeslot index in the schedule
	StartTimeNs     uint64                 `protobuf:"varint,2,opt,name=start_time_ns,json=startTimeNs,proto3" json:"start_time_ns,omitempty"`                   // Absolute start time (ns since epoch or base time)
	DurationNs      uint64                 `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`                        // Duration of the slot in nanoseconds
	GateState       GateState              `protobuf:"varint,4,opt,name=gate_state,json=gateState,proto3,enum=qbv_status.GateState" json:"gate_state,omitempty"` // Current state of the gate (open/closed)
	GateOpenCount   uint64                 `protobuf:"varint,5,opt,name=gate_open_count,json=gateOpenCount,proto3" json:"gate_open_count,omitempty"`             // Number of times gate was opened during this slot
	GateCloseCount  uint64                 `protobuf:"varint,6,opt,name=gate_close_count,json=gateCloseCount,proto3" json:"gate_close_count,omitempty"`          // Number of times gate was closed during this slot
	GateOpenTimeNs  uint64                 `protobuf:"varint,7,opt,name=gate_open_time_ns,json=gateOpenTimeNs,proto3" json:"gate_open_time_ns,omitempty"`        // Cumulative gate open time in ns within this slot
	GateCloseTimeNs uint64                 `protobuf:"varint,8,opt,name=gate_close_time_ns,json=gateCloseTimeNs,proto3" json:"gate_close_time_ns,omitempty"`     // Cumulative gate close time in ns within this slot
	ElapsedTimeNs   uint64                 `protobuf:"varint,9,opt,name=elapsed_time_ns,json=elapsedTimeNs,proto3" json:"elapsed_time_ns,omitempty"`             // Elapsed time since slot start
	RemainingTimeNs uint64                 `protobuf:"varint,10,opt,name=remaining_time_ns,json=remainingTimeNs,proto3" json:"remaining_time_ns,omitempty"`      // Remaining time until slot end
	GateErrorCount  uint64                 `protobuf:"varint,11,opt,name=gate_error_count,json=gateErrorCount,proto3" json:"gate_error_count,omitempty"`         // Number of errors detected on the gate (e.g., unexpected transitions)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GateControlEntryState) Reset() {
	*x = GateControlEntryState{}
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateControlEntryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateControlEntryState) ProtoMessage() {}

func (x *GateControlEntryState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateControlEntryState.ProtoReflect.Descriptor instead.
func (*GateControlEntryState) Descriptor() ([]byte, []int) {
	return file_pkg_structures_qbv_qbv_status_proto_rawDescGZIP(), []int{0}
}

func (x *GateControlEntryState) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *GateControlEntryState) GetStartTimeNs() uint64 {
	if x != nil {
		return x.StartTimeNs
	}
	return 0
}

func (x *GateControlEntryState) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *GateControlEntryState) GetGateState() GateState {
	if x != nil {
		return x.GateState
	}
	return GateState_GATE_STATE_UNSPECIFIED
}

func (x *GateControlEntryState) GetGateOpenCount() uint64 {
	if x != nil {
		return x.GateOpenCount
	}
	return 0
}

func (x *GateControlEntryState) GetGateCloseCount() uint64 {
	if x != nil {
		return x.GateCloseCount
	}
	return 0
}

func (x *GateControlEntryState) GetGateOpenTimeNs() uint64 {
	if x != nil {
		return x.GateOpenTimeNs
	}
	return 0
}

func (x *GateControlEntryState) GetGateCloseTimeNs() uint64 {
	if x != nil {
		return x.GateCloseTimeNs
	}
	return 0
}

func (x *GateControlEntryState) GetElapsedTimeNs() uint64 {
	if x != nil {
		return x.ElapsedTimeNs
	}
	return 0
}

func (x *GateControlEntryState) GetRemainingTimeNs() uint64 {
	if x != nil {
		return x.RemainingTimeNs
	}
	return 0
}

func (x *GateControlEntryState) GetGateErrorCount() uint64 {
	if x != nil {
		return x.GateErrorCount
	}
	return 0
}

// Represents the runtime state of a full TAS schedule on a port
type QbvScheduleState struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	ScheduleId        string                    `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`                         // Unique schedule identifier
	PortId            string                    `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`                                     // Port to which this schedule applies
	BaseTimeNs        uint64                    `protobuf:"varint,3,opt,name=base_time_ns,json=baseTimeNs,proto3" json:"base_time_ns,omitempty"`                      // Base reference time for schedule cycles
	CycleTimeNs       uint64                    `protobuf:"varint,4,opt,name=cycle_time_ns,json=cycleTimeNs,proto3" json:"cycle_time_ns,omitempty"`                   // Duration of one cycle
	CurrentTimeNs     uint64                    `protobuf:"varint,5,opt,name=current_time_ns,json=currentTimeNs,proto3" json:"current_time_ns,omitempty"`             // Current time (for reference within the cycle)
	CycleCount        uint64                    `protobuf:"varint,6,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`                        // Number of cycles completed
	CurrentCycleIndex uint32                    `protobuf:"varint,7,opt,name=current_cycle_index,json=currentCycleIndex,proto3" json:"current_cycle_index,omitempty"` // Index of the current slot in the cycle
	SlotsState        []*GateControlEntryState  `protobuf:"bytes,8,rep,name=slots_state,json=slotsState,proto3" json:"slots_state,omitempty"`                         // States of individual gate control entries (timeslots)
	SyncDiagnostics   *sync.GateSyncDiagnostics `protobuf:"bytes,9,opt,name=sync_diagnostics,json=syncDiagnostics,proto3" json:"sync_diagnostics,omitempty"`          // Diagnostics info for gate synchronization
	TimestampNs       uint64                    `protobuf:"varint,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`                    // Timestamp of this status snapshot (nanoseconds since epoch)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QbvScheduleState) Reset() {
	*x = QbvScheduleState{}
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QbvScheduleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QbvScheduleState) ProtoMessage() {}

func (x *QbvScheduleState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QbvScheduleState.ProtoReflect.Descriptor instead.
func (*QbvScheduleState) Descriptor() ([]byte, []int) {
	return file_pkg_structures_qbv_qbv_status_proto_rawDescGZIP(), []int{1}
}

func (x *QbvScheduleState) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *QbvScheduleState) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QbvScheduleState) GetBaseTimeNs() uint64 {
	if x != nil {
		return x.BaseTimeNs
	}
	return 0
}

func (x *QbvScheduleState) GetCycleTimeNs() uint64 {
	if x != nil {
		return x.CycleTimeNs
	}
	return 0
}

func (x *QbvScheduleState) GetCurrentTimeNs() uint64 {
	if x != nil {
		return x.CurrentTimeNs
	}
	return 0
}

func (x *QbvScheduleState) GetCycleCount() uint64 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *QbvScheduleState) GetCurrentCycleIndex() uint32 {
	if x != nil {
		return x.CurrentCycleIndex
	}
	return 0
}

func (x *QbvScheduleState) GetSlotsState() []*GateControlEntryState {
	if x != nil {
		return x.SlotsState
	}
	return nil
}

func (x *QbvScheduleState) GetSyncDiagnostics() *sync.GateSyncDiagnostics {
	if x != nil {
		return x.SyncDiagnostics
	}
	return nil
}

func (x *QbvScheduleState) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// Overall TAS runtime state report containing multiple schedules
type QbvStateReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*QbvScheduleState    `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QbvStateReport) Reset() {
	*x = QbvStateReport{}
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QbvStateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QbvStateReport) ProtoMessage() {}

func (x *QbvStateReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_structures_qbv_qbv_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QbvStateReport.ProtoReflect.Descriptor instead.
func (*QbvStateReport) Descriptor() ([]byte, []int) {
	return file_pkg_structures_qbv_qbv_status_proto_rawDescGZIP(), []int{2}
}

func (x *QbvStateReport) GetSchedules() []*QbvScheduleState {
	if x != nil {
		return x.Schedules
	}
	return nil
}

var File_pkg_structures_qbv_qbv_status_proto protoreflect.FileDescriptor

const file_pkg_structures_qbv_qbv_status_proto_rawDesc = "" +
	"\n" +
	"#pkg/structures/qbv/qbv_status.proto\x12\n" +
	"qbv_status\x1a\"pkg/structures/sync/syncdiag.proto\"\xd3\x03\n" +
	"\x15GateControlEntryState\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\"\n" +
	"\rstart_time_ns\x18\x02 \x01(\x04R\vstartTimeNs\x12\x1f\n" +
	"\vduration_ns\x18\x03 \x01(\x04R\n" +
	"durationNs\x124\n" +
	"\n" +
	"gate_state\x18\x04 \x01(\x0e2\x15.qbv_status.GateStateR\tgateState\x12&\n" +
	"\x0fgate_open_count\x18\x05 \x01(\x04R\rgateOpenCount\x12(\n" +
	"\x10gate_close_count\x18\x06 \x01(\x04R\x0egateCloseCount\x12)\n" +
	"\x11gate_open_time_ns\x18\a \x01(\x04R\x0egateOpenTimeNs\x12+\n" +
	"\x12gate_close_time_ns\x18\b \x01(\x04R\x0fgateCloseTimeNs\x12&\n" +
	"\x0felapsed_time_ns\x18\t \x01(\x04R\relapsedTimeNs\x12*\n" +
	"\x11remaining_time_ns\x18\n" +
	" \x01(\x04R\x0fremainingTimeNs\x12(\n" +
	"\x10gate_error_count\x18\v \x01(\x04R\x0egateErrorCount\"\xbc\x03\n" +
	"\x10QbvScheduleState\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\x12 \n" +
	"\fbase_time_ns\x18\x03 \x01(\x04R\n" +
	"baseTimeNs\x12\"\n" +
	"\rcycle_time_ns\x18\x04 \x01(\x04R\vcycleTimeNs\x12&\n" +
	"\x0fcurrent_time_ns\x18\x05 \x01(\x04R\rcurrentTimeNs\x12\x1f\n" +
	"\vcycle_count\x18\x06 \x01(\x04R\n" +
	"cycleCount\x12.\n" +
	"\x13current_cycle_index\x18\a \x01(\rR\x11currentCycleIndex\x12B\n" +
	"\vslots_state\x18\b \x03(\v2!.qbv_status.GateControlEntryStateR\n" +
	"slotsState\x12H\n" +
	"\x10sync_diagnostics\x18\t \x01(\v2\x1d.syncdiag.GateSyncDiagnosticsR\x0fsyncDiagnostics\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x04R\vtimestampNs\"L\n" +
	"\x0eQbvStateReport\x12:\n" +
	"\tschedules\x18\x01 \x03(\v2\x1c.qbv_status.QbvScheduleStateR\tschedules*=\n" +
	"\tGateState\x12\x1a\n" +
	"\x16GATE_STATE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02B/Z-OpenCNC_config_service/pkg/structures/qbv;qbvb\x06proto3"

var (
	file_pkg_structures_qbv_qbv_status_proto_rawDescOnce sync1.Once
	file_pkg_structures_qbv_qbv_status_proto_rawDescData []byte
)

func file_pkg_structures_qbv_qbv_status_proto_rawDescGZIP() []byte {
	file_pkg_structures_qbv_qbv_status_proto_rawDescOnce.Do(func() {
		file_pkg_structures_qbv_qbv_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_structures_qbv_qbv_status_proto_rawDesc), len(file_pkg_structures_qbv_qbv_status_proto_rawDesc)))
	})
	return file_pkg_structures_qbv_qbv_status_proto_rawDescData
}

var file_pkg_structures_qbv_qbv_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_structures_qbv_qbv_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_structures_qbv_qbv_status_proto_goTypes = []any{
	(GateState)(0),                   // 0: qbv_status.GateState
	(*GateControlEntryState)(nil),    // 1: qbv_status.GateControlEntryState
	(*QbvScheduleState)(nil),         // 2: qbv_status.QbvScheduleState
	(*QbvStateReport)(nil),           // 3: qbv_status.QbvStateReport
	(*sync.GateSyncDiagnostics)(nil), // 4: syncdiag.GateSyncDiagnostics
}
var file_pkg_structures_qbv_qbv_status_proto_depIdxs = []int32{
	0, // 0: qbv_status.GateControlEntryState.gate_state:type_name -> qbv_status.GateState
	1, // 1: qbv_status.QbvScheduleState.slots_state:type_name -> qbv_status.GateControlEntryState
	4, // 2: qbv_status.QbvScheduleState.sync_diagnostics:type_name -> syncdiag.GateSyncDiagnostics
	2, // 3: qbv_status.QbvStateReport.schedules:type_name -> qbv_status.QbvScheduleState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_structures_qbv_qbv_status_proto_init() }
func file_pkg_structures_qbv_qbv_status_proto_init() {
	if File_pkg_structures_qbv_qbv_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_structures_qbv_qbv_status_proto_rawDesc), len(file_pkg_structures_qbv_qbv_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_structures_qbv_qbv_status_proto_goTypes,
		DependencyIndexes: file_pkg_structures_qbv_qbv_status_proto_depIdxs,
		EnumInfos:         file_pkg_structures_qbv_qbv_status_proto_enumTypes,
		MessageInfos:      file_pkg_structures_qbv_qbv_status_proto_msgTypes,
	}.Build()
	File_pkg_structures_qbv_qbv_status_proto = out.File
	file_pkg_structures_qbv_qbv_status_proto_goTypes = nil
	file_pkg_structures_qbv_qbv_status_proto_depIdxs = nil
}
