// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: devicemodelregistry.proto

package devicemodelregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=model-name,proto3" json:"Name,omitempty"`
	YangFiles     []*YangFile            `protobuf:"bytes,2,rep,name=YangFiles,json=yang-files,proto3" json:"YangFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceModel) Reset() {
	*x = DeviceModel{}
	mi := &file_devicemodelregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceModel) ProtoMessage() {}

func (x *DeviceModel) ProtoReflect() protoreflect.Message {
	mi := &file_devicemodelregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceModel.ProtoReflect.Descriptor instead.
func (*DeviceModel) Descriptor() ([]byte, []int) {
	return file_devicemodelregistry_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceModel) GetYangFiles() []*YangFile {
	if x != nil {
		return x.YangFiles
	}
	return nil
}

type YangFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,json=file-name,proto3" json:"Name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=Revision,json=file-revision,proto3" json:"Revision,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,json=structure,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YangFile) Reset() {
	*x = YangFile{}
	mi := &file_devicemodelregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YangFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YangFile) ProtoMessage() {}

func (x *YangFile) ProtoReflect() protoreflect.Message {
	mi := &file_devicemodelregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YangFile.ProtoReflect.Descriptor instead.
func (*YangFile) Descriptor() ([]byte, []int) {
	return file_devicemodelregistry_proto_rawDescGZIP(), []int{1}
}

func (x *YangFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YangFile) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *YangFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_devicemodelregistry_proto protoreflect.FileDescriptor

const file_devicemodelregistry_proto_rawDesc = "" +
	"\n" +
	"\x19devicemodelregistry.proto\x12\x13devicemodelregistry\"e\n" +
	"\vDeviceModel\x12\x18\n" +
	"\x04Name\x18\x01 \x01(\tR\n" +
	"model-name\x12<\n" +
	"\tYangFiles\x18\x02 \x03(\v2\x1d.devicemodelregistry.YangFileR\n" +
	"yang-files\"d\n" +
	"\bYangFile\x12\x17\n" +
	"\x04Name\x18\x01 \x01(\tR\tfile-name\x12\x1f\n" +
	"\bRevision\x18\x02 \x01(\tR\rfile-revision\x12\x1e\n" +
	"\vdescription\x18\x03 \x01(\tR\tstructureB\x17Z\x15./devicemodelregistryb\x06proto3"

var (
	file_devicemodelregistry_proto_rawDescOnce sync.Once
	file_devicemodelregistry_proto_rawDescData []byte
)

func file_devicemodelregistry_proto_rawDescGZIP() []byte {
	file_devicemodelregistry_proto_rawDescOnce.Do(func() {
		file_devicemodelregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devicemodelregistry_proto_rawDesc), len(file_devicemodelregistry_proto_rawDesc)))
	})
	return file_devicemodelregistry_proto_rawDescData
}

var file_devicemodelregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_devicemodelregistry_proto_goTypes = []any{
	(*DeviceModel)(nil), // 0: devicemodelregistry.DeviceModel
	(*YangFile)(nil),    // 1: devicemodelregistry.YangFile
}
var file_devicemodelregistry_proto_depIdxs = []int32{
	1, // 0: devicemodelregistry.DeviceModel.YangFiles:type_name -> devicemodelregistry.YangFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_devicemodelregistry_proto_init() }
func file_devicemodelregistry_proto_init() {
	if File_devicemodelregistry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devicemodelregistry_proto_rawDesc), len(file_devicemodelregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_devicemodelregistry_proto_goTypes,
		DependencyIndexes: file_devicemodelregistry_proto_depIdxs,
		MessageInfos:      file_devicemodelregistry_proto_msgTypes,
	}.Build()
	File_devicemodelregistry_proto = out.File
	file_devicemodelregistry_proto_goTypes = nil
	file_devicemodelregistry_proto_depIdxs = nil
}
