// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/psfp/psfp.proto

package psfp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
// Priority specification used by PSFP.
//
// IEEE 802.1Q defines the priority specification as either:
//
//   - a specific priority value 0..7
//   - wildcard, matching any priority
//
// Reference:
//   IEEE 802.1Q-2022, 8.6.5.2
//   ieee802-dot1q-stream-filters-gates.yang priority-spec-type
type PrioritySpecification int32

const (
	PrioritySpecification_PRIORITY_SPECIFICATION_UNSPECIFIED PrioritySpecification = 0
	PrioritySpecification_PRIORITY_0                         PrioritySpecification = 1
	PrioritySpecification_PRIORITY_1                         PrioritySpecification = 2
	PrioritySpecification_PRIORITY_2                         PrioritySpecification = 3
	PrioritySpecification_PRIORITY_3                         PrioritySpecification = 4
	PrioritySpecification_PRIORITY_4                         PrioritySpecification = 5
	PrioritySpecification_PRIORITY_5                         PrioritySpecification = 6
	PrioritySpecification_PRIORITY_6                         PrioritySpecification = 7
	PrioritySpecification_PRIORITY_7                         PrioritySpecification = 8
	PrioritySpecification_PRIORITY_WILDCARD                  PrioritySpecification = 9
)

// Enum value maps for PrioritySpecification.
var (
	PrioritySpecification_name = map[int32]string{
		0: "PRIORITY_SPECIFICATION_UNSPECIFIED",
		1: "PRIORITY_0",
		2: "PRIORITY_1",
		3: "PRIORITY_2",
		4: "PRIORITY_3",
		5: "PRIORITY_4",
		6: "PRIORITY_5",
		7: "PRIORITY_6",
		8: "PRIORITY_7",
		9: "PRIORITY_WILDCARD",
	}
	PrioritySpecification_value = map[string]int32{
		"PRIORITY_SPECIFICATION_UNSPECIFIED": 0,
		"PRIORITY_0":                         1,
		"PRIORITY_1":                         2,
		"PRIORITY_2":                         3,
		"PRIORITY_3":                         4,
		"PRIORITY_4":                         5,
		"PRIORITY_5":                         6,
		"PRIORITY_6":                         7,
		"PRIORITY_7":                         8,
		"PRIORITY_WILDCARD":                  9,
	}
)

func (x PrioritySpecification) Enum() *PrioritySpecification {
	p := new(PrioritySpecification)
	*p = x
	return p
}

func (x PrioritySpecification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrioritySpecification) Descriptor() protoreflect.EnumDescriptor {
	return file_common_structures_psfp_psfp_proto_enumTypes[0].Descriptor()
}

func (PrioritySpecification) Type() protoreflect.EnumType {
	return &file_common_structures_psfp_psfp_proto_enumTypes[0]
}

func (x PrioritySpecification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrioritySpecification.Descriptor instead.
func (PrioritySpecification) EnumDescriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{0}
}

//
// Internal Priority Value (IPV) specification used by a Stream Gate.
//
// The IPV is either:
//
//   - null
//   - an internal priority value 0..7
//
// If null, the frame's existing priority is used to determine
// the traffic class.
//
// If a priority is specified, that internal priority is used
// instead.
//
// Reference:
//   IEEE 802.1Q-2022, 8.6.5.2
type InternalPriorityValue int32

const (
	InternalPriorityValue_INTERNAL_PRIORITY_VALUE_UNSPECIFIED InternalPriorityValue = 0
	InternalPriorityValue_IPV_0                               InternalPriorityValue = 1
	InternalPriorityValue_IPV_1                               InternalPriorityValue = 2
	InternalPriorityValue_IPV_2                               InternalPriorityValue = 3
	InternalPriorityValue_IPV_3                               InternalPriorityValue = 4
	InternalPriorityValue_IPV_4                               InternalPriorityValue = 5
	InternalPriorityValue_IPV_5                               InternalPriorityValue = 6
	InternalPriorityValue_IPV_6                               InternalPriorityValue = 7
	InternalPriorityValue_IPV_7                               InternalPriorityValue = 8
	InternalPriorityValue_IPV_NULL                            InternalPriorityValue = 9
)

// Enum value maps for InternalPriorityValue.
var (
	InternalPriorityValue_name = map[int32]string{
		0: "INTERNAL_PRIORITY_VALUE_UNSPECIFIED",
		1: "IPV_0",
		2: "IPV_1",
		3: "IPV_2",
		4: "IPV_3",
		5: "IPV_4",
		6: "IPV_5",
		7: "IPV_6",
		8: "IPV_7",
		9: "IPV_NULL",
	}
	InternalPriorityValue_value = map[string]int32{
		"INTERNAL_PRIORITY_VALUE_UNSPECIFIED": 0,
		"IPV_0":                               1,
		"IPV_1":                               2,
		"IPV_2":                               3,
		"IPV_3":                               4,
		"IPV_4":                               5,
		"IPV_5":                               6,
		"IPV_6":                               7,
		"IPV_7":                               8,
		"IPV_NULL":                            9,
	}
)

func (x InternalPriorityValue) Enum() *InternalPriorityValue {
	p := new(InternalPriorityValue)
	*p = x
	return p
}

func (x InternalPriorityValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalPriorityValue) Descriptor() protoreflect.EnumDescriptor {
	return file_common_structures_psfp_psfp_proto_enumTypes[1].Descriptor()
}

func (InternalPriorityValue) Type() protoreflect.EnumType {
	return &file_common_structures_psfp_psfp_proto_enumTypes[1]
}

func (x InternalPriorityValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalPriorityValue.Descriptor instead.
func (InternalPriorityValue) EnumDescriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{1}
}

//
// Administrative Stream Gate state.
//
// Reference:
//   IEEE 802.1Q-2022, 12.31.3.2.1
type StreamGateState int32

const (
	StreamGateState_STREAM_GATE_STATE_UNSPECIFIED StreamGateState = 0
	StreamGateState_STREAM_GATE_CLOSED            StreamGateState = 1
	StreamGateState_STREAM_GATE_OPEN              StreamGateState = 2
)

// Enum value maps for StreamGateState.
var (
	StreamGateState_name = map[int32]string{
		0: "STREAM_GATE_STATE_UNSPECIFIED",
		1: "STREAM_GATE_CLOSED",
		2: "STREAM_GATE_OPEN",
	}
	StreamGateState_value = map[string]int32{
		"STREAM_GATE_STATE_UNSPECIFIED": 0,
		"STREAM_GATE_CLOSED":            1,
		"STREAM_GATE_OPEN":              2,
	}
)

func (x StreamGateState) Enum() *StreamGateState {
	p := new(StreamGateState)
	*p = x
	return p
}

func (x StreamGateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamGateState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_structures_psfp_psfp_proto_enumTypes[2].Descriptor()
}

func (StreamGateState) Type() protoreflect.EnumType {
	return &file_common_structures_psfp_psfp_proto_enumTypes[2]
}

func (x StreamGateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamGateState.Descriptor instead.
func (StreamGateState) EnumDescriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{2}
}

//
// Specifies which Stream Handle a Stream Filter applies to.
//
// IEEE 802.1Q allows:
//
//   - a specific stream_handle
//   - wildcard, matching any stream
//
// IMPORTANT:
//
// stream_handle is produced by Stream Identification.
// PSFP does not independently identify the frame.
//
// Reference:
//   IEEE 802.1Q-2022, 12.31.2.2
type StreamHandleSpecification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*StreamHandleSpecification_StreamHandle
	//	*StreamHandleSpecification_Wildcard
	Value         isStreamHandleSpecification_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHandleSpecification) Reset() {
	*x = StreamHandleSpecification{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHandleSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHandleSpecification) ProtoMessage() {}

func (x *StreamHandleSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHandleSpecification.ProtoReflect.Descriptor instead.
func (*StreamHandleSpecification) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHandleSpecification) GetValue() isStreamHandleSpecification_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StreamHandleSpecification) GetStreamHandle() uint32 {
	if x != nil {
		if x, ok := x.Value.(*StreamHandleSpecification_StreamHandle); ok {
			return x.StreamHandle
		}
	}
	return 0
}

func (x *StreamHandleSpecification) GetWildcard() bool {
	if x != nil {
		if x, ok := x.Value.(*StreamHandleSpecification_Wildcard); ok {
			return x.Wildcard
		}
	}
	return false
}

type isStreamHandleSpecification_Value interface {
	isStreamHandleSpecification_Value()
}

type StreamHandleSpecification_StreamHandle struct {
	//
	// Specific local stream handle.
	StreamHandle uint32 `protobuf:"varint,1,opt,name=stream_handle,json=streamHandle,proto3,oneof"`
}

type StreamHandleSpecification_Wildcard struct {
	//
	// Wildcard matching any stream handle.
	//
	// Presence of this field represents the IEEE wildcard value.
	Wildcard bool `protobuf:"varint,2,opt,name=wildcard,proto3,oneof"`
}

func (*StreamHandleSpecification_StreamHandle) isStreamHandleSpecification_Value() {}

func (*StreamHandleSpecification_Wildcard) isStreamHandleSpecification_Value() {}

//
// Stream Filter Instance.
//
// A Stream Filter Instance determines which filtering and gating
// behavior applies to a received frame.
//
// Selection is based on:
//
//   stream_handle-spec
//   priority-spec
//
// If multiple entries match, the entry with the earliest position
// in the ordered Stream Filter Instance Table is selected.
//
// In the IEEE YANG model the integer stream-filter-instance-id
// determines this ordering: smaller values appear earlier.
//
// Reference:
//   IEEE 802.1Q-2022, 8.6.5.1
//   IEEE 802.1Q-2022, 12.31.2
type StreamFilterInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Stream Filter Instance ID.
	//
	// This is also the ordering value:
	// lower IDs appear earlier in the ordered list.
	//
	// Reference:
	//   IEEE 802.1Q-2022, 12.31.2.1
	StreamFilterInstanceId uint32 `protobuf:"varint,1,opt,name=stream_filter_instance_id,json=streamFilterInstanceId,proto3" json:"stream_filter_instance_id,omitempty"`
	//
	// Stream Handle selection criterion.
	StreamHandleSpec *StreamHandleSpecification `protobuf:"bytes,2,opt,name=stream_handle_spec,json=streamHandleSpec,proto3" json:"stream_handle_spec,omitempty"`
	//
	// Priority selection criterion.
	//
	// Either priority 0..7 or wildcard.
	PrioritySpec PrioritySpecification `protobuf:"varint,3,opt,name=priority_spec,json=prioritySpec,proto3,enum=tsn.psfp.PrioritySpecification" json:"priority_spec,omitempty"`
	//
	// Maximum SDU size accepted by this filter.
	//
	// Value 0 means that any SDU size is accepted.
	//
	// Units: octets.
	//
	// Reference:
	//   IEEE 802.1Q-2022, 8.6.5.3.1
	MaximumSduSize uint32 `protobuf:"varint,4,opt,name=maximum_sdu_size,json=maximumSduSize,proto3" json:"maximum_sdu_size,omitempty"`
	//
	// Enables permanent stream blocking when a frame exceeds
	// maximum_sdu_size.
	//
	// When enabled, an oversize frame causes
	// stream_blocked_due_to_oversize_frame to become true.
	//
	// Reference:
	//   IEEE 802.1Q-2022, 8.6.5.3.1
	StreamBlockedDueToOversizeFrameEnabled bool `protobuf:"varint,5,opt,name=stream_blocked_due_to_oversize_frame_enabled,json=streamBlockedDueToOversizeFrameEnabled,proto3" json:"stream_blocked_due_to_oversize_frame_enabled,omitempty"`
	//
	// Operational state indicating that the stream has been blocked
	// because an initial frame exceeded maximum_sdu_size.
	//
	// This is operational state rather than the configuration trigger.
	//
	// The value may be administratively reset to false.
	//
	// Reference:
	//   IEEE 802.1Q-2022, 8.6.5.3.1
	StreamBlockedDueToOversizeFrame bool `protobuf:"varint,6,opt,name=stream_blocked_due_to_oversize_frame,json=streamBlockedDueToOversizeFrame,proto3" json:"stream_blocked_due_to_oversize_frame,omitempty"`
	//
	// Stream Gate associated with this Stream Filter.
	//
	// A Stream Filter can reference one Stream Gate.
	//
	// Multiple Stream Filters may reference the same Stream Gate.
	//
	// This is the protobuf equivalent of the IEEE YANG
	// stream-gate-ref leaf.
	StreamGateInstanceId uint32 `protobuf:"varint,7,opt,name=stream_gate_instance_id,json=streamGateInstanceId,proto3" json:"stream_gate_instance_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StreamFilterInstance) Reset() {
	*x = StreamFilterInstance{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFilterInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFilterInstance) ProtoMessage() {}

func (x *StreamFilterInstance) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFilterInstance.ProtoReflect.Descriptor instead.
func (*StreamFilterInstance) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{1}
}

func (x *StreamFilterInstance) GetStreamFilterInstanceId() uint32 {
	if x != nil {
		return x.StreamFilterInstanceId
	}
	return 0
}

func (x *StreamFilterInstance) GetStreamHandleSpec() *StreamHandleSpecification {
	if x != nil {
		return x.StreamHandleSpec
	}
	return nil
}

func (x *StreamFilterInstance) GetPrioritySpec() PrioritySpecification {
	if x != nil {
		return x.PrioritySpec
	}
	return PrioritySpecification_PRIORITY_SPECIFICATION_UNSPECIFIED
}

func (x *StreamFilterInstance) GetMaximumSduSize() uint32 {
	if x != nil {
		return x.MaximumSduSize
	}
	return 0
}

func (x *StreamFilterInstance) GetStreamBlockedDueToOversizeFrameEnabled() bool {
	if x != nil {
		return x.StreamBlockedDueToOversizeFrameEnabled
	}
	return false
}

func (x *StreamFilterInstance) GetStreamBlockedDueToOversizeFrame() bool {
	if x != nil {
		return x.StreamBlockedDueToOversizeFrame
	}
	return false
}

func (x *StreamFilterInstance) GetStreamGateInstanceId() uint32 {
	if x != nil {
		return x.StreamGateInstanceId
	}
	return 0
}

//
// Stream Gate Instance.
//
// A Stream Gate controls whether frames associated with the selected
// Stream Filter are permitted to pass.
//
// The IEEE 802.1Q-2022 Stream Filters/Gates YANG model exposes the
// administrative gate state and administrative IPV.
//
// Reference:
//   IEEE 802.1Q-2022, 8.6.5.2
//   IEEE 802.1Q-2022, 12.31.3
type StreamGateInstance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Stream Gate Instance ID.
	//
	// Referenced by StreamFilterInstance.stream_gate_instance_id.
	StreamGateInstanceId uint32 `protobuf:"varint,1,opt,name=stream_gate_instance_id,json=streamGateInstanceId,proto3" json:"stream_gate_instance_id,omitempty"`
	//
	// Enables the Stream Gate state machines.
	//
	// IEEE default is false.
	//
	// Reference:
	//   IEEE 802.1Q-2022, 8.6.9.4.14
	GateEnabled bool `protobuf:"varint,2,opt,name=gate_enabled,json=gateEnabled,proto3" json:"gate_enabled,omitempty"`
	//
	// Administrative gate state.
	//
	// IEEE default is OPEN.
	AdminGateState StreamGateState `protobuf:"varint,3,opt,name=admin_gate_state,json=adminGateState,proto3,enum=tsn.psfp.StreamGateState" json:"admin_gate_state,omitempty"`
	//
	// Administrative Internal Priority Value.
	//
	// IEEE default is NULL.
	AdminIpv      InternalPriorityValue `protobuf:"varint,4,opt,name=admin_ipv,json=adminIpv,proto3,enum=tsn.psfp.InternalPriorityValue" json:"admin_ipv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGateInstance) Reset() {
	*x = StreamGateInstance{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGateInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGateInstance) ProtoMessage() {}

func (x *StreamGateInstance) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGateInstance.ProtoReflect.Descriptor instead.
func (*StreamGateInstance) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{2}
}

func (x *StreamGateInstance) GetStreamGateInstanceId() uint32 {
	if x != nil {
		return x.StreamGateInstanceId
	}
	return 0
}

func (x *StreamGateInstance) GetGateEnabled() bool {
	if x != nil {
		return x.GateEnabled
	}
	return false
}

func (x *StreamGateInstance) GetAdminGateState() StreamGateState {
	if x != nil {
		return x.AdminGateState
	}
	return StreamGateState_STREAM_GATE_STATE_UNSPECIFIED
}

func (x *StreamGateInstance) GetAdminIpv() InternalPriorityValue {
	if x != nil {
		return x.AdminIpv
	}
	return InternalPriorityValue_INTERNAL_PRIORITY_VALUE_UNSPECIFIED
}

//
// Implementation capabilities for PSFP Stream Filters and Gates.
//
// These correspond to the read-only max-* objects in the IEEE YANG
// model.
//
// Reference:
//   IEEE 802.1Q-2022, 12.31.1.1 and 12.31.1.2
type PsfpCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Maximum number of Stream Filter Instances supported by the
	// Bridge component.
	MaxStreamFilterInstances uint32 `protobuf:"varint,1,opt,name=max_stream_filter_instances,json=maxStreamFilterInstances,proto3" json:"max_stream_filter_instances,omitempty"`
	//
	// Maximum number of Stream Gate Instances supported by the
	// Bridge component.
	MaxStreamGateInstances uint32 `protobuf:"varint,2,opt,name=max_stream_gate_instances,json=maxStreamGateInstances,proto3" json:"max_stream_gate_instances,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PsfpCapabilities) Reset() {
	*x = PsfpCapabilities{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsfpCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsfpCapabilities) ProtoMessage() {}

func (x *PsfpCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsfpCapabilities.ProtoReflect.Descriptor instead.
func (*PsfpCapabilities) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{3}
}

func (x *PsfpCapabilities) GetMaxStreamFilterInstances() uint32 {
	if x != nil {
		return x.MaxStreamFilterInstances
	}
	return 0
}

func (x *PsfpCapabilities) GetMaxStreamGateInstances() uint32 {
	if x != nil {
		return x.MaxStreamGateInstances
	}
	return 0
}

//
// PSFP Stream Filter counters.
//
// These are intentionally kept separate from configuration.
//
// The exact counter set exposed by a particular implementation may
// depend on the managed objects supported by the bridge.
type StreamFilterCounters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Number of frames associated with this Stream Filter.
	Frames uint64 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	//
	// Number of frames discarded because they exceeded
	// maximum_sdu_size.
	OversizeFrames uint64 `protobuf:"varint,2,opt,name=oversize_frames,json=oversizeFrames,proto3" json:"oversize_frames,omitempty"`
	//
	// Number of frames discarded while the stream was blocked because
	// of an oversize frame.
	BlockedFrames uint64 `protobuf:"varint,3,opt,name=blocked_frames,json=blockedFrames,proto3" json:"blocked_frames,omitempty"`
	//
	// Number of frames discarded by the Stream Gate.
	GateClosedFrames uint64 `protobuf:"varint,4,opt,name=gate_closed_frames,json=gateClosedFrames,proto3" json:"gate_closed_frames,omitempty"`
	//
	// Number of frames discarded by policing.
	PolicedFrames uint64 `protobuf:"varint,5,opt,name=policed_frames,json=policedFrames,proto3" json:"policed_frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFilterCounters) Reset() {
	*x = StreamFilterCounters{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFilterCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFilterCounters) ProtoMessage() {}

func (x *StreamFilterCounters) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFilterCounters.ProtoReflect.Descriptor instead.
func (*StreamFilterCounters) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{4}
}

func (x *StreamFilterCounters) GetFrames() uint64 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *StreamFilterCounters) GetOversizeFrames() uint64 {
	if x != nil {
		return x.OversizeFrames
	}
	return 0
}

func (x *StreamFilterCounters) GetBlockedFrames() uint64 {
	if x != nil {
		return x.BlockedFrames
	}
	return 0
}

func (x *StreamFilterCounters) GetGateClosedFrames() uint64 {
	if x != nil {
		return x.GateClosedFrames
	}
	return 0
}

func (x *StreamFilterCounters) GetPolicedFrames() uint64 {
	if x != nil {
		return x.PolicedFrames
	}
	return 0
}

//
// Operational PSFP state associated with a Stream Filter.
type StreamFilterOperationalState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StreamFilterInstanceId uint32                 `protobuf:"varint,1,opt,name=stream_filter_instance_id,json=streamFilterInstanceId,proto3" json:"stream_filter_instance_id,omitempty"`
	Counters               *StreamFilterCounters  `protobuf:"bytes,2,opt,name=counters,proto3" json:"counters,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StreamFilterOperationalState) Reset() {
	*x = StreamFilterOperationalState{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFilterOperationalState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFilterOperationalState) ProtoMessage() {}

func (x *StreamFilterOperationalState) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFilterOperationalState.ProtoReflect.Descriptor instead.
func (*StreamFilterOperationalState) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{5}
}

func (x *StreamFilterOperationalState) GetStreamFilterInstanceId() uint32 {
	if x != nil {
		return x.StreamFilterInstanceId
	}
	return 0
}

func (x *StreamFilterOperationalState) GetCounters() *StreamFilterCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

//
// Complete PSFP configuration for a Bridge component.
//
// This message contains:
//
//   - Stream Filter Instances
//   - Stream Gate Instances
//   - implementation capabilities
//
// Flow Meter configuration is intentionally not duplicated here.
// It should be modeled according to the corresponding IEEE
// Bandwidth Profile / Flow Meter managed objects when the policing
// portion of PSFP is added.
type PsfpConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	//
	// Stream Filter Instance Table.
	//
	// Entries are ordered by stream_filter_instance_id.
	StreamFilterInstances []*StreamFilterInstance `protobuf:"bytes,1,rep,name=stream_filter_instances,json=streamFilterInstances,proto3" json:"stream_filter_instances,omitempty"`
	//
	// Stream Gate Instance Table.
	StreamGateInstances []*StreamGateInstance `protobuf:"bytes,2,rep,name=stream_gate_instances,json=streamGateInstances,proto3" json:"stream_gate_instances,omitempty"`
	//
	// Bridge implementation capabilities.
	//
	// Normally read-only / discovered from the device.
	Capabilities *PsfpCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	//
	// Operational state.
	//
	// Normally populated by telemetry/status rather than configuration.
	OperationalState []*StreamFilterOperationalState `protobuf:"bytes,4,rep,name=operational_state,json=operationalState,proto3" json:"operational_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PsfpConfiguration) Reset() {
	*x = PsfpConfiguration{}
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsfpConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsfpConfiguration) ProtoMessage() {}

func (x *PsfpConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_psfp_psfp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsfpConfiguration.ProtoReflect.Descriptor instead.
func (*PsfpConfiguration) Descriptor() ([]byte, []int) {
	return file_common_structures_psfp_psfp_proto_rawDescGZIP(), []int{6}
}

func (x *PsfpConfiguration) GetStreamFilterInstances() []*StreamFilterInstance {
	if x != nil {
		return x.StreamFilterInstances
	}
	return nil
}

func (x *PsfpConfiguration) GetStreamGateInstances() []*StreamGateInstance {
	if x != nil {
		return x.StreamGateInstances
	}
	return nil
}

func (x *PsfpConfiguration) GetCapabilities() *PsfpCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PsfpConfiguration) GetOperationalState() []*StreamFilterOperationalState {
	if x != nil {
		return x.OperationalState
	}
	return nil
}

var File_common_structures_psfp_psfp_proto protoreflect.FileDescriptor

const file_common_structures_psfp_psfp_proto_rawDesc = "" +
	"\n" +
	"!common/structures/psfp/psfp.proto\x12\btsn.psfp\"i\n" +
	"\x19StreamHandleSpecification\x12%\n" +
	"\rstream_handle\x18\x01 \x01(\rH\x00R\fstreamHandle\x12\x1c\n" +
	"\bwildcard\x18\x02 \x01(\bH\x00R\bwildcardB\a\n" +
	"\x05value\"\xf8\x03\n" +
	"\x14StreamFilterInstance\x129\n" +
	"\x19stream_filter_instance_id\x18\x01 \x01(\rR\x16streamFilterInstanceId\x12Q\n" +
	"\x12stream_handle_spec\x18\x02 \x01(\v2#.tsn.psfp.StreamHandleSpecificationR\x10streamHandleSpec\x12D\n" +
	"\rpriority_spec\x18\x03 \x01(\x0e2\x1f.tsn.psfp.PrioritySpecificationR\fprioritySpec\x12(\n" +
	"\x10maximum_sdu_size\x18\x04 \x01(\rR\x0emaximumSduSize\x12\\\n" +
	",stream_blocked_due_to_oversize_frame_enabled\x18\x05 \x01(\bR&streamBlockedDueToOversizeFrameEnabled\x12M\n" +
	"$stream_blocked_due_to_oversize_frame\x18\x06 \x01(\bR\x1fstreamBlockedDueToOversizeFrame\x125\n" +
	"\x17stream_gate_instance_id\x18\a \x01(\rR\x14streamGateInstanceId\"\xf1\x01\n" +
	"\x12StreamGateInstance\x125\n" +
	"\x17stream_gate_instance_id\x18\x01 \x01(\rR\x14streamGateInstanceId\x12!\n" +
	"\fgate_enabled\x18\x02 \x01(\bR\vgateEnabled\x12C\n" +
	"\x10admin_gate_state\x18\x03 \x01(\x0e2\x19.tsn.psfp.StreamGateStateR\x0eadminGateState\x12<\n" +
	"\tadmin_ipv\x18\x04 \x01(\x0e2\x1f.tsn.psfp.InternalPriorityValueR\badminIpv\"\x8c\x01\n" +
	"\x10PsfpCapabilities\x12=\n" +
	"\x1bmax_stream_filter_instances\x18\x01 \x01(\rR\x18maxStreamFilterInstances\x129\n" +
	"\x19max_stream_gate_instances\x18\x02 \x01(\rR\x16maxStreamGateInstances\"\xd3\x01\n" +
	"\x14StreamFilterCounters\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\x04R\x06frames\x12'\n" +
	"\x0foversize_frames\x18\x02 \x01(\x04R\x0eoversizeFrames\x12%\n" +
	"\x0eblocked_frames\x18\x03 \x01(\x04R\rblockedFrames\x12,\n" +
	"\x12gate_closed_frames\x18\x04 \x01(\x04R\x10gateClosedFrames\x12%\n" +
	"\x0epoliced_frames\x18\x05 \x01(\x04R\rpolicedFrames\"\x95\x01\n" +
	"\x1cStreamFilterOperationalState\x129\n" +
	"\x19stream_filter_instance_id\x18\x01 \x01(\rR\x16streamFilterInstanceId\x12:\n" +
	"\bcounters\x18\x02 \x01(\v2\x1e.tsn.psfp.StreamFilterCountersR\bcounters\"\xd2\x02\n" +
	"\x11PsfpConfiguration\x12V\n" +
	"\x17stream_filter_instances\x18\x01 \x03(\v2\x1e.tsn.psfp.StreamFilterInstanceR\x15streamFilterInstances\x12P\n" +
	"\x15stream_gate_instances\x18\x02 \x03(\v2\x1c.tsn.psfp.StreamGateInstanceR\x13streamGateInstances\x12>\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1a.tsn.psfp.PsfpCapabilitiesR\fcapabilities\x12S\n" +
	"\x11operational_state\x18\x04 \x03(\v2&.tsn.psfp.StreamFilterOperationalStateR\x10operationalState*\xd6\x01\n" +
	"\x15PrioritySpecification\x12&\n" +
	"\"PRIORITY_SPECIFICATION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PRIORITY_0\x10\x01\x12\x0e\n" +
	"\n" +
	"PRIORITY_1\x10\x02\x12\x0e\n" +
	"\n" +
	"PRIORITY_2\x10\x03\x12\x0e\n" +
	"\n" +
	"PRIORITY_3\x10\x04\x12\x0e\n" +
	"\n" +
	"PRIORITY_4\x10\x05\x12\x0e\n" +
	"\n" +
	"PRIORITY_5\x10\x06\x12\x0e\n" +
	"\n" +
	"PRIORITY_6\x10\a\x12\x0e\n" +
	"\n" +
	"PRIORITY_7\x10\b\x12\x15\n" +
	"\x11PRIORITY_WILDCARD\x10\t*\xa6\x01\n" +
	"\x15InternalPriorityValue\x12'\n" +
	"#INTERNAL_PRIORITY_VALUE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05IPV_0\x10\x01\x12\t\n" +
	"\x05IPV_1\x10\x02\x12\t\n" +
	"\x05IPV_2\x10\x03\x12\t\n" +
	"\x05IPV_3\x10\x04\x12\t\n" +
	"\x05IPV_4\x10\x05\x12\t\n" +
	"\x05IPV_5\x10\x06\x12\t\n" +
	"\x05IPV_6\x10\a\x12\t\n" +
	"\x05IPV_7\x10\b\x12\f\n" +
	"\bIPV_NULL\x10\t*b\n" +
	"\x0fStreamGateState\x12!\n" +
	"\x1dSTREAM_GATE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STREAM_GATE_CLOSED\x10\x01\x12\x14\n" +
	"\x10STREAM_GATE_OPEN\x10\x02B%Z#OpenCNC/common/structures/psfp;psfpb\x06proto3"

var (
	file_common_structures_psfp_psfp_proto_rawDescOnce sync.Once
	file_common_structures_psfp_psfp_proto_rawDescData []byte
)

func file_common_structures_psfp_psfp_proto_rawDescGZIP() []byte {
	file_common_structures_psfp_psfp_proto_rawDescOnce.Do(func() {
		file_common_structures_psfp_psfp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_psfp_psfp_proto_rawDesc), len(file_common_structures_psfp_psfp_proto_rawDesc)))
	})
	return file_common_structures_psfp_psfp_proto_rawDescData
}

var file_common_structures_psfp_psfp_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_structures_psfp_psfp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_structures_psfp_psfp_proto_goTypes = []any{
	(PrioritySpecification)(0),           // 0: tsn.psfp.PrioritySpecification
	(InternalPriorityValue)(0),           // 1: tsn.psfp.InternalPriorityValue
	(StreamGateState)(0),                 // 2: tsn.psfp.StreamGateState
	(*StreamHandleSpecification)(nil),    // 3: tsn.psfp.StreamHandleSpecification
	(*StreamFilterInstance)(nil),         // 4: tsn.psfp.StreamFilterInstance
	(*StreamGateInstance)(nil),           // 5: tsn.psfp.StreamGateInstance
	(*PsfpCapabilities)(nil),             // 6: tsn.psfp.PsfpCapabilities
	(*StreamFilterCounters)(nil),         // 7: tsn.psfp.StreamFilterCounters
	(*StreamFilterOperationalState)(nil), // 8: tsn.psfp.StreamFilterOperationalState
	(*PsfpConfiguration)(nil),            // 9: tsn.psfp.PsfpConfiguration
}
var file_common_structures_psfp_psfp_proto_depIdxs = []int32{
	3, // 0: tsn.psfp.StreamFilterInstance.stream_handle_spec:type_name -> tsn.psfp.StreamHandleSpecification
	0, // 1: tsn.psfp.StreamFilterInstance.priority_spec:type_name -> tsn.psfp.PrioritySpecification
	2, // 2: tsn.psfp.StreamGateInstance.admin_gate_state:type_name -> tsn.psfp.StreamGateState
	1, // 3: tsn.psfp.StreamGateInstance.admin_ipv:type_name -> tsn.psfp.InternalPriorityValue
	7, // 4: tsn.psfp.StreamFilterOperationalState.counters:type_name -> tsn.psfp.StreamFilterCounters
	4, // 5: tsn.psfp.PsfpConfiguration.stream_filter_instances:type_name -> tsn.psfp.StreamFilterInstance
	5, // 6: tsn.psfp.PsfpConfiguration.stream_gate_instances:type_name -> tsn.psfp.StreamGateInstance
	6, // 7: tsn.psfp.PsfpConfiguration.capabilities:type_name -> tsn.psfp.PsfpCapabilities
	8, // 8: tsn.psfp.PsfpConfiguration.operational_state:type_name -> tsn.psfp.StreamFilterOperationalState
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_common_structures_psfp_psfp_proto_init() }
func file_common_structures_psfp_psfp_proto_init() {
	if File_common_structures_psfp_psfp_proto != nil {
		return
	}
	file_common_structures_psfp_psfp_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamHandleSpecification_StreamHandle)(nil),
		(*StreamHandleSpecification_Wildcard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_psfp_psfp_proto_rawDesc), len(file_common_structures_psfp_psfp_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_psfp_psfp_proto_goTypes,
		DependencyIndexes: file_common_structures_psfp_psfp_proto_depIdxs,
		EnumInfos:         file_common_structures_psfp_psfp_proto_enumTypes,
		MessageInfos:      file_common_structures_psfp_psfp_proto_msgTypes,
	}.Build()
	File_common_structures_psfp_psfp_proto = out.File
	file_common_structures_psfp_psfp_proto_goTypes = nil
	file_common_structures_psfp_psfp_proto_depIdxs = nil
}
