package monitor

import (
	"context"
	"fmt"
	"reflect"
	"sync"
	"time"

	"OpenCNC_config_service/common/observability"
	"OpenCNC_config_service/monitor_service/pkg/catalog"
	"OpenCNC_config_service/monitor_service/pkg/collectors"
	"OpenCNC_config_service/monitor_service/pkg/meters"
	"OpenCNC_config_service/monitor_service/structures/monitoring"

	"github.com/openshift-telco/go-netconf-client/netconf"
	"google.golang.org/protobuf/proto"
)

type EventHandler func(event *monitoring.MonitoringEvent) error

type ResourceMonitor struct {
	obs *observability.Client
	ctx context.Context

	target     *monitoring.ResourceKey
	meters     map[string]meters.Meter
	collectors []collectors.Collector

	eventHandler EventHandler

	running bool
	stopCh  chan struct{}

	mu sync.Mutex
}

// scheduleGroup represents one ticker: collectors and metrics
// with the same interval share one ticker to reduce goroutine overhead.
type scheduleGroup struct {
	interval time.Duration
	ticker   *time.Ticker

	collectors []collectors.Collector
	metricIDs  []string
}

func NewResourceMonitor(
	target *monitoring.ResourceKey,
	eventHandler EventHandler, // a callbak function to handle events generated by the monitor
	obs *observability.Client,
) *ResourceMonitor {
	return &ResourceMonitor{
		target:       target,
		meters:       make(map[string]meters.Meter),
		eventHandler: eventHandler,
		obs:          obs,
		ctx:          context.Background(),
	}
}

func (m *ResourceMonitor) Resource() *monitoring.ResourceKey {
	return m.target
}

// Start starts the background monitoring scheduler.
func (m *ResourceMonitor) Start() error {

	m.mu.Lock()

	if m.running {
		m.mu.Unlock()
		return fmt.Errorf("monitor is already running")
	}

	m.running = true
	m.stopCh = make(chan struct{})

	stopCh := m.stopCh

	// Copy collectors/meters configuration before starting the scheduler.
	collectorsSnapshot := append([]collectors.Collector(nil), m.collectors...)
	metersSnapshot := copyMeters(m.meters)

	m.mu.Unlock()

	// Build the schedule from the snapshot.
	schedule, err := buildSchedule(collectorsSnapshot, metersSnapshot)
	if err != nil {
		m.Stop()
		return err
	}
	fmt.Println("=== Schedule ===")
	fmt.Println("Target monitor: ", m.target.String())
	fmt.Println("===============")
	for i, group := range schedule {
		fmt.Printf("Group %d\n", i+1)
		fmt.Printf("  Interval: %s\n", group.interval)
		fmt.Printf("  Collectors: [")

		for i, collector := range group.collectors {
			if i > 0 {
				fmt.Printf(",")
			}
			fmt.Printf("[")
			for j, counterID := range collector.CounterIds() {
				if j > 0 {
					fmt.Printf(",")
				}
				fmt.Printf("%q", counterID)
			}
			fmt.Printf("]")
		}

		fmt.Printf("]\n")
		fmt.Printf("  Metrics:  %v\n", group.metricIDs)
		fmt.Printf("  Ticker:   %v\n", group.ticker != nil)
		fmt.Println()
	}
	fmt.Println("===============")

	go m.runLoop(stopCh, schedule)

	return nil
}

// Stop stops the background monitoring scheduler.
func (m *ResourceMonitor) Stop() {
	m.mu.Lock()
	defer m.mu.Unlock()

	if !m.running {
		return
	}

	m.running = false

	close(m.stopCh)
	m.stopCh = nil
}

// AddCollector registers a collector used by this monitor.
func (m *ResourceMonitor) AddCollector(counter *monitoring.Counter, resource *monitoring.ResourceKey, session *netconf.Session, catalog *catalog.Catalog) error {

	if counter == nil {
		return fmt.Errorf("counter is nil")
	}

	if resource.NodeId != m.target.NodeId {
		return fmt.Errorf("counter doesn't belong to the assigned monitor, target node ID is not matching")
	}

	for _, collector := range m.collectors {
		if collector.PollInterval() == counter.PollIntervalMs && collector.Target() == m.target {
			if collector.HasCounter(counter.Name) {
				return nil // Collector already registered for this counter and interval.
			} else {
				if err := collector.AddCounter(counter); err != nil {
					return fmt.Errorf("failed to add counter %q to collector: %w", counter.Name, err)
				}
				return nil // Add the counter to the existing collector with the same interval.
			}
		}
	}
	// No existing collector with the same interval, create a new one.
	newCollector := collectors.NewNetconfCollector(
		resource,
		session,
		catalog,
		m.obs,
		counter.PollIntervalMs,
	)

	if err := newCollector.AddCounter(counter); err != nil {
		return fmt.Errorf("failed to add counter %q to new collector: %w", counter.Name, err)
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	if m.running {
		return fmt.Errorf(
			"cannot add collector while monitor is running",
		)
	}

	m.collectors = append(
		m.collectors,
		newCollector,
	)

	return nil
}

// AddMeter registers a meter used by this monitor.
func (m *ResourceMonitor) AddMeter(metric *monitoring.Metric, resource *monitoring.ResourceKey) error {

	if metric == nil {
		return fmt.Errorf("metric is nil")
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	if meter, exists := m.meters[metric.Name]; exists {
		meter.Metric().EvaluationIntervalMs = metric.EvaluationIntervalMs
		return nil // Meter already registered, update the evaluation interval.
	}

	meter, err := meters.NewPacketRateMeter(resource, m.obs, metric)
	if err != nil {
		return fmt.Errorf("failed to create meter for metric %q: %w", metric.Name, err)
	}

	if m.running {
		return fmt.Errorf(
			"cannot add meter while monitor is running",
		)
	}

	m.meters[metric.Name] = meter
	return nil
}

// runLoop owns the single scheduler goroutine.
//
// There may be multiple tickers, but there is only ONE goroutine
// consuming them.
//
// For every tick:
//
//  1. Collect due collectors.
//  2. Measure due metrics.
//
// Therefore, even when collection and measurement have different
// intervals, collection is always processed before measurement
// when both are due at the same time.
func (m *ResourceMonitor) runLoop(stopCh <-chan struct{}, schedule []*scheduleGroup) {
	defer stopSchedule(schedule)

	cases := make([]reflectSelectCase, 0, len(schedule)+1)

	// Case 0 is always the stop channel.
	cases = append(cases, reflectSelectCase{stopCh: stopCh})

	for _, group := range schedule {
		cases = append(cases, reflectSelectCase{tickerCh: group.ticker.C, group: group})
	}

	for {
		index := selectSchedule(cases)

		// Stop requested.
		if index == 0 {
			return
		}

		group := cases[index].group

		if group == nil {
			continue
		}

		// ----------------------------------------------------
		// 1. COLLECTION
		// ----------------------------------------------------

		if len(group.collectors) > 0 {
			if err := m.collectAndFeed(group.collectors); err != nil {
				// TODO: log/report monitor error with obesrvability package.
				continue
			}
		}

		// ----------------------------------------------------
		// 2. MEASUREMENT
		// ----------------------------------------------------

		if len(group.metricIDs) > 0 {
			if err := m.measureAndFeed(group.metricIDs); err != nil {
				// TODO: log/report monitor error.
				continue
			}
		}
	}
}

// -----------------------------------------------------------------------------
// OPTIONAL MANUAL RUN
// -----------------------------------------------------------------------------

// Run performs one complete monitoring cycle manually.
// This is intentionally different from the scheduler:
// Run() is useful for tests or explicit one-shot execution.
func (m *ResourceMonitor) Run() error {
	m.mu.Lock()

	if !m.running {
		m.mu.Unlock()
		return fmt.Errorf("monitor is not running")
	}

	collectorsSnapshot := append(
		[]collectors.Collector(nil),
		m.collectors...,
	)

	metersSnapshot := copyMeters(m.meters)

	m.mu.Unlock()

	if err := m.collectAndFeedWith(
		collectorsSnapshot,
		metersSnapshot,
	); err != nil {
		return err
	}

	// Evaluate all metrics.
	metricIDs := make([]string, 0, len(metersSnapshot))

	for name := range metersSnapshot {
		metricIDs = append(metricIDs, name)
	}
	//todo: make this function return the events generated by the monitor.
	return m.measureAndFeedWith(
		metersSnapshot,
		metricIDs,
	)
}

// -----------------------------------------------------------------------------
// COLLECTION
// -----------------------------------------------------------------------------

// collectAndFeed collects all counters from collectors due for this interval.
//
// Raw samples are immediately fed into all meters that consume them.
//
// No metric is evaluated here.
func (m *ResourceMonitor) collectAndFeed(collectorsSnapshot []collectors.Collector) error {
	m.mu.Lock()
	metersSnapshot := copyMeters(m.meters)
	m.mu.Unlock()

	return m.collectAndFeedWith(collectorsSnapshot, metersSnapshot)
}

func (m *ResourceMonitor) collectAndFeedWith(collectorsSnapshot []collectors.Collector, metersSnapshot map[string]meters.Meter) error {
	if len(collectorsSnapshot) == 0 {
		return nil
	}

	var samples []*monitoring.DataSample

	for _, collector := range collectorsSnapshot {
		if collector == nil {
			continue
		}

		counters := collector.Counters()

		if len(counters) == 0 {
			continue
		}

		//fmt.Println("collecting data: ", counters)
		collected, err := collector.Collect(m.ctx)
		if err != nil {
			return fmt.Errorf(
				"collector %q failed: %w",
				collector.Protocol(),
				err,
			)
		}

		samples = append(samples, collected...)
	}

	return feedMeters(metersSnapshot, samples)
}

// -----------------------------------------------------------------------------
// MEASUREMENT
// -----------------------------------------------------------------------------

// measureAndFeed evaluates only the metrics that are due.
//
// Metrics are evaluated in dependency order.
//
// When a metric produces a result:
//
//	metric result
//	     ↓
//	dependent meters
//	     ↓
//	further metric evaluation
//
// The metric's thresholds are evaluated immediately after its result
// has been produced.
func (m *ResourceMonitor) measureAndFeed(metricIDs []string) error {
	m.mu.Lock()

	metersSnapshot := copyMeters(m.meters)

	m.mu.Unlock()

	return m.measureAndFeedWith(metersSnapshot, metricIDs)
}

func (m *ResourceMonitor) measureAndFeedWith(metersSnapshot map[string]meters.Meter, metricIDs []string) error {

	m.mu.Lock()
	target := m.target
	m.mu.Unlock()

	// Metrics in this map are due for this measurement cycle.
	due := make(map[string]bool, len(metricIDs))

	for _, id := range metricIDs {
		if id != "" {
			due[id] = true
		}
	}

	// Only scheduled metrics are initially pending.
	pending := make(map[string]meters.Meter, len(metricIDs))

	for _, id := range metricIDs {
		meter, exists := metersSnapshot[id]

		if !exists {
			return fmt.Errorf(
				"scheduled metric %q is not registered",
				id,
			)
		}

		pending[id] = meter
	}

	// Evaluate scheduled metrics in dependency order.
	for len(pending) > 0 {

		progress := false

		for name, meter := range pending {
			metric := meter.Metric()

			if metric == nil {
				return fmt.Errorf(
					"meter %q has nil metric definition",
					name,
				)
			}

			// ------------------------------------------------
			// Check dependencies.
			// ------------------------------------------------
			//
			// If an input is another metric:
			//
			//   - if that metric is due now, wait for it
			//   - if it is not due, use its latest value already
			//     stored in this meter
			//
			// This is what allows different metric intervals.

			ready := true

			for _, inputID := range metric.InputIds {
				if inputID == "" {
					continue
				}

				// Raw counter.
				if _, isMetric := metersSnapshot[inputID]; !isMetric {
					continue
				}

				// The dependency is another metric.
				//
				// Only wait for it if it is scheduled for this
				// particular cycle.
				if !due[inputID] {
					continue
				}

				if _, stillPending := pending[inputID]; stillPending {
					ready = false
					break
				}
			}

			if !ready {
				continue
			}

			// Meter owns its own sample-window readiness.
			if !meter.Ready() {
				continue
			}
			// ------------------------------------------------
			// Evaluate the metric.
			// ------------------------------------------------

			result, err := meter.Evaluate(m.ctx)
			if err != nil {
				return fmt.Errorf(
					"evaluate meter %q: %w",
					name,
					err,
				)
			}

			if result == nil {
				return fmt.Errorf(
					"meter %q returned nil result",
					name,
				)
			}

			// The result represents this metric.
			result.Id = name
			result.Kind = monitoring.DataType_METRIC

			if result.Source == nil {
				result.Source = target
			}

			// ------------------------------------------------
			// Propagate metric result.
			// ------------------------------------------------

			if err := feedMetricResult(metersSnapshot, result); err != nil {
				return err
			}

			// ------------------------------------------------
			// Evaluate this metric's thresholds immediately.
			// ------------------------------------------------

			if err := m.evaluateMetricThresholds(metric, result, target); err != nil {
				return err
			}

			delete(pending, name)
			progress = true
		}

		if !progress {
			//TODO: separate error for dependency cycle vs. meter not ready. not ready should not be an error,
			//  just skip it until next cycle.
			return fmt.Errorf(
				"cannot evaluate scheduled metrics: unresolved dependency, dependency cycle, or meter not ready",
			)
		}
	}

	return nil
}

// -----------------------------------------------------------------------------
// METER FEEDING
// -----------------------------------------------------------------------------

// feedMeters feeds raw samples into all meters that consume the sample ID.
func feedMeters(metersMap map[string]meters.Meter, samples []*monitoring.DataSample) error {
	for _, sample := range samples {
		if sample == nil {
			continue
		}

		for _, meter := range metersMap {
			if !meter.UsesInput(sample.Id) {
				continue
			}

			if err := meter.AddSample(sample); err != nil {
				return fmt.Errorf(
					"meter %q rejected input %q: %w",
					meter.Name(),
					sample.Id,
					err,
				)
			}
		}
	}

	return nil
}

// feedMetricResult propagates a calculated metric into all dependent meters.
func feedMetricResult(metersMap map[string]meters.Meter, result *monitoring.DataSample) error {
	if result == nil {
		return nil
	}

	for _, meter := range metersMap {
		// Never feed a metric into itself.
		if meter.Name() == result.Id {
			continue
		}

		if !meter.UsesInput(result.Id) {
			continue
		}

		if err := meter.AddSample(result); err != nil {
			return fmt.Errorf(
				"meter %q rejected metric %q: %w",
				meter.Name(),
				result.Id,
				err,
			)
		}
	}

	return nil
}

// -----------------------------------------------------------------------------
// THRESHOLDS / EVENTS
// -----------------------------------------------------------------------------

// evaluateMetricThresholds evaluates all thresholds belonging to one metric.
//
// There is deliberately NO ticker here.
//
// The sequence is:
//
//	metric evaluated
//	    ↓
//	result produced
//	    ↓
//	thresholds evaluated
//	    ↓
//	event generated
//	    ↓
//	eventHandler(event)
//
// The monitor generates the event, but the engine owns what happens
// because the event handler belongs to the engine.
func (m *ResourceMonitor) evaluateMetricThresholds(metric *monitoring.Metric, result *monitoring.DataSample, target *monitoring.ResourceKey) error {
	if metric == nil || result == nil {
		return nil
	}

	for _, threshold := range metric.Thresholds {
		if threshold == nil {
			continue
		}

		triggered, err := thresholdTriggered(result.Value, threshold)
		if err != nil {
			return fmt.Errorf(
				"evaluate threshold for metric %q: %w",
				metric.Name,
				err,
			)
		}

		if !triggered {
			continue
		}

		if threshold.Event == nil {
			return fmt.Errorf(
				"metric %q threshold has no event",
				metric.Name,
			)
		}

		// The threshold owns the event policy.
		//
		// Clone it because the event inside the metric
		// definition is configuration and must not be mutated.
		event, ok := proto.Clone(threshold.Event).(*monitoring.MonitoringEvent)
		if !ok || event == nil {
			return fmt.Errorf(
				"failed to clone event for metric %q",
				metric.Name,
			)
		}

		// The monitor owns the resource being monitored.
		event.Source = target

		// ----------------------------------------------------
		// Dispatch event to the engine.
		// ----------------------------------------------------
		if m.eventHandler != nil {
			if err := m.eventHandler(event); err != nil {
				return fmt.Errorf(
					"event handler failed for metric %q: %w",
					metric.Name,
					err,
				)
			}
		}
	}

	return nil
}

// thresholdTriggered evaluates one threshold against a value.
func thresholdTriggered(value float64, threshold *monitoring.Threshold) (bool, error) {
	if threshold == nil {
		return false, fmt.Errorf(
			"threshold is nil",
		)
	}

	switch threshold.Comparison {

	case monitoring.Comparison_GREATER_THAN:
		return value > threshold.Value, nil

	case monitoring.Comparison_GREATER_OR_EQUAL:
		return value >= threshold.Value, nil

	case monitoring.Comparison_LESS_THAN:
		return value < threshold.Value, nil

	case monitoring.Comparison_LESS_OR_EQUAL:
		return value <= threshold.Value, nil

	case monitoring.Comparison_EQUAL:
		return value == threshold.Value, nil

	case monitoring.Comparison_NOT_EQUAL:
		return value != threshold.Value, nil

	case monitoring.Comparison_COMPARISON_UNSPECIFIED:
		return false, fmt.Errorf(
			"comparison is unspecified",
		)

	default:
		return false, fmt.Errorf(
			"unsupported comparison: %v",
			threshold.Comparison,
		)
	}
}

// -----------------------------------------------------------------------------
// SCHEDULER
// -----------------------------------------------------------------------------

// buildSchedule creates one ticker for every distinct interval.
//
// Example:
//
//	collector C1 → 1s
//	collector C2 → 1s
//	metric M1    → 1s
//	metric M2    → 5s
//
// produces:
//
//	1s ticker → C1, C2, M1
//	5s ticker → M2
//
// There is still only ONE goroutine consuming all these tickers.
func buildSchedule(collectorsList []collectors.Collector, metersMap map[string]meters.Meter) ([]*scheduleGroup, error) {
	groups := make(
		map[time.Duration]*scheduleGroup,
	)

	// ------------------------------------------------------------
	// Group collectors by polling interval.
	// ------------------------------------------------------------

	for _, collector := range collectorsList {
		if collector == nil {
			continue
		}

		interval := time.Duration(collector.PollInterval()) * time.Millisecond

		if interval <= 0 {
			return nil, fmt.Errorf(
				"collector %q has invalid polling interval",
				collector.Protocol(),
			)
		}

		if len(collector.Counters()) == 0 {
			continue
		}

		group := groups[interval]

		if group == nil {
			group = &scheduleGroup{
				interval: interval,
			}

			groups[interval] = group
		}

		group.collectors = append(
			group.collectors,
			collector,
		)
	}

	// ------------------------------------------------------------
	// Group metrics by evaluation interval.
	// ------------------------------------------------------------

	for name, meter := range metersMap {
		metric := meter.Metric()

		if metric == nil {
			return nil, fmt.Errorf(
				"meter %q has nil metric definition",
				name,
			)
		}

		interval := time.Duration(
			metric.EvaluationIntervalMs,
		) * time.Millisecond

		if interval <= 0 {
			return nil, fmt.Errorf(
				"metric %q has invalid evaluation interval",
				name,
			)
		}

		group := groups[interval]

		if group == nil {
			group = &scheduleGroup{
				interval: interval,
			}

			groups[interval] = group
		}

		group.metricIDs = append(
			group.metricIDs,
			name,
		)
	}

	// ------------------------------------------------------------
	// Create one ticker for every distinct interval.
	// ------------------------------------------------------------

	schedule := make([]*scheduleGroup, 0, len(groups))

	for _, group := range groups {
		group.ticker = time.NewTicker(group.interval)
		schedule = append(schedule, group)
	}

	return schedule, nil
}

func stopSchedule(schedule []*scheduleGroup) {
	for _, group := range schedule {
		if group == nil || group.ticker == nil {
			continue
		}

		group.ticker.Stop()
	}
}

// -----------------------------------------------------------------------------
// HELPERS
// -----------------------------------------------------------------------------

func copyMeters(source map[string]meters.Meter) map[string]meters.Meter {
	result := make(map[string]meters.Meter, len(source))
	for name, meter := range source {
		result[name] = meter
	}
	return result
}

// -----------------------------------------------------------------------------
// Dynamic select
// -----------------------------------------------------------------------------

// Go's normal select requires statically known cases.
//
// Because the number of schedule groups is dynamic, reflect.Select lets
// the single scheduler goroutine wait on:
//
//	stopCh
//	ticker 1
//	ticker 2
//	ticker 3
//	...
//
// There is still only ONE scheduler goroutine.
type reflectSelectCase struct {
	stopCh   <-chan struct{}
	tickerCh <-chan time.Time
	group    *scheduleGroup
}

// creates the cases and returns the index of the case that fired.
func selectSchedule(cases []reflectSelectCase) int {
	selectCases := make([]reflect.SelectCase, len(cases))

	for i, item := range cases {
		if i == 0 {
			selectCases[i] = reflect.SelectCase{
				Dir:  reflect.SelectRecv,
				Chan: reflect.ValueOf(item.stopCh),
			}

			continue
		}

		selectCases[i] = reflect.SelectCase{
			Dir:  reflect.SelectRecv,
			Chan: reflect.ValueOf(item.tickerCh),
		}
	}

	chosen, _, _ := reflect.Select(selectCases)

	return chosen
}
