// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/pcp/pcp.proto

package pcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines how the eight PCP/DEI combinations are interpreted.
//
// P = priority levels
// D = drop-eligible levels
//
// IEEE 802.1Q defines the following PCP mapping formats:
//
//	8P0D - 8 priorities, 0 drop-eligible levels
//	7P1D - 7 priorities, 1 drop-eligible level
//	6P2D - 6 priorities, 2 drop-eligible levels
//	5P3D - 5 priorities, 3 drop-eligible levels
type PcpType int32

const (
	PcpType_PCP_TYPE_UNSPECIFIED PcpType = 0
	PcpType_PCP_TYPE_8P0D        PcpType = 1
	PcpType_PCP_TYPE_7P1D        PcpType = 2
	PcpType_PCP_TYPE_6P2D        PcpType = 3
	PcpType_PCP_TYPE_5P3D        PcpType = 4
)

// Enum value maps for PcpType.
var (
	PcpType_name = map[int32]string{
		0: "PCP_TYPE_UNSPECIFIED",
		1: "PCP_TYPE_8P0D",
		2: "PCP_TYPE_7P1D",
		3: "PCP_TYPE_6P2D",
		4: "PCP_TYPE_5P3D",
	}
	PcpType_value = map[string]int32{
		"PCP_TYPE_UNSPECIFIED": 0,
		"PCP_TYPE_8P0D":        1,
		"PCP_TYPE_7P1D":        2,
		"PCP_TYPE_6P2D":        3,
		"PCP_TYPE_5P3D":        4,
	}
)

func (x PcpType) Enum() *PcpType {
	p := new(PcpType)
	*p = x
	return p
}

func (x PcpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PcpType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_structures_pcp_pcp_proto_enumTypes[0].Descriptor()
}

func (PcpType) Type() protoreflect.EnumType {
	return &file_common_structures_pcp_pcp_proto_enumTypes[0]
}

func (x PcpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PcpType.Descriptor instead.
func (PcpType) EnumDescriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{0}
}

// Complete PCP configuration for a bridge port.
//
// PCP enablement is kept in the topology port configuration.
//
// This message contains the PCP-specific IEEE tables.
type PcpPortConfig struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	TrafficClassTable    []*TrafficClassMappingEntry `protobuf:"bytes,1,rep,name=traffic_class_table,json=trafficClassTable,proto3" json:"traffic_class_table,omitempty"`
	EncodingTables       []*PcpEncodingTable         `protobuf:"bytes,2,rep,name=encoding_tables,json=encodingTables,proto3" json:"encoding_tables,omitempty"`
	DecodingTables       []*PcpDecodingTable         `protobuf:"bytes,3,rep,name=decoding_tables,json=decodingTables,proto3" json:"decoding_tables,omitempty"`
	PriorityRegeneration *PriorityRegenerationTable  `protobuf:"bytes,4,opt,name=priority_regeneration,json=priorityRegeneration,proto3,oneof" json:"priority_regeneration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PcpPortConfig) Reset() {
	*x = PcpPortConfig{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcpPortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcpPortConfig) ProtoMessage() {}

func (x *PcpPortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcpPortConfig.ProtoReflect.Descriptor instead.
func (*PcpPortConfig) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{0}
}

func (x *PcpPortConfig) GetTrafficClassTable() []*TrafficClassMappingEntry {
	if x != nil {
		return x.TrafficClassTable
	}
	return nil
}

func (x *PcpPortConfig) GetEncodingTables() []*PcpEncodingTable {
	if x != nil {
		return x.EncodingTables
	}
	return nil
}

func (x *PcpPortConfig) GetDecodingTables() []*PcpDecodingTable {
	if x != nil {
		return x.DecodingTables
	}
	return nil
}

func (x *PcpPortConfig) GetPriorityRegeneration() *PriorityRegenerationTable {
	if x != nil {
		return x.PriorityRegeneration
	}
	return nil
}

// IEEE 802.1Q Clause 8.6.6.1
// Per-port Priority to traffic class (=egress queue id) mapping
type TrafficClassMappingEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`                                  // Priority Code Point (0–7)
	EgressQueueId uint32                 `protobuf:"varint,2,opt,name=egress_queue_id,json=egressQueueId,proto3" json:"egress_queue_id,omitempty"` // Traffic class index (0–7)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficClassMappingEntry) Reset() {
	*x = TrafficClassMappingEntry{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficClassMappingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficClassMappingEntry) ProtoMessage() {}

func (x *TrafficClassMappingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficClassMappingEntry.ProtoReflect.Descriptor instead.
func (*TrafficClassMappingEntry) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficClassMappingEntry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TrafficClassMappingEntry) GetEgressQueueId() uint32 {
	if x != nil {
		return x.EgressQueueId
	}
	return 0
}

// A single PCP encoding entry.
//
// Maps an internal priority and DEI value to a Priority Code Point.
//
// priority:
//
//	Internal priority value, 0..7.
//
// dei:
//
//	Drop Eligible Indicator.
//
// priority_code_point:
//
//	PCP value placed into the transmitted VLAN tag, 0..7.
type PcpEncodingEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Priority          uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Dei               bool                   `protobuf:"varint,2,opt,name=dei,proto3" json:"dei,omitempty"`
	PriorityCodePoint uint32                 `protobuf:"varint,3,opt,name=priority_code_point,json=priorityCodePoint,proto3" json:"priority_code_point,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PcpEncodingEntry) Reset() {
	*x = PcpEncodingEntry{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcpEncodingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcpEncodingEntry) ProtoMessage() {}

func (x *PcpEncodingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcpEncodingEntry.ProtoReflect.Descriptor instead.
func (*PcpEncodingEntry) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{2}
}

func (x *PcpEncodingEntry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PcpEncodingEntry) GetDei() bool {
	if x != nil {
		return x.Dei
	}
	return false
}

func (x *PcpEncodingEntry) GetPriorityCodePoint() uint32 {
	if x != nil {
		return x.PriorityCodePoint
	}
	return 0
}

// PCP encoding table for a specific PCP mapping type.
type PcpEncodingTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcpType       PcpType                `protobuf:"varint,1,opt,name=pcp_type,json=pcpType,proto3,enum=pcp.PcpType" json:"pcp_type,omitempty"`
	Entries       []*PcpEncodingEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcpEncodingTable) Reset() {
	*x = PcpEncodingTable{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcpEncodingTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcpEncodingTable) ProtoMessage() {}

func (x *PcpEncodingTable) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcpEncodingTable.ProtoReflect.Descriptor instead.
func (*PcpEncodingTable) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{3}
}

func (x *PcpEncodingTable) GetPcpType() PcpType {
	if x != nil {
		return x.PcpType
	}
	return PcpType_PCP_TYPE_UNSPECIFIED
}

func (x *PcpEncodingTable) GetEntries() []*PcpEncodingEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// A single PCP decoding entry.
//
// Maps an incoming Priority Code Point to an internal priority and DEI value.
type PcpDecodingEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PriorityCodePoint uint32                 `protobuf:"varint,1,opt,name=priority_code_point,json=priorityCodePoint,proto3" json:"priority_code_point,omitempty"`
	Priority          uint32                 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Dei               bool                   `protobuf:"varint,3,opt,name=dei,proto3" json:"dei,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PcpDecodingEntry) Reset() {
	*x = PcpDecodingEntry{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcpDecodingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcpDecodingEntry) ProtoMessage() {}

func (x *PcpDecodingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcpDecodingEntry.ProtoReflect.Descriptor instead.
func (*PcpDecodingEntry) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{4}
}

func (x *PcpDecodingEntry) GetPriorityCodePoint() uint32 {
	if x != nil {
		return x.PriorityCodePoint
	}
	return 0
}

func (x *PcpDecodingEntry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PcpDecodingEntry) GetDei() bool {
	if x != nil {
		return x.Dei
	}
	return false
}

// PCP decoding table for a specific PCP mapping type.
type PcpDecodingTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PcpType       PcpType                `protobuf:"varint,1,opt,name=pcp_type,json=pcpType,proto3,enum=pcp.PcpType" json:"pcp_type,omitempty"`
	Entries       []*PcpDecodingEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcpDecodingTable) Reset() {
	*x = PcpDecodingTable{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcpDecodingTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcpDecodingTable) ProtoMessage() {}

func (x *PcpDecodingTable) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcpDecodingTable.ProtoReflect.Descriptor instead.
func (*PcpDecodingTable) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{5}
}

func (x *PcpDecodingTable) GetPcpType() PcpType {
	if x != nil {
		return x.PcpType
	}
	return PcpType_PCP_TYPE_UNSPECIFIED
}

func (x *PcpDecodingTable) GetEntries() []*PcpDecodingEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Defines regeneration of an internal priority.
//
// The priority value represents the input priority and
// regenerated_priority represents the resulting priority.
type PriorityRegenerationEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Priority            uint32                 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	RegeneratedPriority uint32                 `protobuf:"varint,2,opt,name=regenerated_priority,json=regeneratedPriority,proto3" json:"regenerated_priority,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PriorityRegenerationEntry) Reset() {
	*x = PriorityRegenerationEntry{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityRegenerationEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityRegenerationEntry) ProtoMessage() {}

func (x *PriorityRegenerationEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityRegenerationEntry.ProtoReflect.Descriptor instead.
func (*PriorityRegenerationEntry) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{6}
}

func (x *PriorityRegenerationEntry) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PriorityRegenerationEntry) GetRegeneratedPriority() uint32 {
	if x != nil {
		return x.RegeneratedPriority
	}
	return 0
}

// Priority regeneration configuration for a port.
type PriorityRegenerationTable struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entries       []*PriorityRegenerationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriorityRegenerationTable) Reset() {
	*x = PriorityRegenerationTable{}
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriorityRegenerationTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriorityRegenerationTable) ProtoMessage() {}

func (x *PriorityRegenerationTable) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_pcp_pcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriorityRegenerationTable.ProtoReflect.Descriptor instead.
func (*PriorityRegenerationTable) Descriptor() ([]byte, []int) {
	return file_common_structures_pcp_pcp_proto_rawDescGZIP(), []int{7}
}

func (x *PriorityRegenerationTable) GetEntries() []*PriorityRegenerationEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_common_structures_pcp_pcp_proto protoreflect.FileDescriptor

const file_common_structures_pcp_pcp_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon/structures/pcp/pcp.proto\x12\x03pcp\"\xd2\x02\n" +
	"\rPcpPortConfig\x12M\n" +
	"\x13traffic_class_table\x18\x01 \x03(\v2\x1d.pcp.TrafficClassMappingEntryR\x11trafficClassTable\x12>\n" +
	"\x0fencoding_tables\x18\x02 \x03(\v2\x15.pcp.PcpEncodingTableR\x0eencodingTables\x12>\n" +
	"\x0fdecoding_tables\x18\x03 \x03(\v2\x15.pcp.PcpDecodingTableR\x0edecodingTables\x12X\n" +
	"\x15priority_regeneration\x18\x04 \x01(\v2\x1e.pcp.PriorityRegenerationTableH\x00R\x14priorityRegeneration\x88\x01\x01B\x18\n" +
	"\x16_priority_regeneration\"^\n" +
	"\x18TrafficClassMappingEntry\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12&\n" +
	"\x0fegress_queue_id\x18\x02 \x01(\rR\regressQueueId\"p\n" +
	"\x10PcpEncodingEntry\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x12\x10\n" +
	"\x03dei\x18\x02 \x01(\bR\x03dei\x12.\n" +
	"\x13priority_code_point\x18\x03 \x01(\rR\x11priorityCodePoint\"l\n" +
	"\x10PcpEncodingTable\x12'\n" +
	"\bpcp_type\x18\x01 \x01(\x0e2\f.pcp.PcpTypeR\apcpType\x12/\n" +
	"\aentries\x18\x02 \x03(\v2\x15.pcp.PcpEncodingEntryR\aentries\"p\n" +
	"\x10PcpDecodingEntry\x12.\n" +
	"\x13priority_code_point\x18\x01 \x01(\rR\x11priorityCodePoint\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\x12\x10\n" +
	"\x03dei\x18\x03 \x01(\bR\x03dei\"l\n" +
	"\x10PcpDecodingTable\x12'\n" +
	"\bpcp_type\x18\x01 \x01(\x0e2\f.pcp.PcpTypeR\apcpType\x12/\n" +
	"\aentries\x18\x02 \x03(\v2\x15.pcp.PcpDecodingEntryR\aentries\"j\n" +
	"\x19PriorityRegenerationEntry\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\rR\bpriority\x121\n" +
	"\x14regenerated_priority\x18\x02 \x01(\rR\x13regeneratedPriority\"U\n" +
	"\x19PriorityRegenerationTable\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.pcp.PriorityRegenerationEntryR\aentries*o\n" +
	"\aPcpType\x12\x18\n" +
	"\x14PCP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPCP_TYPE_8P0D\x10\x01\x12\x11\n" +
	"\rPCP_TYPE_7P1D\x10\x02\x12\x11\n" +
	"\rPCP_TYPE_6P2D\x10\x03\x12\x11\n" +
	"\rPCP_TYPE_5P3D\x10\x04B\x06Z\x04/pcpb\x06proto3"

var (
	file_common_structures_pcp_pcp_proto_rawDescOnce sync.Once
	file_common_structures_pcp_pcp_proto_rawDescData []byte
)

func file_common_structures_pcp_pcp_proto_rawDescGZIP() []byte {
	file_common_structures_pcp_pcp_proto_rawDescOnce.Do(func() {
		file_common_structures_pcp_pcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_pcp_pcp_proto_rawDesc), len(file_common_structures_pcp_pcp_proto_rawDesc)))
	})
	return file_common_structures_pcp_pcp_proto_rawDescData
}

var file_common_structures_pcp_pcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_structures_pcp_pcp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_structures_pcp_pcp_proto_goTypes = []any{
	(PcpType)(0),                      // 0: pcp.PcpType
	(*PcpPortConfig)(nil),             // 1: pcp.PcpPortConfig
	(*TrafficClassMappingEntry)(nil),  // 2: pcp.TrafficClassMappingEntry
	(*PcpEncodingEntry)(nil),          // 3: pcp.PcpEncodingEntry
	(*PcpEncodingTable)(nil),          // 4: pcp.PcpEncodingTable
	(*PcpDecodingEntry)(nil),          // 5: pcp.PcpDecodingEntry
	(*PcpDecodingTable)(nil),          // 6: pcp.PcpDecodingTable
	(*PriorityRegenerationEntry)(nil), // 7: pcp.PriorityRegenerationEntry
	(*PriorityRegenerationTable)(nil), // 8: pcp.PriorityRegenerationTable
}
var file_common_structures_pcp_pcp_proto_depIdxs = []int32{
	2, // 0: pcp.PcpPortConfig.traffic_class_table:type_name -> pcp.TrafficClassMappingEntry
	4, // 1: pcp.PcpPortConfig.encoding_tables:type_name -> pcp.PcpEncodingTable
	6, // 2: pcp.PcpPortConfig.decoding_tables:type_name -> pcp.PcpDecodingTable
	8, // 3: pcp.PcpPortConfig.priority_regeneration:type_name -> pcp.PriorityRegenerationTable
	0, // 4: pcp.PcpEncodingTable.pcp_type:type_name -> pcp.PcpType
	3, // 5: pcp.PcpEncodingTable.entries:type_name -> pcp.PcpEncodingEntry
	0, // 6: pcp.PcpDecodingTable.pcp_type:type_name -> pcp.PcpType
	5, // 7: pcp.PcpDecodingTable.entries:type_name -> pcp.PcpDecodingEntry
	7, // 8: pcp.PriorityRegenerationTable.entries:type_name -> pcp.PriorityRegenerationEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_common_structures_pcp_pcp_proto_init() }
func file_common_structures_pcp_pcp_proto_init() {
	if File_common_structures_pcp_pcp_proto != nil {
		return
	}
	file_common_structures_pcp_pcp_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_pcp_pcp_proto_rawDesc), len(file_common_structures_pcp_pcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_pcp_pcp_proto_goTypes,
		DependencyIndexes: file_common_structures_pcp_pcp_proto_depIdxs,
		EnumInfos:         file_common_structures_pcp_pcp_proto_enumTypes,
		MessageInfos:      file_common_structures_pcp_pcp_proto_msgTypes,
	}.Build()
	File_common_structures_pcp_pcp_proto = out.File
	file_common_structures_pcp_pcp_proto_goTypes = nil
	file_common_structures_pcp_pcp_proto_depIdxs = nil
}
