// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/devicemodelregistry/devicemodelregistry.proto

package devicemodelregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,json=model-name,proto3" json:"name,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	YangFiles     []*YangModule          `protobuf:"bytes,4,rep,name=yangFiles,json=yang-files,proto3" json:"yangFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceModel) Reset() {
	*x = DeviceModel{}
	mi := &file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceModel) ProtoMessage() {}

func (x *DeviceModel) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceModel.ProtoReflect.Descriptor instead.
func (*DeviceModel) Descriptor() ([]byte, []int) {
	return file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceModel) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *DeviceModel) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DeviceModel) GetYangFiles() []*YangModule {
	if x != nil {
		return x.YangFiles
	}
	return nil
}

type YangModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,json=file-name,proto3" json:"name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,json=file-revision,proto3" json:"revision,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YangModule) Reset() {
	*x = YangModule{}
	mi := &file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YangModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YangModule) ProtoMessage() {}

func (x *YangModule) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YangModule.ProtoReflect.Descriptor instead.
func (*YangModule) Descriptor() ([]byte, []int) {
	return file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescGZIP(), []int{1}
}

func (x *YangModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YangModule) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *YangModule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_common_structures_devicemodelregistry_devicemodelregistry_proto protoreflect.FileDescriptor

const file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDesc = "" +
	"\n" +
	"?common/structures/devicemodelregistry/devicemodelregistry.proto\x12\x13devicemodelregistry\"\x99\x01\n" +
	"\vDeviceModel\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tR\n" +
	"model-name\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12>\n" +
	"\tyangFiles\x18\x04 \x03(\v2\x1f.devicemodelregistry.YangModuleR\n" +
	"yang-files\"h\n" +
	"\n" +
	"YangModule\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tR\tfile-name\x12\x1f\n" +
	"\brevision\x18\x02 \x01(\tR\rfile-revision\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB\x17Z\x15./devicemodelregistryb\x06proto3"

var (
	file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescOnce sync.Once
	file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescData []byte
)

func file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescGZIP() []byte {
	file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescOnce.Do(func() {
		file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDesc), len(file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDesc)))
	})
	return file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDescData
}

var file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_structures_devicemodelregistry_devicemodelregistry_proto_goTypes = []any{
	(*DeviceModel)(nil), // 0: devicemodelregistry.DeviceModel
	(*YangModule)(nil),  // 1: devicemodelregistry.YangModule
}
var file_common_structures_devicemodelregistry_devicemodelregistry_proto_depIdxs = []int32{
	1, // 0: devicemodelregistry.DeviceModel.yangFiles:type_name -> devicemodelregistry.YangModule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_structures_devicemodelregistry_devicemodelregistry_proto_init() }
func file_common_structures_devicemodelregistry_devicemodelregistry_proto_init() {
	if File_common_structures_devicemodelregistry_devicemodelregistry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDesc), len(file_common_structures_devicemodelregistry_devicemodelregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_devicemodelregistry_devicemodelregistry_proto_goTypes,
		DependencyIndexes: file_common_structures_devicemodelregistry_devicemodelregistry_proto_depIdxs,
		MessageInfos:      file_common_structures_devicemodelregistry_devicemodelregistry_proto_msgTypes,
	}.Build()
	File_common_structures_devicemodelregistry_devicemodelregistry_proto = out.File
	file_common_structures_devicemodelregistry_devicemodelregistry_proto_goTypes = nil
	file_common_structures_devicemodelregistry_devicemodelregistry_proto_depIdxs = nil
}
