syntax="proto3";
package devicemodelregistry;

option go_package = "./devicemodelregistry";  // Use './' to indicate the current directory

message DeviceModel {
    string name = 1 [json_name="model-name"];
    string vendor = 2 [json_name="vendor"];
    string software = 3 [json_name="software"];
    repeated YangModule yangFiles = 4 [json_name="yang-files"];
   
}

message YangModule {
    string name = 1 [json_name="file-name"];
    string revision = 2 [json_name="file-revision"];
    string description = 3 [json_name="description"];
}