// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: common/structures/credentials/credentials.proto

package credentials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Credentials used by the CNC to authenticate to a managed device.
//
// The credential itself does not describe:
//   - which node it belongs to
//   - which management protocol is being used
//   - which transport is being used
//
// Those belong to the management/topology configuration.
//
// Example combinations:
//
//	NETCONF + SSH + USERNAME_PASSWORD
//	NETCONF + SSH + SSH_PRIVATE_KEY
//	NETCONF + TLS + TLS_CLIENT_CERTIFICATE
//	gNMI    + TLS + TLS_CLIENT_CERTIFICATE
//	SNMP    + UDP + SNMP_V2C_COMMUNITY
//	SNMP    + UDP + SNMP_V3
type ManagementCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Authentication:
	//
	//	*ManagementCredentials_UsernamePassword
	//	*ManagementCredentials_SshPrivateKey
	//	*ManagementCredentials_TlsClientCertificate
	//	*ManagementCredentials_SnmpV2CCommunity
	//	*ManagementCredentials_SnmpV3
	Authentication isManagementCredentials_Authentication `protobuf_oneof:"authentication"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagementCredentials) Reset() {
	*x = ManagementCredentials{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagementCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementCredentials) ProtoMessage() {}

func (x *ManagementCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementCredentials.ProtoReflect.Descriptor instead.
func (*ManagementCredentials) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *ManagementCredentials) GetAuthentication() isManagementCredentials_Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *ManagementCredentials) GetUsernamePassword() *UsernamePassword {
	if x != nil {
		if x, ok := x.Authentication.(*ManagementCredentials_UsernamePassword); ok {
			return x.UsernamePassword
		}
	}
	return nil
}

func (x *ManagementCredentials) GetSshPrivateKey() *SshPrivateKey {
	if x != nil {
		if x, ok := x.Authentication.(*ManagementCredentials_SshPrivateKey); ok {
			return x.SshPrivateKey
		}
	}
	return nil
}

func (x *ManagementCredentials) GetTlsClientCertificate() *TlsClientCertificate {
	if x != nil {
		if x, ok := x.Authentication.(*ManagementCredentials_TlsClientCertificate); ok {
			return x.TlsClientCertificate
		}
	}
	return nil
}

func (x *ManagementCredentials) GetSnmpV2CCommunity() *SnmpV2CCommunity {
	if x != nil {
		if x, ok := x.Authentication.(*ManagementCredentials_SnmpV2CCommunity); ok {
			return x.SnmpV2CCommunity
		}
	}
	return nil
}

func (x *ManagementCredentials) GetSnmpV3() *SnmpV3Credentials {
	if x != nil {
		if x, ok := x.Authentication.(*ManagementCredentials_SnmpV3); ok {
			return x.SnmpV3
		}
	}
	return nil
}

type isManagementCredentials_Authentication interface {
	isManagementCredentials_Authentication()
}

type ManagementCredentials_UsernamePassword struct {
	UsernamePassword *UsernamePassword `protobuf:"bytes,1,opt,name=username_password,json=usernamePassword,proto3,oneof"`
}

type ManagementCredentials_SshPrivateKey struct {
	SshPrivateKey *SshPrivateKey `protobuf:"bytes,2,opt,name=ssh_private_key,json=sshPrivateKey,proto3,oneof"`
}

type ManagementCredentials_TlsClientCertificate struct {
	TlsClientCertificate *TlsClientCertificate `protobuf:"bytes,3,opt,name=tls_client_certificate,json=tlsClientCertificate,proto3,oneof"`
}

type ManagementCredentials_SnmpV2CCommunity struct {
	SnmpV2CCommunity *SnmpV2CCommunity `protobuf:"bytes,4,opt,name=snmp_v2c_community,json=snmpV2cCommunity,proto3,oneof"`
}

type ManagementCredentials_SnmpV3 struct {
	SnmpV3 *SnmpV3Credentials `protobuf:"bytes,5,opt,name=snmp_v3,json=snmpV3,proto3,oneof"`
}

func (*ManagementCredentials_UsernamePassword) isManagementCredentials_Authentication() {}

func (*ManagementCredentials_SshPrivateKey) isManagementCredentials_Authentication() {}

func (*ManagementCredentials_TlsClientCertificate) isManagementCredentials_Authentication() {}

func (*ManagementCredentials_SnmpV2CCommunity) isManagementCredentials_Authentication() {}

func (*ManagementCredentials_SnmpV3) isManagementCredentials_Authentication() {}

// Generic username/password authentication.
//
// Can be used by management protocols that support
// username/password authentication.
type UsernamePassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePassword) Reset() {
	*x = UsernamePassword{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePassword) ProtoMessage() {}

func (x *UsernamePassword) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePassword.ProtoReflect.Descriptor instead.
func (*UsernamePassword) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *UsernamePassword) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernamePassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// SSH public-key authentication.
//
// The private key is secret material and therefore belongs
// in the credential store rather than the topology.
type SshPrivateKey struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Username   string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKey string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Optional passphrase protecting the private key.
	Passphrase    *string `protobuf:"bytes,3,opt,name=passphrase,proto3,oneof" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SshPrivateKey) Reset() {
	*x = SshPrivateKey{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SshPrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshPrivateKey) ProtoMessage() {}

func (x *SshPrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshPrivateKey.ProtoReflect.Descriptor instead.
func (*SshPrivateKey) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *SshPrivateKey) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SshPrivateKey) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SshPrivateKey) GetPassphrase() string {
	if x != nil && x.Passphrase != nil {
		return *x.Passphrase
	}
	return ""
}

// TLS client certificate authentication.
//
// The private key is secret material.
//
// CA certificate is included here because the credential
// configuration may need to define the trust chain used
// when establishing the TLS connection.
type TlsClientCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CA certificate(s) used to validate the server.
	CaCertificate string `protobuf:"bytes,1,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	// Client certificate presented by the CNC.
	ClientCertificate string `protobuf:"bytes,2,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	// Private key corresponding to client_certificate.
	ClientPrivateKey string `protobuf:"bytes,3,opt,name=client_private_key,json=clientPrivateKey,proto3" json:"client_private_key,omitempty"`
	// Optional passphrase protecting the private key.
	PrivateKeyPassphrase *string `protobuf:"bytes,4,opt,name=private_key_passphrase,json=privateKeyPassphrase,proto3,oneof" json:"private_key_passphrase,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TlsClientCertificate) Reset() {
	*x = TlsClientCertificate{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsClientCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsClientCertificate) ProtoMessage() {}

func (x *TlsClientCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsClientCertificate.ProtoReflect.Descriptor instead.
func (*TlsClientCertificate) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *TlsClientCertificate) GetCaCertificate() string {
	if x != nil {
		return x.CaCertificate
	}
	return ""
}

func (x *TlsClientCertificate) GetClientCertificate() string {
	if x != nil {
		return x.ClientCertificate
	}
	return ""
}

func (x *TlsClientCertificate) GetClientPrivateKey() string {
	if x != nil {
		return x.ClientPrivateKey
	}
	return ""
}

func (x *TlsClientCertificate) GetPrivateKeyPassphrase() string {
	if x != nil && x.PrivateKeyPassphrase != nil {
		return *x.PrivateKeyPassphrase
	}
	return ""
}

// SNMPv2c community-based authentication.
type SnmpV2CCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     string                 `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnmpV2CCommunity) Reset() {
	*x = SnmpV2CCommunity{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnmpV2CCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV2CCommunity) ProtoMessage() {}

func (x *SnmpV2CCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV2CCommunity.ProtoReflect.Descriptor instead.
func (*SnmpV2CCommunity) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{4}
}

func (x *SnmpV2CCommunity) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

// SNMPv3 authentication.
//
// SNMPv3 separates authentication and privacy.
type SnmpV3Credentials struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Username               string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AuthenticationPassword *string                `protobuf:"bytes,2,opt,name=authentication_password,json=authenticationPassword,proto3,oneof" json:"authentication_password,omitempty"`
	PrivacyPassword        *string                `protobuf:"bytes,3,opt,name=privacy_password,json=privacyPassword,proto3,oneof" json:"privacy_password,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SnmpV3Credentials) Reset() {
	*x = SnmpV3Credentials{}
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnmpV3Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV3Credentials) ProtoMessage() {}

func (x *SnmpV3Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_common_structures_credentials_credentials_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV3Credentials.ProtoReflect.Descriptor instead.
func (*SnmpV3Credentials) Descriptor() ([]byte, []int) {
	return file_common_structures_credentials_credentials_proto_rawDescGZIP(), []int{5}
}

func (x *SnmpV3Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SnmpV3Credentials) GetAuthenticationPassword() string {
	if x != nil && x.AuthenticationPassword != nil {
		return *x.AuthenticationPassword
	}
	return ""
}

func (x *SnmpV3Credentials) GetPrivacyPassword() string {
	if x != nil && x.PrivacyPassword != nil {
		return *x.PrivacyPassword
	}
	return ""
}

var File_common_structures_credentials_credentials_proto protoreflect.FileDescriptor

const file_common_structures_credentials_credentials_proto_rawDesc = "" +
	"\n" +
	"/common/structures/credentials/credentials.proto\x12\vcredentials\"\xa2\x03\n" +
	"\x15ManagementCredentials\x12L\n" +
	"\x11username_password\x18\x01 \x01(\v2\x1d.credentials.UsernamePasswordH\x00R\x10usernamePassword\x12D\n" +
	"\x0fssh_private_key\x18\x02 \x01(\v2\x1a.credentials.SshPrivateKeyH\x00R\rsshPrivateKey\x12Y\n" +
	"\x16tls_client_certificate\x18\x03 \x01(\v2!.credentials.TlsClientCertificateH\x00R\x14tlsClientCertificate\x12M\n" +
	"\x12snmp_v2c_community\x18\x04 \x01(\v2\x1d.credentials.SnmpV2cCommunityH\x00R\x10snmpV2cCommunity\x129\n" +
	"\asnmp_v3\x18\x05 \x01(\v2\x1e.credentials.SnmpV3CredentialsH\x00R\x06snmpV3B\x10\n" +
	"\x0eauthentication\"J\n" +
	"\x10UsernamePassword\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x80\x01\n" +
	"\rSshPrivateKey\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12#\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tH\x00R\n" +
	"passphrase\x88\x01\x01B\r\n" +
	"\v_passphrase\"\xf0\x01\n" +
	"\x14TlsClientCertificate\x12%\n" +
	"\x0eca_certificate\x18\x01 \x01(\tR\rcaCertificate\x12-\n" +
	"\x12client_certificate\x18\x02 \x01(\tR\x11clientCertificate\x12,\n" +
	"\x12client_private_key\x18\x03 \x01(\tR\x10clientPrivateKey\x129\n" +
	"\x16private_key_passphrase\x18\x04 \x01(\tH\x00R\x14privateKeyPassphrase\x88\x01\x01B\x19\n" +
	"\x17_private_key_passphrase\"0\n" +
	"\x10SnmpV2cCommunity\x12\x1c\n" +
	"\tcommunity\x18\x01 \x01(\tR\tcommunity\"\xce\x01\n" +
	"\x11SnmpV3Credentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12<\n" +
	"\x17authentication_password\x18\x02 \x01(\tH\x00R\x16authenticationPassword\x88\x01\x01\x12.\n" +
	"\x10privacy_password\x18\x03 \x01(\tH\x01R\x0fprivacyPassword\x88\x01\x01B\x1a\n" +
	"\x18_authentication_passwordB\x13\n" +
	"\x11_privacy_passwordB\x0eZ\f/credentialsb\x06proto3"

var (
	file_common_structures_credentials_credentials_proto_rawDescOnce sync.Once
	file_common_structures_credentials_credentials_proto_rawDescData []byte
)

func file_common_structures_credentials_credentials_proto_rawDescGZIP() []byte {
	file_common_structures_credentials_credentials_proto_rawDescOnce.Do(func() {
		file_common_structures_credentials_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_structures_credentials_credentials_proto_rawDesc), len(file_common_structures_credentials_credentials_proto_rawDesc)))
	})
	return file_common_structures_credentials_credentials_proto_rawDescData
}

var file_common_structures_credentials_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_structures_credentials_credentials_proto_goTypes = []any{
	(*ManagementCredentials)(nil), // 0: credentials.ManagementCredentials
	(*UsernamePassword)(nil),      // 1: credentials.UsernamePassword
	(*SshPrivateKey)(nil),         // 2: credentials.SshPrivateKey
	(*TlsClientCertificate)(nil),  // 3: credentials.TlsClientCertificate
	(*SnmpV2CCommunity)(nil),      // 4: credentials.SnmpV2cCommunity
	(*SnmpV3Credentials)(nil),     // 5: credentials.SnmpV3Credentials
}
var file_common_structures_credentials_credentials_proto_depIdxs = []int32{
	1, // 0: credentials.ManagementCredentials.username_password:type_name -> credentials.UsernamePassword
	2, // 1: credentials.ManagementCredentials.ssh_private_key:type_name -> credentials.SshPrivateKey
	3, // 2: credentials.ManagementCredentials.tls_client_certificate:type_name -> credentials.TlsClientCertificate
	4, // 3: credentials.ManagementCredentials.snmp_v2c_community:type_name -> credentials.SnmpV2cCommunity
	5, // 4: credentials.ManagementCredentials.snmp_v3:type_name -> credentials.SnmpV3Credentials
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_structures_credentials_credentials_proto_init() }
func file_common_structures_credentials_credentials_proto_init() {
	if File_common_structures_credentials_credentials_proto != nil {
		return
	}
	file_common_structures_credentials_credentials_proto_msgTypes[0].OneofWrappers = []any{
		(*ManagementCredentials_UsernamePassword)(nil),
		(*ManagementCredentials_SshPrivateKey)(nil),
		(*ManagementCredentials_TlsClientCertificate)(nil),
		(*ManagementCredentials_SnmpV2CCommunity)(nil),
		(*ManagementCredentials_SnmpV3)(nil),
	}
	file_common_structures_credentials_credentials_proto_msgTypes[2].OneofWrappers = []any{}
	file_common_structures_credentials_credentials_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_structures_credentials_credentials_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_structures_credentials_credentials_proto_rawDesc), len(file_common_structures_credentials_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_structures_credentials_credentials_proto_goTypes,
		DependencyIndexes: file_common_structures_credentials_credentials_proto_depIdxs,
		MessageInfos:      file_common_structures_credentials_credentials_proto_msgTypes,
	}.Build()
	File_common_structures_credentials_credentials_proto = out.File
	file_common_structures_credentials_credentials_proto_goTypes = nil
	file_common_structures_credentials_credentials_proto_depIdxs = nil
}
